import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
assert.equal(process.env.GITHUB_ACTIONS,'true');
assert.equal(process.env.ROUND52_ISOLATED_CI,'true');
const imported=await import(pathToFileURL(process.env.ROUND52_PG_MODULE).href);
const {Client}=imported.default??imported;
const config={host:'127.0.0.1',port:55452,database:'round52',user:'postgres'};
const control=new Client(config);await control.connect();await control.query('CREATE DATABASE round57');await control.end();
const db=new Client({...config,database:'round57'});await db.connect();
const customer='9664d189-4a12-4caa-8243-dc73383447e6',technical='a212f9de-0364-427e-8473-2b0742a2d897',unknown='00000000-0000-4000-8000-000000000009';
try {
 await db.query(`CREATE SCHEMA auth; CREATE SCHEMA storage;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE TABLE user_roles(user_id uuid,role text);
 CREATE FUNCTION is_super_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM user_roles WHERE user_id=auth.uid() AND role='super_admin') $$;
 CREATE TABLE tenants(id uuid PRIMARY KEY,nome text);
 CREATE TABLE tenant_members(tenant_id uuid,user_id uuid,membership_status text);
 CREATE FUNCTION user_has_active_membership(u uuid,t uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM tenant_members WHERE user_id=u AND tenant_id=t AND membership_status='active') $$;
 CREATE TABLE system_events(id uuid,tenant_id uuid,created_at timestamptz,category text,source text,severity text,latency_ms integer,meta jsonb,event text,status_code integer,error_message text);
 CREATE TABLE leads(id uuid,tenant_id uuid);
 CREATE TABLE storage.objects(id uuid,name text);
 ALTER TABLE leads ENABLE ROW LEVEL SECURITY; CREATE POLICY legacy_super_allow ON leads FOR ALL TO authenticated USING (true) WITH CHECK (true);
 ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY; CREATE POLICY legacy_storage_allow ON storage.objects FOR ALL TO authenticated USING (true) WITH CHECK (true);
 GRANT USAGE ON SCHEMA public,auth,storage TO authenticated,service_role;
 GRANT ALL ON ALL TABLES IN SCHEMA public,storage TO authenticated,service_role;`);
 await db.query("INSERT INTO tenants VALUES ($1,'Fixture customer'),($2,'Fixture technical'),($3,'Fixture unclassified')",[customer,technical,unknown]);
 await db.query("INSERT INTO user_roles VALUES ($1,'super_admin');",[technical]);
 await db.query("INSERT INTO tenant_members VALUES ($1,$1,'active')",[customer]);
 await db.query("INSERT INTO leads VALUES ($1,$1)",[customer]);
 await db.query("INSERT INTO storage.objects VALUES ($1,'fixture')",[customer]);
 await db.query(readFileSync('database/round57-governance.sql','utf8'));
 const rows=(await db.query('SELECT id,operational_kind FROM tenants ORDER BY id')).rows;
 assert.equal(rows.find(r=>r.id===customer).operational_kind,'customer');
 assert.equal(rows.find(r=>r.id===technical).operational_kind,'technical');
 assert.equal(rows.find(r=>r.id===unknown).operational_kind,'unclassified');
 await db.query("SELECT set_config('request.jwt.claim.sub',$1,false), set_config('request.headers',$2,false)",[technical,JSON.stringify({'x-tenant-id':customer})]);
 await db.query('SET ROLE authenticated');
 assert.equal((await db.query('SELECT get_current_tenant_id() AS id')).rows[0].id,null);
 assert.equal((await db.query('SELECT count(*)::int n FROM leads')).rows[0].n,0);
 assert.equal((await db.query('SELECT count(*)::int n FROM storage.objects')).rows[0].n,0);
 await assert.rejects(db.query('INSERT INTO leads VALUES ($1,$2)',[unknown,customer]),/row-level security/);
 await db.query('RESET ROLE');
 await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[customer]);await db.query('SET ROLE authenticated');
 assert.equal((await db.query('SELECT get_current_tenant_id() AS id')).rows[0].id,customer);
 await db.query('RESET ROLE');await db.query('SET ROLE service_role');
 assert.equal((await db.query('SELECT count(*)::int n FROM leads')).rows[0].n,1);
 console.log('PASS Round57 isolated SQL: classification preserves all rows, technical and unknown excluded, forged Super Admin context fails, legacy permissive RLS cannot override restrictive denial, ordinary membership preserved, service authority retained.');
} finally {await db.end();}
