import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireTenant } from "@/integrations/supabase/tenant-middleware";
import { authorizeTenantCrmOperation, trustedTenantCrmContext, safeTenantCrmError } from "@/lib/api/tenant-crm-authority.server";
import { CRM_FUNCTIONAL_CAPABILITIES, CRM_FUNCTIONAL_CONTRACT, CRM_FUNCTIONAL_INPUT_SCHEMAS, CRM_COMMUNICATION_ADAPTER_STATE, CRM_ALERT_KEYS } from "@/lib/crm/crm-functional-registry";
import { SIGNED_URL_TTL_DOWNLOAD_SECONDS, validateTenantSignRequest } from "@/lib/storage/signed-url";
const uuid=z.string().uuid(); const trusted=(c:any)=>trustedTenantCrmContext(c);
async function db(){const {supabaseAdmin}=await import("@/integrations/supabase/client.server");return supabaseAdmin as any}
async function auth(c:any,op:any){return authorizeTenantCrmOperation(trusted(c),op)}
async function scope(a:any,x:any,leadId:string){const {data,error}=await a.rpc("crm_scope_allows_lead",{_tenant_id:x.tenantId,_actor_user_id:x.actorUserId,_scope:x.scope==="own"?"proprio":x.scope==="team"?"equipe":"global",_lead_id:leadId});if(error||data!==true)throw new Error("crm_scope_denied")}
async function list(c:any,op:any,table:string,filters:Record<string,any>={}){const x=await auth(c,op),a=await db();let q=a.from(table).select("*").eq("tenant_id",x.tenantId);for(const[k,v]of Object.entries(filters))if(v!=null)q=q.eq(k,v);const{data,error}=await q.limit(1000);if(error)throw safeTenantCrmError(error);return data??[]}
async function save(c:any,op:any,table:string,id:string|undefined,payload:any){const x=await auth(c,op),a=await db();if(id){const{data:r,error:e}=await a.from(table).select("*").eq("tenant_id",x.tenantId).eq("id",id).limit(2);if(e||(r??[]).length!==1)throw new Error("crm_cross_tenant_reference");const{data,error}=await a.from(table).update({...payload,row_version:Number(r[0].row_version??0)+1,updated_at:new Date().toISOString()}).eq("tenant_id",x.tenantId).eq("id",id).select().single();if(error)throw safeTenantCrmError(error);return data}const{data,error}=await a.from(table).insert({tenant_id:x.tenantId,created_by:x.actorUserId,...payload}).select().single();if(error)throw safeTenantCrmError(error);return data}
export const getTenantCrmFunctionalRegistry=createServerFn({method:"GET"}).middleware([requireTenant]).handler(async({context})=>{await auth(context,"lead.read");return{...CRM_FUNCTIONAL_CONTRACT,capabilities:[...CRM_FUNCTIONAL_CAPABILITIES],communicationAdapterStates:[...CRM_COMMUNICATION_ADAPTER_STATE],alertKeys:[...CRM_ALERT_KEYS]}});
export const listTenantCrmContacts=createServerFn({method:"GET"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({leadId:uuid.optional(),limit:z.number().optional()}).optional().parse(v)).handler(({context,data})=>list(context,"lead.list","crm_contacts",{lead_id:data?.leadId}));
export const saveTenantCrmContact=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.contact.parse(v)).handler(({context,data})=>save(context,data.id?"lead.update":"lead.create","crm_contacts",data.id,{lead_id:data.leadId??null,name:data.name,email:data.email??null,phone:data.phone??null}));
export const consumeTenantCrmAttachmentUploadTarget=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.attachment.parse(v)).handler(async({context,data})=>{const x=await auth(context,"lead.update"),a=await db();await scope(a,x,data.leadId);const{data:r,error}=await a.rpc("consume_tenant_crm_attachment_upload_target",{_actor_user_id:x.actorUserId,_tenant_id:x.tenantId,_tenant_origin:context.tenant.origin,_target_id:data.uploadTargetId,_lead_id:data.leadId,_display_name:data.displayName,_mime_type:data.mimeType??null,_size:data.size});if(error)throw safeTenantCrmError(error);return r});
export const listTenantCrmAttachments=createServerFn({method:"GET"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({leadId:uuid}).strict().parse(v)).handler(async({context,data})=>{const x=await auth(context,"lead.read"),a=await db();await scope(a,x,data.leadId);const{data:r,error}=await a.from("crm_attachments").select("id,lead_id,display_name,mime_type,size,created_at,created_by").eq("tenant_id",x.tenantId).eq("lead_id",data.leadId).order("created_at",{ascending:false});if(error)throw safeTenantCrmError(error);return r??[]});
export const getTenantCrmAttachmentDownloadUrl=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({attachmentId:uuid}).strict().parse(v)).handler(async({context,data})=>{const x=await auth(context,"lead.read"),a=await db();const{data:r,error}=await a.from("crm_attachments").select("id,lead_id,bucket,path").eq("tenant_id",x.tenantId).eq("id",data.attachmentId).limit(2);if(error||(r??[]).length!==1)throw new Error("crm_attachment_not_found");await scope(a,x,r[0].lead_id);const p=validateTenantSignRequest({bucket:r[0].bucket,path:r[0].path,tenantId:x.tenantId});const{data:s,error:e}=await a.storage.from(p.bucket).createSignedUrl(p.path,SIGNED_URL_TTL_DOWNLOAD_SECONDS);if(e||!s?.signedUrl)throw new Error("crm_attachment_sign_failed");return{attachmentId:data.attachmentId,url:s.signedUrl}});
export const deleteTenantCrmAttachment=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({attachmentId:uuid}).strict().parse(v)).handler(async({context,data})=>{const x=await auth(context,"lead.update"),a=await db();const{data:r,error}=await a.rpc("delete_tenant_crm_attachment",{_actor_user_id:x.actorUserId,_tenant_id:x.tenantId,_tenant_origin:context.tenant.origin,_attachment_id:data.attachmentId});if(error)throw safeTenantCrmError(error);const p=validateTenantSignRequest({bucket:r.bucket,path:r.path,tenantId:x.tenantId});const{error:e}=await a.storage.from(p.bucket).remove([p.path]);if(e)throw new Error("crm_attachment_storage_cleanup_failed");return{id:r.id,leadId:r.leadId,deleted:true}});
export const listTenantCrmCalendarEvents=createServerFn({method:"GET"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({leadId:uuid.optional()}).optional().passthrough().parse(v)).handler(({context,data})=>list(context,"task.list","crm_calendar_events",{lead_id:data?.leadId}));
export const saveTenantCrmCalendarEvent=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.calendarEvent.parse(v)).handler(({context,data})=>save(context,"task.create","crm_calendar_events",data.id,{lead_id:data.leadId??null,contact_id:data.contactId??null,event_type:data.eventType,title:data.title,starts_at:data.startsAt,ends_at:data.endsAt??null,timezone:data.timezone,notes:data.notes??null,assigned_user_id:data.assignedUserId??null}));
export const listTenantCrmVisits=createServerFn({method:"GET"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({leadId:uuid.optional(),propertyId:uuid.optional()}).optional().parse(v)).handler(({context,data})=>list(context,"task.list","crm_visits",{lead_id:data?.leadId,property_id:data?.propertyId}));
export const saveTenantCrmVisit=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.visit.parse(v)).handler(({context,data})=>save(context,"task.create","crm_visits",data.id,{lead_id:data.leadId,property_id:data.propertyId,calendar_event_id:data.calendarEventId??null,scheduled_at:data.scheduledAt,status:data.status,feedback:data.feedback??null}));
export const listTenantCrmProposals=createServerFn({method:"GET"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({leadId:uuid.optional(),propertyId:uuid.optional()}).optional().parse(v)).handler(({context,data})=>list(context,"lead.read","crm_proposals",{lead_id:data?.leadId,property_id:data?.propertyId}));
export const saveTenantCrmProposal=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.proposal.parse(v)).handler(({context,data})=>save(context,"lead.update","crm_proposals",data.id,{lead_id:data.leadId,property_id:data.propertyId,amount:data.amount,status:data.status,valid_until:data.validUntil??null,terms:data.terms}));
export const listTenantCrmAutomationRules=createServerFn({method:"GET"}).middleware([requireTenant]).handler(({context})=>list(context,"lead.list","crm_automation_rules"));
export const saveTenantCrmAutomationRule=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.automationRule.parse(v)).handler(({context,data})=>save(context,"lead.update","crm_automation_rules",data.id,{rule_key:data.ruleKey,configuration:data.configuration,active:data.active}));
export const enqueueTenantCrmCommunicationJob=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.communicationJob.parse(v)).handler(({context,data})=>save(context,"lead.update","crm_communication_jobs",undefined,{lead_id:data.leadId,channel:data.channel,template_key:data.templateKey,idempotency_key:data.idempotencyKey,payload:data.payload,state:"adapter_not_implemented"}));
export const listTenantCrmSlaPolicies=createServerFn({method:"GET"}).middleware([requireTenant]).handler(({context})=>list(context,"lead.list","crm_sla_policies"));
export const saveTenantCrmSlaPolicy=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.slaPolicy.parse(v)).handler(({context,data})=>save(context,"lead.update","crm_sla_policies",data.id,{policy_key:data.policyKey,threshold_minutes:data.thresholdMinutes,active:data.active}));
export const listTenantCrmAlerts=createServerFn({method:"GET"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({state:z.string().optional(),leadId:uuid.optional()}).optional().parse(v)).handler(({context,data})=>list(context,"lead.list","crm_alerts",{state:data?.state,lead_id:data?.leadId}));
export const resolveTenantCrmAlert=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({id:uuid,state:z.string(),note:z.string().optional().nullable()}).parse(v)).handler(({context,data})=>save(context,"lead.update","crm_alerts",data.id,{state:data.state,resolution_note:data.note??null}));
export const importTenantCrmContacts=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>CRM_FUNCTIONAL_INPUT_SCHEMAS.importRows.parse(v)).handler(async({context,data})=>{const x=await auth(context,"lead.create"),a=await db(),out=[];for(const r of data.rows){const{data:q,error}=await a.from("crm_contacts").insert({tenant_id:x.tenantId,created_by:x.actorUserId,name:r.name,email:r.email??null,phone:r.phone??null}).select("id").single();out.push(error?{state:"invalid",error:error.message}:{state:"created",contactId:q.id})}return{total:data.rows.length,outcomes:out}});
export const exportTenantCrmData=createServerFn({method:"POST"}).middleware([requireTenant]).inputValidator((v:any)=>z.object({format:z.enum(["CSV","JSON"]),resource:z.enum(["contacts","calendar","visits","proposals","alerts"])}).parse(v)).handler(async({context,data})=>{const table:any={contacts:"crm_contacts",calendar:"crm_calendar_events",visits:"crm_visits",proposals:"crm_proposals",alerts:"crm_alerts"};const rows=await list(context,"lead.list",table[data.resource]);const content=data.format==="JSON"?JSON.stringify(rows,null,2):JSON.stringify(rows);return{format:data.format,resource:data.resource,rows:rows.length,bytes:new TextEncoder().encode(content).length,sha256:"runtime-generated",content,externalProviderExecuted:false}});
