import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
assert.equal(process.env.ROUND52_ISOLATED_CI,'true');
const pg=await import(pathToFileURL(process.env.ROUND52_PG_MODULE));const {Client}=pg.default??pg;
const config={host:'127.0.0.1',port:55452,user:'postgres'};
const root=new Client({...config,database:'postgres'});await root.connect();await root.query('CREATE DATABASE tenant_user_admin');await root.end();
const db=new Client({...config,database:'tenant_user_admin'});await db.connect();
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
try {
 await db.query(`CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid primary key,email_confirmed_at timestamptz);
 CREATE TYPE tenant_role AS ENUM('owner','admin','gerente','secretaria','corretor','viewer');
 CREATE TYPE membership_status AS ENUM('active','invited','suspended','revoked');
 CREATE TYPE rbac_action AS ENUM('visualizar','criar','editar','excluir','publicar','exportar','importar','aprovar','gerenciar');
 CREATE TYPE rbac_scope AS ENUM('proprio','equipe','global');
 CREATE TABLE tenants(id uuid primary key);
 CREATE TABLE user_roles(user_id uuid,role text);
 CREATE TABLE tenant_members(tenant_id uuid,user_id uuid,tenant_role tenant_role,membership_status membership_status,is_owner boolean,is_default boolean default false,joined_at timestamptz,invited_at timestamptz,accepted_at timestamptz,updated_at timestamptz,suspended_at timestamptz,revoked_at timestamptz,primary key(tenant_id,user_id));
 CREATE TABLE rbac_profiles(id uuid primary key default gen_random_uuid(),tenant_id uuid,nome text,descricao text,codigo text,sistema boolean,updated_at timestamptz);
 CREATE TABLE rbac_modules(id uuid primary key,codigo text);
 CREATE TABLE rbac_permissions(profile_id uuid,module_id uuid,action rbac_action,scope rbac_scope,primary key(profile_id,module_id,action));
 CREATE TABLE user_profiles(tenant_id uuid,user_id uuid,profile_id uuid);
 CREATE TABLE team_members(tenant_id uuid,user_id uuid,team_id uuid);
 CREATE TABLE audit_log(tenant_id uuid,user_id uuid,action text,entity text,entity_id text,before jsonb,after jsonb);
 CREATE FUNCTION resolve_tenant_permission(uuid,uuid,text,text,text) RETURNS jsonb LANGUAGE sql AS $$ SELECT '{"allowed":false,"scope":null}'::jsonb $$;
 -- Seat-provider dependency is controlled; real seat logic is unchanged by this migration.
 CREATE FUNCTION resolve_commercial_seat_decision(uuid,uuid,text,int) RETURNS jsonb LANGUAGE sql AS $$ SELECT jsonb_build_object('allowed',coalesce(current_setting('fixture.seats',true),'allow')<>'deny') $$;
 ALTER TABLE tenant_members ENABLE ROW LEVEL SECURITY; ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
 CREATE POLICY fixture_tenant ON tenant_members FOR SELECT TO authenticated USING(tenant_id=current_setting('fixture.tenant')::uuid);
 CREATE POLICY fixture_tenant ON user_profiles FOR SELECT TO authenticated USING(tenant_id=current_setting('fixture.tenant')::uuid);
 CREATE POLICY fixture_tenant ON team_members FOR SELECT TO authenticated USING(tenant_id=current_setting('fixture.tenant')::uuid);
 GRANT USAGE ON SCHEMA auth TO service_role; GRANT ALL ON ALL TABLES IN SCHEMA public,auth TO service_role;
 GRANT SELECT ON tenant_members,user_profiles,team_members TO authenticated;`);
 const access=readFileSync('supabase/migrations/20260728180000_pr_m2_tenant_access_control.sql','utf8');
 for(const name of ['mutate_tenant_access_profile','set_tenant_profile_permission']) {
   const start=access.indexOf('CREATE OR REPLACE FUNCTION public.'+name+'('),end=access.indexOf('$fn$;',start)+5;
   await db.query(access.slice(start,end));
 }
 await db.query(readFileSync('supabase/migrations/20260913170940_tenant_user_administration.sql','utf8'));
 for(let n=1;n<=9;n++)await db.query('INSERT INTO auth.users VALUES($1,now())',[id(n)]);
 await db.query('INSERT INTO tenants VALUES($1),($2)',[id(20),id(21)]);
 for(const [u,t,role,status,owner] of [[1,20,'owner','active',true],[2,20,'admin','active',false],[3,20,'viewer','active',false],[4,20,'admin','suspended',false],[5,21,'admin','active',false]])await db.query('INSERT INTO tenant_members(tenant_id,user_id,tenant_role,membership_status,is_owner) VALUES($1,$2,$3,$4,$5)',[id(t),id(u),role,status,owner]);
 await db.query("INSERT INTO user_roles VALUES($1,'super_admin')",[id(1)]);
 await db.query("INSERT INTO rbac_profiles(id,tenant_id,nome,sistema) VALUES($1,NULL,'Captador',true),($2,$3,'Outro tenant',false)",[id(30),id(31),id(21)]);
 await db.query("INSERT INTO rbac_modules VALUES($1,'leads')",[id(40)]);
 await db.query("INSERT INTO rbac_permissions VALUES($1,$2,'visualizar','global')",[id(30),id(40)]);
 const customize=(actor=2,tenant=20,source=30,origin='selection')=>db.query('SELECT customize_tenant_access_profile($1,$2,$3,$4) result',[id(actor),id(tenant),origin,id(source)]);
 await db.query('SET ROLE service_role');
 for(const actor of [1,3,4,5])await assert.rejects(customize(actor));
 await assert.rejects(customize(1,20,30,'impersonation'));
 await assert.rejects(customize(2,20,31));
 const copy=(await customize()).rows[0].result.profileId;assert.equal((await customize()).rows[0].result.profileId,copy);
 await db.query("SELECT set_tenant_profile_permission($1,$2,'selection',$3,$4,'visualizar','proprio',true)",[id(2),id(20),copy,id(40)]);
 assert.equal((await db.query('SELECT scope FROM rbac_permissions WHERE profile_id=$1',[id(30)])).rows[0].scope,'global');
 await assert.rejects(db.query("SELECT set_tenant_profile_permission($1,$2,'selection',$3,$4,'visualizar','proprio',true)",[id(2),id(20),id(30),id(40)]));
 const configure=(actor=2,target=6,profiles=[copy],resend=false,tenant=20)=>db.query("SELECT configure_tenant_member_registration($1,$2,'selection',$3,'viewer','Pessoa de teste',$4,$5) result",[id(actor),id(tenant),id(target),profiles,resend]);
 for(const actor of [1,3,4,5])await assert.rejects(configure(actor));
 await assert.rejects(configure(2,1));await assert.rejects(configure(2,6,[id(31)]));
 await db.query("SET fixture.seats='deny'");await assert.rejects(configure(),/commercial_seat_limit_denied/);await db.query("SET fixture.seats='allow'");
 assert.equal((await db.query('SELECT count(*) FROM tenant_members WHERE user_id=$1',[id(6)])).rows[0].count,'0');
 await configure();
 const row=(await db.query('SELECT * FROM tenant_members WHERE user_id=$1',[id(6)])).rows[0];assert.equal(row.membership_status,'invited');assert.equal(row.display_name,'Pessoa de teste');assert.equal(row.activation_delivery_status,'pending');
 assert.equal((await db.query('SELECT profile_id FROM user_profiles WHERE user_id=$1',[id(6)])).rows[0].profile_id,copy);
 await assert.rejects(configure(2,6,[copy],true),/registration_retry_later/);
 await db.query('RESET ROLE');
 // An audit failure rolls back the membership and configured profiles together.
 await db.query("CREATE FUNCTION fail_registration_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.action='tenant_user.registration.configure' THEN RAISE EXCEPTION 'fixture_audit_failure'; END IF; RETURN NEW; END$$; CREATE TRIGGER fail_registration_audit BEFORE INSERT ON audit_log FOR EACH ROW EXECUTE FUNCTION fail_registration_audit()");
 await assert.rejects(configure(2,7),/fixture_audit_failure/);
 assert.equal((await db.query('SELECT count(*) FROM tenant_members WHERE user_id=$1',[id(7)])).rows[0].count,'0');
 await db.query('DROP TRIGGER fail_registration_audit ON audit_log');
 await db.query('UPDATE auth.users SET email_confirmed_at=NULL WHERE id=$1',[id(6)]);
 await assert.rejects(db.query('SELECT accept_tenant_invitation($1,$2)',[id(6),id(20)]),/verified_operational_identity_required/);
 await db.query('UPDATE auth.users SET email_confirmed_at=now() WHERE id=$1',[id(6)]);
 await db.query('SELECT accept_tenant_invitation($1,$2)',[id(6),id(20)]);
 await db.query('INSERT INTO user_profiles VALUES($1,$2,$3);',[id(20),id(1),id(30)]);
 await db.query('SELECT set_config(\'fixture.tenant\',$1,false)',[id(20)]);await db.query('SET ROLE authenticated');
 assert.ok(!(await db.query('SELECT user_id FROM tenant_members')).rows.some(x=>x.user_id===id(1)||x.user_id===id(5)));
 assert.ok(!(await db.query('SELECT user_id FROM user_profiles')).rows.some(x=>x.user_id===id(1)));
 await assert.rejects(customize(),/permission denied/);
 await db.query('RESET ROLE; SET ROLE anon');await assert.rejects(configure(),/permission denied/);
 await db.query('RESET ROLE');assert.equal((await db.query('SELECT is_owner FROM tenant_members WHERE user_id=$1',[id(1)])).rows[0].is_owner,true);
 console.log('PASS native tenant user administration: operational Admin, foreign/suspended/viewer/Super denial, immutable and idempotent profile customization, pending configuration atomicity, seat denial, cooldown, verified acceptance, restrictive directory RLS and service-only RPC grants.');
} finally {await db.end();}
