import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createJourneyCommandRunner, journeyError } from './src/components/pipeline/crm-journey-command';
import { leadTaskIntentSchema, taskTransitionIntentSchema, leadAssignmentIntentSchema, leadTransitionIntentSchema } from './src/lib/crm/crm-registry';

async function main() {
  let serial = 0;
  const run = createJourneyCommandRunner(() => `request-${++serial}`);
  const keys: string[] = [];
  let committed = false;
  const payload = { nome: 'Contato de teste' };
  await assert.rejects(run('create', payload, async key => { keys.push(key); committed = true; throw Error('response_lost'); }));
  const leadId = await run('create', payload, async key => { keys.push(key); assert.ok(committed); return '00000000-0000-4000-8000-000000000001'; });
  assert.equal(keys[0], keys[1], 'lost response retries reuse identity');
  await run('create', payload, async key => { assert.notEqual(key, keys[0]); });
  let finish!: () => void;
  const pending = run('slow', {}, () => new Promise<void>(resolve => { finish = resolve; }));
  await assert.rejects(run('second', {}, async () => {}), /journey_busy/);
  finish(); await pending;
  let version = 2;
  const actor = '00000000-0000-4000-8000-000000000002';
  const assign = leadAssignmentIntentSchema.parse({ leadId, expectedVersion: version, strategy: 'manual_member', assigneeUserId: actor, reason: 'Atendimento manual', idempotencyKey: 'request-assign' });
  assert.equal(assign.expectedVersion, 2);
  version++;
  const task = leadTaskIntentSchema.parse({ leadId, type: 'follow_up', title: 'Retorno', assigneeUserId: actor, idempotencyKey: 'request-task' });
  assert.equal(task.assigneeUserId, actor);
  const complete = taskTransitionIntentSchema.parse({ taskId: actor, expectedVersion: 4, toStatus: 'completed', idempotencyKey: 'request-complete' });
  assert.equal(complete.expectedVersion, 4);
  const advance = leadTransitionIntentSchema.parse({ leadId, expectedVersion: version, toStatus: 'conversando', idempotencyKey: 'request-advance' });
  assert.equal(advance.expectedVersion, 3);
  assert.throws(() => leadTransitionIntentSchema.parse({ ...advance, tenantId: actor }));
  assert.throws(() => leadAssignmentIntentSchema.parse({ ...assign, assigneeUserId: null }));
  assert.match(journeyError(Error('tenant_crm_permission_denied')), /Acesso negado/);
  assert.match(journeyError(Error('version_conflict')), /registro mudou/);
  assert.match(journeyError(Error('tenant_unresolved')), /indisponível/);
  assert.match(journeyError(Error('invalid_transition')), /recusada/);
  assert.ok(!journeyError(Error('secret internal details')).includes('secret'));
  const read = (p: string) => readFileSync(p, 'utf8');
  const panel = read('src/components/pipeline/CrmJourneyPanel.tsx');
  const route = read('src/routes/_authenticated.admin.pipeline.tsx');
  assert.ok(route.includes('<CrmJourneyPanel') && route.includes('<PipelineReadOnlyPage'));
  assert.ok(!panel.includes('PipelinePage') && !panel.includes('CrmOperationsPanel'));
  assert.ok(panel.includes('expectedVersion: lead.version') && panel.includes('expectedVersion: task.row_version'));
  assert.ok(panel.includes('qc.invalidateQueries') && panel.includes('aggregate.data?.activities'));
  assert.ok(panel.includes('key={`${scopeKey}:${selectedId') && panel.includes("['crm-journey', tenantId"));
  assert.ok(!panel.includes('localStorage') && !panel.includes('supabaseAdmin') && !panel.includes('.rpc('));
  assert.ok(!read('src/components/pipeline/PipelineReadOnlyPage.tsx').includes('useMutation'));
  console.log('Round 35: retry, concurrency, canonical payloads, error states and read-only composition passed. Controlled responses only; no persistent runtime claim.');
}
main().catch(e => { console.error(e); process.exitCode = 1; });
