// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_04_03 = `is-a-nascarfan.com
is-a-nurse.com
is-a-painter.com
is-a-patsfan.org
is-a-personaltrainer.com
is-a-photographer.com
is-a-player.com
is-a-republican.com
is-a-rockstar.com
is-a-socialist.com
is-a-soxfan.org
is-a-student.com
is-a-teacher.com
is-a-techie.com
is-a-therapist.com
is-a.dev
is-an-accountant.com
is-an-actor.com
is-an-actress.com
is-an-anarchist.com
is-an-artist.com
is-an-engineer.com
is-an-entertainer.com
is-by.us
is-certified.com
is-cool.dev
is-found.org
is-gone.com
is-into-anime.com
is-into-cars.com
is-into-cartoons.com
is-into-games.com
is-leet.com
is-local.org
is-lost.org
is-not-a.dev
is-not-certified.com
is-saved.org
is-slick.com
is-uberleet.com
is-very-bad.org
is-very-evil.org
is-very-good.org
is-very-nice.org
is-very-sweet.org
is-with-theband.com
is.eu.org
is.gov.pl
is.it
isa-geek.com
isa-geek.net
isa-geek.org
isa-hockeynut.com
isa.kagoshima.jp
isa.us
isahaya.nagasaki.jp
ise.mie.jp
isehara.kanagawa.jp
isen.kagoshima.jp
isernia.it
iserv.dev
iserv.host
iservschule.de
isesaki.gunma.jp
ishigaki.okinawa.jp
ishikari.hokkaido.jp
ishikawa.fukushima.jp
ishikawa.jp
ishikawa.okinawa.jp
ishinomaki.miyagi.jp
isla.pr
ismaili
ispmanager.name
isshiki.aichi.jp
issmarterthanyou.com
ist
istanbul
isteingeek.de
istmein.de
isumi.chiba.jp
it
it.ao
it.bd
it.com
it.eu.org
it.kr
it1.eur.aruba.jenv-aruba.cloud
it1.jenv-aruba.cloud
itabashi.tokyo.jp
itako.ibaraki.jp
itakura.gunma.jp
itami.hyogo.jp
itano.tokushima.jp
itau
itayanagi.aomori.jp
itcouldbewor.se
itigo.jp
ito.shizuoka.jp
itoigawa.niigata.jp
itoman.okinawa.jp
its.me
itv
ivano-frankivsk.ua
ivanovo.su
iveland.no
ivgu.no
ivory.ne.jp
iwade.wakayama.jp
iwafune.tochigi.jp
iwaizumi.iwate.jp
iwaki.fukushima.jp
iwakuni.yamaguchi.jp
iwakura.aichi.jp
iwama.ibaraki.jp
iwamizawa.hokkaido.jp
iwanai.hokkaido.jp
iwanuma.miyagi.jp
iwata.shizuoka.jp
iwate.iwate.jp
iwate.jp
iwatsuki.saitama.jp
iwi.nz
iyo.ehime.jp
iz.hr
izena.okinawa.jp
izu.shizuoka.jp
izumi.kagoshima.jp
izumi.osaka.jp
izumiotsu.osaka.jp
izumisano.osaka.jp
izumizaki.fukushima.jp
izumo.shimane.jp
izumozaki.niigata.jp
izunokuni.shizuoka.jp
j.bg
j.layershift.co.uk
j.scaleforce.com.cy
j.scaleforce.net
jab.br
jaguar
jambyl.su
jampa.br
jan-mayen.no
janeway.replit.dev
java
jaworzno.pl
jc.neen.it
jcb
jcloud-ver-jpc.ik-server.com
jcloud.ik-server.com
jcloud.kz
jdevcloud.com
jdf.br
je
jed.wafaicloud.com
jeep
jeez.jp
jeju.kr
jelastic.dogado.eu
jelastic.saveincloud.net`.split("\n").filter(Boolean);
