// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_01 = `!city.kawasaki.jp
!city.kitakyushu.jp
!city.kobe.jp
!city.nagoya.jp
!city.sapporo.jp
!city.sendai.jp
!city.yokohama.jp
!www.ck
*.001.test.code-builder-stg.platform.salesforce.com
*.0e.vc
*.0emm.com
*.aa.crm.dev
*.ab.crm.dev
*.ac.crm.dev
*.ad.crm.dev
*.advisor.ws
*.ae.crm.dev
*.af-south-1.airflow.amazonaws.com
*.af-south-1.rds.amazonaws.com
*.af.crm.dev
*.airflow.af-south-1.on.aws
*.airflow.ap-east-1.on.aws
*.airflow.ap-northeast-1.on.aws
*.airflow.ap-northeast-2.on.aws
*.airflow.ap-northeast-3.on.aws
*.airflow.ap-south-1.on.aws
*.airflow.ap-south-2.on.aws
*.airflow.ap-southeast-1.on.aws
*.airflow.ap-southeast-2.on.aws
*.airflow.ap-southeast-3.on.aws
*.airflow.ap-southeast-4.on.aws
*.airflow.ap-southeast-5.on.aws
*.airflow.ca-central-1.on.aws
*.airflow.ca-west-1.on.aws
*.airflow.cn-north-1.on.amazonwebservices.com.cn
*.airflow.cn-northwest-1.on.amazonwebservices.com.cn
*.airflow.eu-central-1.on.aws
*.airflow.eu-central-2.on.aws
*.airflow.eu-north-1.on.aws
*.airflow.eu-south-1.on.aws
*.airflow.eu-south-2.on.aws
*.airflow.eu-west-1.on.aws
*.airflow.eu-west-2.on.aws
*.airflow.eu-west-3.on.aws
*.airflow.il-central-1.on.aws
*.airflow.me-central-1.on.aws
*.airflow.me-south-1.on.aws
*.airflow.sa-east-1.on.aws
*.airflow.us-east-1.on.aws
*.airflow.us-east-2.on.aws
*.airflow.us-west-1.on.aws
*.airflow.us-west-2.on.aws
*.alces.network
*.ap-east-1.airflow.amazonaws.com
*.ap-east-1.rds.amazonaws.com
*.ap-east-2.rds.amazonaws.com
*.ap-north-1.r.cloud.int.apple
*.ap-northeast-1.airflow.amazonaws.com
*.ap-northeast-1.rds.amazonaws.com
*.ap-northeast-2.airflow.amazonaws.com
*.ap-northeast-2.rds.amazonaws.com
*.ap-northeast-3.airflow.amazonaws.com
*.ap-northeast-3.rds.amazonaws.com
*.ap-south-1.airflow.amazonaws.com
*.ap-south-1.r.cloud.int.apple
*.ap-south-1.rds.amazonaws.com
*.ap-south-2.airflow.amazonaws.com
*.ap-south-2.r.cloud.int.apple
*.ap-south-2.rds.amazonaws.com
*.ap-southeast-1.airflow.amazonaws.com
*.ap-southeast-1.rds.amazonaws.com
*.ap-southeast-2.airflow.amazonaws.com
*.ap-southeast-2.rds.amazonaws.com
*.ap-southeast-3.airflow.amazonaws.com
*.ap-southeast-3.rds.amazonaws.com
*.ap-southeast-4.airflow.amazonaws.com
*.ap-southeast-4.rds.amazonaws.com
*.ap-southeast-5.airflow.amazonaws.com
*.ap-southeast-5.rds.amazonaws.com
*.ap-southeast-6.rds.amazonaws.com
*.ap-southeast-7.airflow.amazonaws.com
*.ap-southeast-7.rds.amazonaws.com
*.appwrite.run
*.at.playit.plus
*.at.ply.gg
*.atlassian-3p-us-gov-mod.com
*.atlassian-3p.com
*.atlassian-isolated-3p.com
*.auiusercontent.com
*.awdev.ca
*.awsapprunner.com
*.azurecontainer.io
*.beget.app
*.begetcdn.cloud
*.build.run
*.builder.code.com
*.bwcloud-os-instance.de
*.c.ts.net
*.ca-central-1.airflow.amazonaws.com
*.ca-central-1.rds.amazonaws.com
*.ca-west-1.airflow.amazonaws.com
*.ca-west-1.rds.amazonaws.com
*.ci.crm.dev
*.ck
*.cloud.int.apple
*.cloud.metacentrum.cz
*.cloudera.site
*.clusters.rdpa.co
*.cn-north-1.airflow.amazonaws.com.cn
*.cn-northwest-1.airflow.amazonaws.com.cn
*.cn.st
*.code.run
*.compute-1.amazonaws.com
*.compute.amazonaws.com
*.compute.amazonaws.com.cn
*.compute.estate
*.customer-oci.com
*.d.crm.dev
*.database.run
*.dev-builder.code.com
*.dev.adobeaemcloud.com
*.developer.app
*.devinapps.com
*.digitaloceanspaces.com
*.dweb.link
*.elb.amazonaws.com
*.elb.amazonaws.com.cn
*.er
*.eu-central-1.airflow.amazonaws.com
*.eu-central-1.r.cloud.int.apple
*.eu-central-1.rds.amazonaws.com
*.eu-central-2.airflow.amazonaws.com
*.eu-central-2.rds.amazonaws.com
*.eu-north-1.airflow.amazonaws.com
*.eu-north-1.r.cloud.int.apple
*.eu-south-1.airflow.amazonaws.com
*.eu-south-2.airflow.amazonaws.com
*.eu-west-1.airflow.amazonaws.com
*.eu-west-1.rds.amazonaws.com
*.eu-west-2.airflow.amazonaws.com
*.eu-west-2.rds.amazonaws.com
*.eu-west-3.airflow.amazonaws.com
*.eu-west-3.rds.amazonaws.com
*.ewp.live
*.ex.futurecms.at
*.ex.ortsinfo.at
*.experiments.sagemaker.aws
*.firenet.ch
*.fk
*.frusky.de
*.futurecms.at
*.gateway.dev
*.hosted.app
*.hosting.myjino.ru
*.hosting.ovh.net
*.icp.net
*.id.pub
*.il-central-1.airflow.amazonaws.com
*.il-central-1.rds.amazonaws.com
*.in.futurecms.at
*.inbrowser.dev
*.inbrowser.link
*.jm
*.kawasaki.jp
*.kin.one
*.kin.pub
*.kitakyushu.jp
*.kobe.jp
*.kunden.ortsinfo.at
*.landing.myjino.ru
*.lcl.dev
*.lclstage.dev
*.linodeobjects.com
*.localto.net
*.lutrausercontent.com
*.magentosite.cloud
*.me-central-1.airflow.amazonaws.com
*.me-central-1.rds.amazonaws.com
*.me-south-1.airflow.amazonaws.com
*.me-south-1.rds.amazonaws.com
*.metaaiusercontent.com
*.migration.run
*.mm
*.moonscale.io
*.mtls.run.app
*.mx-central-1.rds.amazonaws.com
*.nagoya.jp
*.nodebalancer.linode.com
*.nom.br
*.northflank.app
*.np
*.nxa.eu
*.oaiusercontent.com
*.oci.customer-oci.com
*.ocp.customer-oci.com
*.ocs.customer-oci.com
*.on-k3s.io
*.on-rancher.cloud
*.on-rio.io
*.oraclecloudapps.com
*.oraclegovcloudapps.com
*.oraclegovcloudapps.uk
*.otap.co
*.owo.codes
*.pa.crm.dev
*.paywhirl.com
*.pb.crm.dev
*.pc.crm.dev
*.pd.crm.dev
*.pe.crm.dev
*.pf.crm.dev
*.pg
*.platformsh.site
*.private.repost.aws
*.privatelink.snowflake.app
*.qualyhqpartner.com
*.qualyhqportal.com
*.quipelements.com
*.r.appspot.com
*.r.cloud.int.apple
*.raw.icp0.io
*.raw.icp1.io
*.rds.cn-north-1.amazonaws.com.cn
*.rds.cn-northwest-1.amazonaws.com.cn
*.run.app
*.s.brave.app
*.s.brave.dev
*.s.brave.io
*.sa-east-1.airflow.amazonaws.com
*.sa-east-1.rds.amazonaws.com
*.sapporo.jp
*.sch.uk
*.sendai.jp
*.services.clever-cloud.com
*.snowflake.app
*.spectrum.myjino.ru
*.srvrless.rdpa.co
*.statics.cloud
*.stg-builder.code.com
*.stg.dev
*.stgstage.dev
*.stolos.io
*.svc.firenet.ch
*.sys.qcx.io
*.telebit.xyz
*.transurl.be
*.transurl.eu
*.transurl.nl
*.triton.zone
*.tst.site
*.upsun.app
*.us-central-1.r.cloud.int.apple
*.us-central-2.r.cloud.int.apple
*.us-east-1.airflow.amazonaws.com
*.us-east-1.r.cloud.int.apple
*.us-east-1.rds.amazonaws.com
*.us-east-2.airflow.amazonaws.com
*.us-east-2.r.cloud.int.apple
*.us-east-2.rds.amazonaws.com
*.us-gov-east-1.rds.amazonaws.com
*.us-gov-west-1.rds.amazonaws.com
*.us-northeast-1.rds.amazonaws.com
*.us-west-1.airflow.amazonaws.com
*.us-west-1.r.cloud.int.apple
*.us-west-1.rds.amazonaws.com
*.us-west-2.airflow.amazonaws.com
*.us-west-2.r.cloud.int.apple
*.us-west-2.rds.amazonaws.com
*.us-west-3.r.cloud.int.apple
*.user.fm
*.user.localcert.dev
*.usercontent.goog
*.vps.myjino.ru
*.vultrobjects.com
*.w.crm.dev
*.wa.crm.dev
*.wadl.top
*.wb.crm.dev
*.wc.crm.dev
*.wd.crm.dev
*.we.crm.dev
*.webhare.dev
*.webpaas.ovh.net
*.wf.crm.dev
*.xenonconnect.de
*.xmit.co
*.yokohama.jp
*.zerops.app
*.zerops.zone
0.bg
0am.jp
0g0.jp
0j0.jp
0t0.jp
1.azurestaticapps.net
1.bg
123hjemmeside.dk
123hjemmeside.no
123homepage.it
123kotisivu.fi
123minsida.se
123miweb.es
123paginaweb.pt
123siteweb.fr
123webseite.at
123webseite.de
123website.be
123website.ch
123website.lu
123website.nl
12hp.at
12hp.ch
12hp.de
1337.pictures
16-b.it
180r.com
1cooldns.com
1kapp.com
2-d.jp
2.azurestaticapps.net
2.bg
2000.hu
2038.io
2ix.at
2ix.ch
2ix.de
3.azurestaticapps.net
3.bg
32-b.it
3utilities.com
4.at
4.azurestaticapps.net
4.bg
4lima.at
4lima.ch
4lima.de
4u.com
5.azurestaticapps.net
5.bg
5g.in
6.azurestaticapps.net
6.bg
611.to
64-b.it
6g.in
7.azurestaticapps.net
7.bg
8.bg
9.bg
9guacu.br
a.bg
a.prod.fastly.net
a.se
a.ssl.fastly.net
a2hosted.com
aa.no
aaa
aaa.pro
aarborte.no
aarp
ab.ca
abashiri.hokkaido.jp
abb
abbott
abbvie
abc
abc.br
abeno.osaka.jp
aberdeen.wa.us
abg.ec
abiko.chiba.jp
abira.hokkaido.jp
abkhazia.su
able
abo.pa
abogado
abr.it
abrdns.com
abruzzo.it
abu.yamaguchi.jp
abudhabi
ac
ac.ae
ac.at
ac.bd
ac.be
ac.bw
ac.ci
ac.cn
ac.cr
ac.cy
ac.eg
ac.fj
ac.gn
ac.gov.br
ac.id
ac.il
ac.im
ac.in
ac.ir
ac.jp
ac.ke
ac.kr
ac.leg.br
ac.lk
ac.ls
ac.ma
ac.me
ac.ml
ac.mu
ac.mw
ac.mz
ac.ni
ac.nz
ac.pa
ac.pk
ac.pr
ac.rs
ac.ru
ac.rw
ac.se
ac.sz
ac.th
ac.tz
ac.ug
ac.uk
ac.vn
ac.za
ac.zm
ac.zw
aca.pro
academia.bo
academy
accenture
accesscam.org
accident-investigation.aero
accident-prevention.aero
accountant
accountants
acct.pro
achi.nagano.jp
aco
act.au
act.edu.au
activetrail.biz
actor
ad
ad.jp
adachi.tokyo.jp
adaptable.app
adimo.co.uk
adm.br
adm.ec
adobeaemcloud.com
adobeaemcloud.net
adobeio-static.net
adobeioruntime.net
ads
adult
adult.ht
adv.br
adv.mz
adygeya.ru
adygeya.su
ae
ae.kg
ae.org
aeg
aejrie.no
aem.live
aem.network
aem.page
aem.reviews
aero
aero.in
aero.mv
aerobatic.aero
aeroclub.aero
aerodrome.aero
aeroport.fr
aetna
af
af-south-1.elasticbeanstalk.com
affinitylottery.org.uk
afjord.no
afl
africa
africa.bj
africa.com
ag
ag.it
aga.niigata.jp
agakhan
agano.niigata.jp
agdenes.no
agematsu.nagano.jp
agency
agents.aero
agr.br
agrar.hu
agri.jo
agric.za
agrigento.it
agro.bj
agro.bo
agro.pl
agron.ec
aguni.okinawa.jp
ah.cn
ah.no
ai
ai.bd
ai.id
ai.in
ai.jo
ai.kr
ai.vn
aibetsu.hokkaido.jp
aichi.jp
aid.pl
aig
aikawa.kanagawa.jp
ainan.ehime.jp
aioi.hyogo.jp
aip.ee
air-surveillance.aero
air-traffic-control.aero
airbus
aircraft.aero
airforce
airline.aero
airport.aero
airtel
airtraffic.aero
aisai.aichi.jp
aisho.shiga.jp
aiven.app
aivencloud.com
aizubange.fukushima.jp
aizumi.tokushima.jp
aizumisato.fukushima.jp
aizuwakamatsu.fukushima.jp
aju.br
ak.us
akabira.hokkaido.jp
akadns.net
akagi.shimane.jp
akaiwa.okayama.jp
akamai-staging.net
akamai.net
akamaiedge-staging.net
akamaiedge.net
akamaihd-staging.net
akamaihd.net
akamaiorigin-staging.net
akamaiorigin.net
akamaized-staging.net
akamaized.net
akashi.hyogo.jp
akdn
aki.kochi.jp
akiruno.tokyo.jp
akishima.tokyo.jp
akita.akita.jp
akita.jp
akkeshi.hokkaido.jp
aknoluokta.no
ako.hyogo.jp
akrehamn.no
aktyubinsk.su
akune.kagoshima.jp
al
al.eu.org
al.gov.br
al.it
al.leg.br
al.no
al.us
alaheadju.no
aland.fi
alessandria.it
alesund.no
algard.no
aliases121.com
alibaba
alibabacloudcs.com
alipay
allfinanz
allstate
ally
alp1.ae.flow.ch
alpha-myqnapcloud.com
alsace
alstahaug.no
alstom
alt.na
alt.za
alta.no
altervista.org
alto-adige.it
altoadige.it
alumni.in
alvdal.no
alwaysdata.net
am
am.br
am.gov.br
am.in
am.leg.br
ama.aichi.jp
ama.shimane.jp
amagasaki.hyogo.jp
amakusa.kumamoto.jp
amami.kagoshima.jp
amazon
ambulance.aero
americanexpress
americanfamily
amex
amfam
ami.ibaraki.jp
amica
amli.no
amot.no
amplifyapp.com
amsterdam
an.it
analytics
analytics-gateway.ap-northeast-1.amazonaws.com
analytics-gateway.ap-northeast-2.amazonaws.com
analytics-gateway.ap-south-1.amazonaws.com
analytics-gateway.ap-southeast-1.amazonaws.com
analytics-gateway.ap-southeast-2.amazonaws.com
analytics-gateway.eu-central-1.amazonaws.com
analytics-gateway.eu-west-1.amazonaws.com
analytics-gateway.us-east-1.amazonaws.com
analytics-gateway.us-east-2.amazonaws.com
analytics-gateway.us-west-2.amazonaws.com
anamizu.ishikawa.jp
anan.nagano.jp
anan.tokushima.jp
anani.br
ancona.it
andasuolo.no
andebu.no
ando.nara.jp
andoy.no
andria-barletta-trani.it
andria-trani-barletta.it
andriabarlettatrani.it
andriatranibarletta.it
android
angiang.vn
angry.jp
anjo.aichi.jp
ann-arbor.mi.us
annaka.gunma.jp
anpachi.gifu.jp
anquan
antagonist.cloud
anz
ao
ao.it
aogaki.hyogo.jp
aogashima.tokyo.jp
aoki.nagano.jp
aol
aomori.aomori.jp
aomori.jp
aosta-valley.it
aosta.it
aostavalley.it
aoste.it
ap-east-1.elasticbeanstalk.com
ap-northeast-1.elasticbeanstalk.com
ap-northeast-2.elasticbeanstalk.com
ap-northeast-3.elasticbeanstalk.com
ap-south-1.elasticbeanstalk.com
ap-southeast-1.elasticbeanstalk.com
ap-southeast-2.elasticbeanstalk.com
ap-southeast-3.elasticbeanstalk.com
ap-southeast-5.elasticbeanstalk.com
ap-southeast-7.elasticbeanstalk.com
ap.gov.br
ap.gov.pl
ap.it
ap.leg.br
ap.ngrok.io
aparecida.br
apartments
api.br
api.gov.uk
api.lp.dev
apigee.io
app
app-ionos.space
app.br
app.os.fedoraproject.org
app.os.stg.fedoraproject.org
app.render.com
appchizi.com
appengine.flow.ch
apple
applinzi.com
apps-1and1.com
apps-1and1.net
apps.fbsbx.com
apps.lair.io
appspacehosted.com
appspaceusercontent.com
appspot.com
appudo.net
appwrite.global
appwrite.network
aq
aq.it
aquarelle
ar
ar.it
ar.us
arab
arai.shizuoka.jp
arakawa.saitama.jp
arakawa.tokyo.jp
aramco
arao.kumamoto.jp
archer.replit.dev
archi
architectes.bj
ardal.no
aremark.no
arendal.no
arezzo.it
ariake.saga.jp
arida.wakayama.jp
aridagawa.wakayama.jp
arita.saga.jp
arkhangelsk.su
armenia.su
army
arna.no
arpa
arq.br
arqt.ec
art
art.br
art.do
art.dz
art.ec
art.ht
art.ml
art.pl
art.sn
arte
arte.bo
arts.nf
arts.ro
arts.ve
arvanedge.ir
arvo.network
as
as.sh.cn
as.us
asago.hyogo.jp
asahi.chiba.jp
asahi.ibaraki.jp
asahi.mie.jp
asahi.nagano.jp
asahi.toyama.jp
asahi.yamagata.jp
asahikawa.hokkaido.jp
asaka.saitama.jp
asakawa.fukushima.jp
asakuchi.okayama.jp
asaminami.hiroshima.jp
ascoli-piceno.it
ascolipiceno.it
asda
aseral.no
ashgabad.su
ashibetsu.hokkaido.jp
ashikaga.tochigi.jp
ashiya.fukuoka.jp
ashiya.hyogo.jp
ashoro.hokkaido.jp
asia
asker.no
askim.no
askoy.no
askvoll.no
asn.au
asn.lv
asnes.no
aso.kumamoto.jp
ass.km
assabu.hokkaido.jp
assessments.cx
assn.lk
asso.ci
asso.dz
asso.eu.org
asso.fr
asso.gp
asso.ht
asso.km
asso.mc
asso.ml
asso.nc
asso.re
associates
association.aero
assur.bj
asti.it
asuke.aichi.jp
at
at-band-camp.net
at.emf.camp
at.eu.org
at.it
atami.shizuoka.jp
ath.cx
athleta
atl.jelastic.vps-host.net
atm.pl
atmeta.com
ato.br
atsugi.kanagawa.jp
atsuma.hokkaido.jp
attorney
au
au.eu.org
au.ngrok.io
auction
audi
audible
audio
audnedal.no
augustow.pl
aukra.no
aure.no
aurland.no
aurskog-holand.no
aus.basketball
auspost
austevoll.no
austrheim.no
auth-fips.us-east-1.amazoncognito.com
auth-fips.us-east-2.amazoncognito.com
auth-fips.us-gov-east-1.amazoncognito.com
auth-fips.us-gov-west-1.amazoncognito.com
auth-fips.us-west-1.amazoncognito.com
auth-fips.us-west-2.amazoncognito.com
auth.af-south-1.amazoncognito.com
auth.ap-east-1.amazoncognito.com
auth.ap-northeast-1.amazoncognito.com
auth.ap-northeast-2.amazoncognito.com
auth.ap-northeast-3.amazoncognito.com
auth.ap-south-1.amazoncognito.com
auth.ap-south-2.amazoncognito.com
auth.ap-southeast-1.amazoncognito.com
auth.ap-southeast-2.amazoncognito.com
auth.ap-southeast-3.amazoncognito.com
auth.ap-southeast-4.amazoncognito.com
auth.ap-southeast-5.amazoncognito.com
auth.ap-southeast-7.amazoncognito.com
auth.ca-central-1.amazoncognito.com
auth.ca-west-1.amazoncognito.com
auth.cognito-idp.eusc-de-east-1.on.amazonwebservices.eu
auth.eu-central-1.amazoncognito.com
auth.eu-central-2.amazoncognito.com
auth.eu-north-1.amazoncognito.com
auth.eu-south-1.amazoncognito.com
auth.eu-south-2.amazoncognito.com
auth.eu-west-1.amazoncognito.com
auth.eu-west-2.amazoncognito.com
auth.eu-west-3.amazoncognito.com
auth.il-central-1.amazoncognito.com
auth.me-central-1.amazoncognito.com
auth.me-south-1.amazoncognito.com
auth.mx-central-1.amazoncognito.com
auth.sa-east-1.amazoncognito.com
auth.us-east-1.amazoncognito.com
auth.us-east-2.amazoncognito.com
auth.us-west-1.amazoncognito.com
auth.us-west-2.amazoncognito.com
authgear-staging.com
authgearapps.com
author
author.aero
auto
auto.pl
autos
av.it
av.tr
avellino.it
averoy.no
avocat.fr
avocat.pro
avocats.bj
avoues.fr
aw
awaji.hyogo.jp
aws
awsapps.com
awsglobalaccelerator.com
ax
axa
aya.miyazaki.jp
ayabe.kyoto.jp
ayagawa.kagawa.jp
ayase.kanagawa.jp
az
az.us
azerbaijan.su
azimuth.network
azumino.nagano.jp
azure
azure-api.net
azure-api.us
azure-mobile.net
azureedge.net
azurefd.net
azurestaticapps.net
azurewebsites.net
azurewebsites.us
b-data.io
b.bg
b.br
b.se
b.ssl.fastly.net
ba
ba.gov.br
ba.it
ba.leg.br
babia-gora.pl
baby
babyblue.jp
babymilk.jp
bacgiang.vn
backan.vn
backdrop.jp
baclieu.vn
bacninh.vn
badaddja.no
bahcavuotna.no
bahccavuotna.no
baidar.no
baidu
bainbridge-isl.wa.us
bajddar.no
balashov.su
balat.no
balena-devices.com
balestrand.no
ballangen.no
ballooning.aero
balsan-sudtirol.it
balsan-suedtirol.it
balsan.it
balsfjord.no
bambina.jp
bamble.no
banamex
band
bandai.fukushima.jp
bando.ibaraki.jp
bank
bank.in
bar
bar.ec
bar.pro
barcelona
barclaycard
barclays
bardu.no
barefoot
bargains
bari.it
baria-vungtau.vn
barletta-trani-andria.it
barlettatraniandria.it
barrel-of-knowledge.info
barrell-of-knowledge.info
barsy.bg
barsy.ca
barsy.club
barsy.co.uk
barsy.de
barsy.dev
barsy.eu
barsy.gr
barsy.in
barsy.info
barsy.io
barsy.me
barsy.menu
barsy.mobi
barsy.net
barsy.online
barsy.org
barsy.pro
barsy.pub
barsy.ro
barsy.rs
barsy.shop
barsy.site
barsy.store
barsy.support
barsy.uk
barsycenter.com
barsyonline.co.uk
barsyonline.com
barsyonline.menu
barsyonline.shop
barueri.br
barum.no
bas.it
base.ec
base.shop
base44-sandbox.com
base44.app
baseball
bashkiria.ru
bashkiria.su
basicserver.io
basilicata.it
basketball
bato.tochigi.jp
batsfjord.no
bauhaus
bayern
bb
bbc
bbs.tr
bbt
bbva
bc.ca
bcg
bcn
bd
bd.se
be
be.eu.org
beagleboard.io
bearalvahki.no
bearblog.dev
beardu.no
beats
beauty
bedzin.pl
beep.pl
beer
beiarn.no
bel.tr
belem.br
bellevue.wa.us
belluno.it
benevento.it
bentre.vn
beppu.oita.jp
berg.no
bergamo.it
bergen.no
berlevag.no
berlin
beskidy.pl
best
bestbuy
bet
bet.ar
bet.br
beta.wmcloud.org
better-than.tv
bf
bg
bg.eu.org
bg.it
bh
bharti
bhz.br
bi
bi.it
bialowieza.pl
bialystok.pl
bib.br
bib.ve
bibai.hokkaido.jp
bible
bid
biei.hokkaido.jp
bielawa.pl
biella.it
bielsko.pl
bieszczady.pl
bievat.no
bifuka.hokkaido.jp
bihar.in
bihoro.hokkaido.jp
bike
bindal.no
bing
bingo
binhdinh.vn
binhduong.vn
binhphuoc.vn
binhthuan.vn
bio
bio.br
bir.ru
biratori.hokkaido.jp
birkenes.no
bitbucket.io
bitter.jp
biz
biz.az
biz.bb
biz.cy
biz.dk
biz.et
biz.fj
biz.gh
biz.id
biz.in
biz.ki
biz.ls
biz.mv
biz.mw
biz.my
biz.ng
biz.ni
biz.nr
biz.pk
biz.pl
biz.pr
biz.ss
biz.tj
biz.tr
biz.tt
biz.ua
biz.vn
biz.wf
biz.zm
bizen.okayama.jp
bj
bj.cn
bjerkreim.no
bjugn.no
bl.it
black
blackbaudcdn.net
blackfriday
blob.core.usgovcloudapi.net
blob.core.windows.net
blockbuster
blog
blog.bo
blog.br
blogdns.com
blogdns.net
blogdns.org
blogsite.org
blogspot.com
blogsyte.com
bloomberg
blue
bluebite.io
blush.jp
bm
bmd.br
bmoattachments.org
bms
bmw
bn
bn.it
bnpparibas
bnr.la
bo
bo.it
bo.nordland.no
bo.telemark.no
boats
boavista.br
bodo.no
boehringer
bofa
bokn.no
boldlygoingnowhere.org
boleslawiec.pl
bolivia.bo
bologna.it
bolt.host
bolt.hu
bolzano-altoadige.it
bolzano.it
bom
bomlo.no
bona.jp
bond
bones.replit.dev
boo
boo.jp
book
book.online
booking
boomla.net
bosch
bostik
boston
bot
botda.sh
botdash.app
botdash.dev
botdash.gg
botdash.net
botdash.xyz
bounceme.net
boutique
boutir.com
box
box.ca
boxfuse.io
boy.jp
boyfriend.jp
bozen-sudtirol.it
bozen-suedtirol.it
bozen.it
bplaced.com
bplaced.de
bplaced.net
br
br.com
br.it
bradesco
brand.se
brasilia.me
brave.app
brave.dev
brave.io
bremanger.no
bremerton.wa.us
brescia.it
bridgestone
brindisi.it
broadway
broke-it.net
broker
broker.aero
bronnoy.no
bronnoysund.no
brother
browsersafetymark.io
brumunddal.no
brussels
bryansk.su
bryne.no
bs
bs.it
bsb.br
bss.design
bt
bt.it
bu.no
bubbleapps.io
budejju.no
build
builders
builtwithdark.com
bukhara.su
bulsan-sudtirol.it
bulsan-suedtirol.it
bulsan.it
bumbleshrimp.com
bungoono.oita.jp
bungotakada.oita.jp
bunkyo.tokyo.jp
busan.kr
business
business.in
but.jp
buy`.split("\n").filter(Boolean);
