// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_06_02 = `poivron.org
poker
pokrovsk.su
pol.dz
pol.ht
pol.tr
police.uk
politica.bo
politie
polkowice.pl
poltava.ua
polyspace.com
pomorskie.pl
pomorze.pl
poniatowa.pl
ponpes.id
pordenone.it
porn
porsanger.no
porsangu.no
porsgrunn.no
port-angeles.wa.us
port-ludlow.wa.us
port-orchard.wa.us
port-townsend.wa.us
port.fr
post
post.in
postman-echo.com
potager.org
potenza.it
poulsbo.wa.us
powiat.pl
poznan.pl
pp.az
pp.ru
pp.se
pp.ua
ppg.br
pplx.app
pr
pr.gov.br
pr.gov.pl
pr.it
pr.leg.br
pr.ml
pr.us
prato.it
praxi
prd.fr
prd.km
prd.mg
prequalifyme.today
prerelease.replit.dev
press
press.aero
press.cy
press.ma
press.se
presse.km
presse.ml
preview.csb.app
preview.emergentagent.com
preview.site
prg1-zerops.zone
pri.ee
prime
primetel.cloud
principe.st
priv.at
priv.hu
priv.instances.scw.cloud
priv.me
priv.no
priv.pl
privatizehealthinsurance.net
pro
pro.az
pro.br
pro.cy
pro.ec
pro.fj
pro.ht
pro.in
pro.mv
pro.om
pro.pr
pro.tt
pro.typeform.com
pro.vn
prochowice.pl
prod
production.aero
productions
prof
prof.ec
prof.pr
profesional.bo
progressive
project.space
promo
properties
property
protection
pru
prudential
pruszkow.pl
prvcy.page
prvw.eu
przeworsk.pl
ps
psc.br
psi.br
psic.ec
psiq.ec
psp.gov.pl
psse.gov.pl
pstmn.io
pt
pt.eu.org
pt.it
pu.it
pub
pub.ec
pub.instances.scw.cloud
pub.sa
publ.cv
publ.pt
public-inquiry.uk
pubtls.org
pueblo.bo
pug.it
puglia.it
pulawy.pl
punyu.jp
pup.gov.pl
pupu.jp
pussycat.jp
puter.app
puter.site
puter.work
pv.it
pvh.br
pvt.ge
pvt.k12.ma.us
pw
pwc
py
pya.jp
pyatigorsk.ru
pymnt.uk
pythonanywhere.com
pz.it
q.bg
qa
qa2.com
qbuser.com
qc.ca
qcx.io
qh.cn
qld.au
qld.edu.au
qld.gov.au
qoto.io
qpon
qsl.br
qualifioapp.com
quangbinh.vn
quangnam.vn
quangngai.vn
quangninh.vn
quangtri.vn
quebec
quest
quicksytes.com
quizzes.cx
qzz.io
r.bg
r.cdn77.net
r.se
r2.dev
ra.it
racing
rackmaze.com
rackmaze.net
rade.no
radio
radio.am
radio.br
radio.fm
radom.pl
radoy.no
raffleentry.org.uk
rag-cloud-ch.hosteur.com
rag-cloud.hosteur.com
ragusa.it
rahkkeravju.no
raholt.no
raindrop.jp
raisa.no
rakkestad.no
ralingen.no
rana.no
randaberg.no
rankoshi.hokkaido.jp
ranzan.saitama.jp
rar.ve
ras.ru
rauma.no
ravendb.cloud
ravendb.community
ravendb.run
ravenna.it
ravpage.co.il
rawa-maz.pl
rc.it
rdb.fr-par.scw.cloud
rdb.nl-ams.scw.cloud
rdb.pl-waw.scw.cloud
rdy.jp
re
re.it
re.kr
re.no
read
read-books.org
readmyblog.org
readthedocs-hosted.com
readthedocs.io
readymade.jp
realestate
realestate.pl
realm.cz
realtime.supabase.co
realtor
realty
rebun.hokkaido.jp
rec.br
rec.nf
rec.ro
rec.ve
recht.pro
recife.br
recipes
recreation.aero
red
red.sv
redirectme.net
redmond.wa.us
redumbrella
reed.replit.dev
reg.dk
reggio-calabria.it
reggio-emilia.it
reggiocalabria.it
reggioemilia.it
rehab
reise
reisen
reit
reklam.hu
rel.ht
rel.pl
relay.evervault.app
relay.evervault.dev
reliance
remotewd.com
ren
rendalen.no
rennebu.no
rennesoy.no
rent
rentals
renton.wa.us
rep.br
rep.kp
repair
repbody.aero
repl.co
repl.run
replit.app
replit.dev
report
republican
res.aero
res.in
research.aero
researched.cx
reservd.com
reservd.dev.thingdust.io
reservd.disrec.thingdust.io
reservd.testing.thingdust.io
reserve-online.net
resindevice.io
resolve.bar
rest
restaurant
restaurant.bj
resto.bj
review
reviews
revista.bo
rexroth
rg.it
rgr.jp
rhcloud.com
ri.it
ri.us
ribeirao.br
ric.jelastic.vps-host.net
rice-labs.com
rich
richardli
ricoh
rieti.it
rifu.miyagi.jp
riik.ee
riker.replit.dev
rikubetsu.hokkaido.jp
rikuzentakata.iwate.jp
ril
rimini.it
rindal.no
ringebu.no
ringerike.no
ringsaker.no
rio
rio.br
rio.ec
riobranco.br
riopreto.br
rip
rishiri.hokkaido.jp
rishirifuji.hokkaido.jp
risor.no
rissa.no
ritto.shiga.jp
rivne.ua
rj.gov.br
rj.leg.br
rl.no
rm.it
rma.objectstorage.ch
rn.gov.br
rn.it
rn.leg.br
ro
ro.eu.org
ro.gov.br
ro.it
ro.leg.br
roan.no
rocks
rocky.page
rodeo
rodoy.no
rogers
rokunohe.aomori.jp
rollag.no
roma.it
rome.it
romsa.no
romskog.no
room
roros.no
rost.no
rotorcraft.aero
routingthecloud.com
routingthecloud.net
routingthecloud.org
rovigo.it
rovno.ua
roxa.org
royal-commission.uk
royken.no
royrvik.no
rr.gov.br
rr.leg.br
rrpp.ec
rs
rs.ba
rs.gov.br
rs.leg.br
rs.webaccel.jp
rsc.cdn77.org
rsc.contentproxy9.cz
rsvp
rt.ht
ru
ru.com
ru.eu.org
ru.net
rub.de
rugby
ruhr
ruhr-uni-bochum.de
rulez.jp
run
runcontainers.dev
runs.onstackit.cloud
ruovat.no
rv.ua
rw
rwe
rybnik.pl
ryd.wafaicloud.com
rygge.no
ryokami.saitama.jp
ryugasaki.ibaraki.jp
ryukyu
ryuoh.shiga.jp
rzeszow.pl
rzgw.gov.pl
s.bg
s.se
s3-1.amazonaws.com
s3-accesspoint-fips.ca-central-1.amazonaws.com
s3-accesspoint-fips.ca-west-1.amazonaws.com
s3-accesspoint-fips.dualstack.ca-central-1.amazonaws.com
s3-accesspoint-fips.dualstack.ca-west-1.amazonaws.com
s3-accesspoint-fips.dualstack.us-east-1.amazonaws.com
s3-accesspoint-fips.dualstack.us-east-2.amazonaws.com
s3-accesspoint-fips.dualstack.us-gov-east-1.amazonaws.com
s3-accesspoint-fips.dualstack.us-gov-west-1.amazonaws.com
s3-accesspoint-fips.dualstack.us-west-1.amazonaws.com
s3-accesspoint-fips.dualstack.us-west-2.amazonaws.com
s3-accesspoint-fips.us-east-1.amazonaws.com
s3-accesspoint-fips.us-east-2.amazonaws.com
s3-accesspoint-fips.us-gov-east-1.amazonaws.com
s3-accesspoint-fips.us-gov-west-1.amazonaws.com
s3-accesspoint-fips.us-west-1.amazonaws.com
s3-accesspoint-fips.us-west-2.amazonaws.com
s3-accesspoint.af-south-1.amazonaws.com
s3-accesspoint.ap-east-1.amazonaws.com
s3-accesspoint.ap-northeast-1.amazonaws.com
s3-accesspoint.ap-northeast-2.amazonaws.com
s3-accesspoint.ap-northeast-3.amazonaws.com
s3-accesspoint.ap-south-1.amazonaws.com
s3-accesspoint.ap-south-2.amazonaws.com
s3-accesspoint.ap-southeast-1.amazonaws.com
s3-accesspoint.ap-southeast-2.amazonaws.com
s3-accesspoint.ap-southeast-3.amazonaws.com
s3-accesspoint.ap-southeast-4.amazonaws.com
s3-accesspoint.ap-southeast-5.amazonaws.com
s3-accesspoint.ca-central-1.amazonaws.com
s3-accesspoint.ca-west-1.amazonaws.com
s3-accesspoint.cn-north-1.amazonaws.com.cn
s3-accesspoint.cn-northwest-1.amazonaws.com.cn
s3-accesspoint.dualstack.af-south-1.amazonaws.com
s3-accesspoint.dualstack.ap-east-1.amazonaws.com
s3-accesspoint.dualstack.ap-northeast-1.amazonaws.com
s3-accesspoint.dualstack.ap-northeast-2.amazonaws.com
s3-accesspoint.dualstack.ap-northeast-3.amazonaws.com
s3-accesspoint.dualstack.ap-south-1.amazonaws.com
s3-accesspoint.dualstack.ap-south-2.amazonaws.com
s3-accesspoint.dualstack.ap-southeast-1.amazonaws.com
s3-accesspoint.dualstack.ap-southeast-2.amazonaws.com
s3-accesspoint.dualstack.ap-southeast-3.amazonaws.com
s3-accesspoint.dualstack.ap-southeast-4.amazonaws.com`.split("\n").filter(Boolean);
