// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_07_01 = `s3.dualstack.af-south-1.amazonaws.com
s3.dualstack.ap-east-1.amazonaws.com
s3.dualstack.ap-northeast-1.amazonaws.com
s3.dualstack.ap-northeast-2.amazonaws.com
s3.dualstack.ap-northeast-3.amazonaws.com
s3.dualstack.ap-south-1.amazonaws.com
s3.dualstack.ap-south-2.amazonaws.com
s3.dualstack.ap-southeast-1.amazonaws.com
s3.dualstack.ap-southeast-2.amazonaws.com
s3.dualstack.ap-southeast-3.amazonaws.com
s3.dualstack.ap-southeast-4.amazonaws.com
s3.dualstack.ap-southeast-5.amazonaws.com
s3.dualstack.ca-central-1.amazonaws.com
s3.dualstack.ca-west-1.amazonaws.com
s3.dualstack.cn-north-1.amazonaws.com.cn
s3.dualstack.cn-northwest-1.amazonaws.com.cn
s3.dualstack.eu-central-1.amazonaws.com
s3.dualstack.eu-central-2.amazonaws.com
s3.dualstack.eu-north-1.amazonaws.com
s3.dualstack.eu-south-1.amazonaws.com
s3.dualstack.eu-south-2.amazonaws.com
s3.dualstack.eu-west-1.amazonaws.com
s3.dualstack.eu-west-2.amazonaws.com
s3.dualstack.eu-west-3.amazonaws.com
s3.dualstack.il-central-1.amazonaws.com
s3.dualstack.me-central-1.amazonaws.com
s3.dualstack.me-south-1.amazonaws.com
s3.dualstack.sa-east-1.amazonaws.com
s3.dualstack.us-east-1.amazonaws.com
s3.dualstack.us-east-2.amazonaws.com
s3.dualstack.us-gov-east-1.amazonaws.com
s3.dualstack.us-gov-west-1.amazonaws.com
s3.dualstack.us-west-1.amazonaws.com
s3.dualstack.us-west-2.amazonaws.com
s3.eu-central-1.amazonaws.com
s3.eu-central-2.amazonaws.com
s3.eu-north-1.amazonaws.com
s3.eu-south-1.amazonaws.com
s3.eu-south-2.amazonaws.com
s3.eu-west-1.amazonaws.com
s3.eu-west-2.amazonaws.com
s3.eu-west-3.amazonaws.com
s3.fr-par.scw.cloud
s3.il-central-1.amazonaws.com
s3.isk01.sakurastorage.jp
s3.isk02.sakurastorage.jp
s3.k2.cloud
s3.me-central-1.amazonaws.com
s3.me-south-1.amazonaws.com
s3.nl-ams.scw.cloud
s3.pl-waw.scw.cloud
s3.ru-msk.k2.cloud
s3.ru-spb.k2.cloud
s3.sa-east-1.amazonaws.com
s3.teckids.org
s3.us-east-1.amazonaws.com
s3.us-east-2.amazonaws.com
s3.us-gov-east-1.amazonaws.com
s3.us-gov-west-1.amazonaws.com
s3.us-west-1.amazonaws.com
s3.us-west-2.amazonaws.com
sa
sa-east-1.elasticbeanstalk.com
sa.au
sa.com
sa.cr
sa.edu.au
sa.gov.au
sa.gov.pl
sa.it
sa.ngrok.io
saarland
sabae.fukui.jp
sadist.jp
sado.niigata.jp
safe
safety
safety.aero
saga.jp
saga.saga.jp
sagae.yamagata.jp
sagamihara.kanagawa.jp
saigawa.fukuoka.jp
saijo.ehime.jp
saikai.nagasaki.jp
saiki.oita.jp
saitama.jp
saitama.saitama.jp
saito.miyazaki.jp
saka.hiroshima.jp
sakado.saitama.jp
sakae.chiba.jp
sakae.nagano.jp
sakahogi.gifu.jp
sakai.fukui.jp
sakai.ibaraki.jp
sakai.osaka.jp
sakaiminato.tottori.jp
sakaki.nagano.jp
sakata.yamagata.jp
sakawa.kochi.jp
sakegawa.yamagata.jp
saku.nagano.jp
sakuho.nagano.jp
sakura
sakura.chiba.jp
sakura.ne.jp
sakura.tochigi.jp
sakura.tv
sakuragawa.ibaraki.jp
sakurai.nara.jp
sakuratan.com
sakuraweb.com
sakyo.kyoto.jp
sal.ec
salangen.no
salat.no
sale
salerno.it
salon
saloon.jp
saltdal.no
salud.bo
salvador.br
same-app.com
same-preview.com
samegawa.fukushima.jp
samnanger.no
sampa.br
samsclub
samsung
samukawa.kanagawa.jp
sanagochi.tokushima.jp
sanda.hyogo.jp
sandbox.deno.net
sandcats.io
sande.more-og-romsdal.no
sande.vestfold.no
sande.xn--mre-og-romsdal-qqb.no
sandefjord.no
sandnes.no
sandnessjoen.no
sandoy.no
sandvik
sandvikcoromant
sango.nara.jp
sanjo.niigata.jp
sannan.hyogo.jp
sannohe.aomori.jp
sano.tochigi.jp
sanofi
sanok.pl
santamaria.br
santoandre.br
sanuki.kagawa.jp
saobernardo.br
saogonca.br
saotome.st
sap
sar.it
sardegna.it
sardinia.it
sarl
saroma.hokkaido.jp
sarpsborg.no
sarufutsu.hokkaido.jp
sas
sasaguri.fukuoka.jp
sasayama.hyogo.jp
sasebo.nagasaki.jp
sassari.it
satosho.okayama.jp
satsumasendai.kagoshima.jp
satte.saitama.jp
sauda.no
sauherad.no
sav.case
save
saves-the-whales.com
savona.it
saxo
sayama.osaka.jp
sayama.saitama.jp
sayo.hyogo.jp
sb
sb.ua
sbi
sblo.jp
sbs
sc
sc.cn
sc.gov.br
sc.ke
sc.kr
sc.leg.br
sc.ls
sc.tz
sc.ug
sc.us
scalebook.scw.cloud
scb
scbl.fr-par.scw.cloud
scbl.nl-ams.scw.cloud
scbl.pl-waw.scw.cloud
sch.ac
sch.ae
sch.bd
sch.id
sch.ir
sch.jo
sch.lk
sch.ly
sch.ng
sch.qa
sch.sa
sch.ss
sch.tf
sch.wf
sch.zm
schaeffler
schmidt
schokokeks.net
scholarships
school
school.ge
school.in
school.nz
school.za
schoolbus.jp
schuldock.de
schule
schulplattform.de
schulserver.de
schwarz
sci.eg
science
scientist.aero
scot
scrapper-site.net
scrapping.cc
scrysec.com
sd
sd.cn
sd.us
sdn.gov.pl
sdscloud.pl
se
se.eu.org
se.gov.br
se.leg.br
se.net
sea.wa.us
search
seat
seattle.wa.us
sebastopol.ua
sec.ps
secret.jp
secure
security
securitytactics.com
seek
seg.ar
seg.br
seidat.net
seihi.nagasaki.jp
seika.kyoto.jp
seiro.niigata.jp
seirou.niigata.jp
seiyo.ehime.jp
sejny.pl
sekd1.beebyteapp.io
seki.gifu.jp
sekigahara.gifu.jp
sekikawa.niigata.jp
sel.no
selbu.no
select
selfip.biz
selfip.com
selfip.info
selfip.net
selfip.org
selje.no
seljord.no
sellfy.store
sells-for-less.com
sells-for-u.com
sells-it.net
sellsyourhome.org
semboku.akita.jp
semine.miyagi.jp
senasa.ar
sener
sennan.osaka.jp
senseering.net
seoul.kr
seprox.hooc.me
sequim.wa.us
sera.hiroshima.jp
seranishi.hiroshima.jp
servebbs.com
servebbs.net
servebbs.org
servebeer.com
serveblog.net
servebolt.cloud
servecounterstrike.com
serveexchange.com
serveftp.com
serveftp.net
serveftp.org
servegame.com
servegame.org
servehalflife.com
servehttp.com
servehumour.com
serveirc.com
serveminecraft.net
servemp3.com
servep2p.com
servepics.com
servequake.com
server-on.net
servername.us
servesarcasm.com
service.gov.scot
service.gov.uk
service.one
servicebus.usgovcloudapi.net
servicebus.windows.net
services
services.aero
setagaya.tokyo.jp
seto.aichi.jp
setouchi.okayama.jp
settsu.osaka.jp
sevastopol.ua
seven
sew
sex
sex.hu
sex.pl
sexy
sf.no
sfr
sg
sg-1.paas.massivegrid.net
sh
sh.cn
shacknet.nu
shakotan.hokkaido.jp
shangrila
shari.hokkaido.jp
sharp
sheezy.games
shell
shelton.wa.us
shia
shibata.miyagi.jp
shibata.niigata.jp
shibecha.hokkaido.jp
shibetsu.hokkaido.jp
shibukawa.gunma.jp
shibuya.tokyo.jp
shichikashuku.miyagi.jp
shichinohe.aomori.jp
shiga.jp
shiiba.miyazaki.jp
shijonawate.osaka.jp
shika.ishikawa.jp
shikabe.hokkaido.jp
shikama.miyagi.jp
shikaoi.hokkaido.jp
shikatsu.aichi.jp
shiki.saitama.jp
shikokuchuo.ehime.jp
shiksha
shima.mie.jp
shimabara.nagasaki.jp
shimada.shizuoka.jp
shimamaki.hokkaido.jp
shimamoto.osaka.jp
shimane.jp
shimane.shimane.jp
shimizu.hokkaido.jp
shimizu.shizuoka.jp
shimoda.shizuoka.jp
shimodate.ibaraki.jp
shimofusa.chiba.jp
shimogo.fukushima.jp
shimoichi.nara.jp
shimoji.okinawa.jp
shimokawa.hokkaido.jp
shimokitayama.nara.jp
shimonita.gunma.jp
shimonoseki.yamaguchi.jp
shimosuwa.nagano.jp
shimotsuke.tochigi.jp`.split("\n").filter(Boolean);
