// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_06_03 = `s3-accesspoint.dualstack.ap-southeast-5.amazonaws.com
s3-accesspoint.dualstack.ca-central-1.amazonaws.com
s3-accesspoint.dualstack.ca-west-1.amazonaws.com
s3-accesspoint.dualstack.cn-north-1.amazonaws.com.cn
s3-accesspoint.dualstack.cn-northwest-1.amazonaws.com.cn
s3-accesspoint.dualstack.eu-central-1.amazonaws.com
s3-accesspoint.dualstack.eu-central-2.amazonaws.com
s3-accesspoint.dualstack.eu-north-1.amazonaws.com
s3-accesspoint.dualstack.eu-south-1.amazonaws.com
s3-accesspoint.dualstack.eu-south-2.amazonaws.com
s3-accesspoint.dualstack.eu-west-1.amazonaws.com
s3-accesspoint.dualstack.eu-west-2.amazonaws.com
s3-accesspoint.dualstack.eu-west-3.amazonaws.com
s3-accesspoint.dualstack.il-central-1.amazonaws.com
s3-accesspoint.dualstack.me-central-1.amazonaws.com
s3-accesspoint.dualstack.me-south-1.amazonaws.com
s3-accesspoint.dualstack.sa-east-1.amazonaws.com
s3-accesspoint.dualstack.us-east-1.amazonaws.com
s3-accesspoint.dualstack.us-east-2.amazonaws.com
s3-accesspoint.dualstack.us-gov-east-1.amazonaws.com
s3-accesspoint.dualstack.us-gov-west-1.amazonaws.com
s3-accesspoint.dualstack.us-west-1.amazonaws.com
s3-accesspoint.dualstack.us-west-2.amazonaws.com
s3-accesspoint.eu-central-1.amazonaws.com
s3-accesspoint.eu-central-2.amazonaws.com
s3-accesspoint.eu-north-1.amazonaws.com
s3-accesspoint.eu-south-1.amazonaws.com
s3-accesspoint.eu-south-2.amazonaws.com
s3-accesspoint.eu-west-1.amazonaws.com
s3-accesspoint.eu-west-2.amazonaws.com
s3-accesspoint.eu-west-3.amazonaws.com
s3-accesspoint.il-central-1.amazonaws.com
s3-accesspoint.me-central-1.amazonaws.com
s3-accesspoint.me-south-1.amazonaws.com
s3-accesspoint.sa-east-1.amazonaws.com
s3-accesspoint.us-east-1.amazonaws.com
s3-accesspoint.us-east-2.amazonaws.com
s3-accesspoint.us-gov-east-1.amazonaws.com
s3-accesspoint.us-gov-west-1.amazonaws.com
s3-accesspoint.us-west-1.amazonaws.com
s3-accesspoint.us-west-2.amazonaws.com
s3-ap-east-1.amazonaws.com
s3-ap-northeast-1.amazonaws.com
s3-ap-northeast-2.amazonaws.com
s3-ap-northeast-3.amazonaws.com
s3-ap-south-1.amazonaws.com
s3-ap-southeast-1.amazonaws.com
s3-ap-southeast-2.amazonaws.com
s3-ca-central-1.amazonaws.com
s3-deprecated.ap-southeast-5.amazonaws.com
s3-deprecated.cn-north-1.amazonaws.com.cn
s3-deprecated.eu-west-1.amazonaws.com
s3-deprecated.us-east-1.amazonaws.com
s3-deprecated.us-east-2.amazonaws.com
s3-deprecated.us-west-2.amazonaws.com
s3-eu-central-1.amazonaws.com
s3-eu-north-1.amazonaws.com
s3-eu-west-1.amazonaws.com
s3-eu-west-2.amazonaws.com
s3-eu-west-3.amazonaws.com
s3-external-1.amazonaws.com
s3-fips-us-gov-east-1.amazonaws.com
s3-fips-us-gov-west-1.amazonaws.com
s3-fips.ca-central-1.amazonaws.com
s3-fips.ca-west-1.amazonaws.com
s3-fips.dualstack.ca-central-1.amazonaws.com
s3-fips.dualstack.ca-west-1.amazonaws.com
s3-fips.dualstack.us-east-1.amazonaws.com
s3-fips.dualstack.us-east-2.amazonaws.com
s3-fips.dualstack.us-gov-east-1.amazonaws.com
s3-fips.dualstack.us-gov-west-1.amazonaws.com
s3-fips.dualstack.us-west-1.amazonaws.com
s3-fips.dualstack.us-west-2.amazonaws.com
s3-fips.us-east-1.amazonaws.com
s3-fips.us-east-2.amazonaws.com
s3-fips.us-gov-east-1.amazonaws.com
s3-fips.us-gov-west-1.amazonaws.com
s3-fips.us-west-1.amazonaws.com
s3-fips.us-west-2.amazonaws.com
s3-me-south-1.amazonaws.com
s3-object-lambda.af-south-1.amazonaws.com
s3-object-lambda.ap-east-1.amazonaws.com
s3-object-lambda.ap-northeast-1.amazonaws.com
s3-object-lambda.ap-northeast-2.amazonaws.com
s3-object-lambda.ap-northeast-3.amazonaws.com
s3-object-lambda.ap-south-1.amazonaws.com
s3-object-lambda.ap-south-2.amazonaws.com
s3-object-lambda.ap-southeast-1.amazonaws.com
s3-object-lambda.ap-southeast-2.amazonaws.com
s3-object-lambda.ap-southeast-3.amazonaws.com
s3-object-lambda.ap-southeast-4.amazonaws.com
s3-object-lambda.ap-southeast-5.amazonaws.com
s3-object-lambda.ca-central-1.amazonaws.com
s3-object-lambda.ca-west-1.amazonaws.com
s3-object-lambda.cn-north-1.amazonaws.com.cn
s3-object-lambda.cn-northwest-1.amazonaws.com.cn
s3-object-lambda.eu-central-1.amazonaws.com
s3-object-lambda.eu-central-2.amazonaws.com
s3-object-lambda.eu-north-1.amazonaws.com
s3-object-lambda.eu-south-1.amazonaws.com
s3-object-lambda.eu-south-2.amazonaws.com
s3-object-lambda.eu-west-1.amazonaws.com
s3-object-lambda.eu-west-2.amazonaws.com
s3-object-lambda.eu-west-3.amazonaws.com
s3-object-lambda.il-central-1.amazonaws.com
s3-object-lambda.me-central-1.amazonaws.com
s3-object-lambda.me-south-1.amazonaws.com
s3-object-lambda.sa-east-1.amazonaws.com
s3-object-lambda.us-east-1.amazonaws.com
s3-object-lambda.us-east-2.amazonaws.com
s3-object-lambda.us-gov-east-1.amazonaws.com
s3-object-lambda.us-gov-west-1.amazonaws.com
s3-object-lambda.us-west-1.amazonaws.com
s3-object-lambda.us-west-2.amazonaws.com
s3-sa-east-1.amazonaws.com
s3-us-east-2.amazonaws.com
s3-us-gov-east-1.amazonaws.com
s3-us-gov-west-1.amazonaws.com
s3-us-west-1.amazonaws.com
s3-us-west-2.amazonaws.com
s3-website-ap-northeast-1.amazonaws.com
s3-website-ap-southeast-1.amazonaws.com
s3-website-ap-southeast-2.amazonaws.com
s3-website-eu-west-1.amazonaws.com
s3-website-sa-east-1.amazonaws.com
s3-website-us-east-1.amazonaws.com
s3-website-us-gov-west-1.amazonaws.com
s3-website-us-west-1.amazonaws.com
s3-website-us-west-2.amazonaws.com
s3-website.af-south-1.amazonaws.com
s3-website.ap-east-1.amazonaws.com
s3-website.ap-northeast-1.amazonaws.com
s3-website.ap-northeast-2.amazonaws.com
s3-website.ap-northeast-3.amazonaws.com
s3-website.ap-south-1.amazonaws.com
s3-website.ap-south-2.amazonaws.com
s3-website.ap-southeast-1.amazonaws.com
s3-website.ap-southeast-2.amazonaws.com
s3-website.ap-southeast-3.amazonaws.com
s3-website.ap-southeast-4.amazonaws.com
s3-website.ap-southeast-5.amazonaws.com
s3-website.ca-central-1.amazonaws.com
s3-website.ca-west-1.amazonaws.com
s3-website.cn-north-1.amazonaws.com.cn
s3-website.cn-northwest-1.amazonaws.com.cn
s3-website.dualstack.af-south-1.amazonaws.com
s3-website.dualstack.ap-northeast-1.amazonaws.com
s3-website.dualstack.ap-northeast-2.amazonaws.com
s3-website.dualstack.ap-northeast-3.amazonaws.com
s3-website.dualstack.ap-south-1.amazonaws.com
s3-website.dualstack.ap-south-2.amazonaws.com
s3-website.dualstack.ap-southeast-1.amazonaws.com
s3-website.dualstack.ap-southeast-2.amazonaws.com
s3-website.dualstack.ap-southeast-3.amazonaws.com
s3-website.dualstack.ap-southeast-4.amazonaws.com
s3-website.dualstack.ap-southeast-5.amazonaws.com
s3-website.dualstack.ca-central-1.amazonaws.com
s3-website.dualstack.ca-west-1.amazonaws.com`.split("\n").filter(Boolean);
