// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_07_02 = `shimotsuma.ibaraki.jp
shinagawa.tokyo.jp
shinanomachi.nagano.jp
shingo.aomori.jp
shingu.fukuoka.jp
shingu.hyogo.jp
shingu.wakayama.jp
shinichi.hiroshima.jp
shinjo.nara.jp
shinjo.okayama.jp
shinjo.yamagata.jp
shinjuku.tokyo.jp
shinkamigoto.nagasaki.jp
shinonsen.hyogo.jp
shinshinotsu.hokkaido.jp
shinshiro.aichi.jp
shinto.gunma.jp
shintoku.hokkaido.jp
shintomi.miyazaki.jp
shinyoshitomi.fukuoka.jp
shiogama.miyagi.jp
shiojiri.nagano.jp
shioya.tochigi.jp
shiptoday.app
shiptoday.build
shirahama.wakayama.jp
shirakawa.fukushima.jp
shirakawa.gifu.jp
shirako.chiba.jp
shiranuka.hokkaido.jp
shiraoi.hokkaido.jp
shiraoka.saitama.jp
shirataka.yamagata.jp
shiriuchi.hokkaido.jp
shiroi.chiba.jp
shiroishi.miyagi.jp
shiroishi.saga.jp
shirosato.ibaraki.jp
shishikui.tokushima.jp
shiso.hyogo.jp
shisui.chiba.jp
shitara.aichi.jp
shiwa.iwate.jp
shizukuishi.iwate.jp
shizuoka.jp
shizuoka.shizuoka.jp
shobara.hiroshima.jp
shoes
shonai.fukuoka.jp
shonai.yamagata.jp
shoo.okayama.jp
shop
shop.brendly.ba
shop.brendly.hr
shop.brendly.rs
shop.ht
shop.hu
shop.pl
shop.ro
shop.th
shoparena.pl
shopitsite.com
shopping
shopselect.net
shopware.shop
shopware.store
shouji
show
show.aero
showa.fukushima.jp
showa.gunma.jp
showa.yamanashi.jp
shunan.yamaguchi.jp
si
si.eu.org
si.it
sic.it
sicilia.it
sicily.it
siellak.no
siena.it
sieradz.pl
sigdal.no
siiites.com
siljan.no
silk
silverdale.wa.us
simple-url.com
simplesite.com
simplesite.com.br
simplesite.gr
simplesite.pl
sina
sinaapp.com
singles
siracusa.it
sirdal.no
sisko.replit.dev
site
site.rb-hosting.io
site.tb-hosting.com
site.transip.me
siteleaf.net
sj
sjc.br
sk
sk.ca
sk.eu.org
skanit.no
skanland.no
skaun.no
skedsmo.no
skedsmokorset.no
ski
ski.no
skien.no
skierniewice.pl
skierva.no
skin
skiptvet.no
skjak.no
skjervoy.no
sklep.pl
sko.gov.pl
skoczow.pl
skodje.no
skr.jp
sky
skydiving.aero
skype
sl
slask.pl
slattum.no
sld.do
sld.pa
slg.br
sling
slupsk.pl
slz.br
sm
sm.ua
small-web.org
smart
smartlabeling.scw.cloud
smile
smola.no
smushcdn.com
sn
sn.cn
sn.mynetname.net
snaase.no
snasa.no
sncf
snillfjord.no
snoasa.no
so
so.gov.pl
so.it
sobetsu.hokkaido.jp
soc.dz
soc.lk
soc.srcf.net
soccer
sochi.su
social
social.br
soctrang.vn
sodegaura.chiba.jp
soeda.fukuoka.jp
softbank
software
software.aero
sogndal.no
sogne.no
sohu
soja.okayama.jp
soka.saitama.jp
sokndal.no
sol.site
sola.no
solar
solund.no
solutions
soma.fukushima.jp
somna.no
sondre-land.no
sondrio.it
song
songdalen.no
soni.nara.jp
sonla.vn
sony
soo.kagoshima.jp
sopot.pl
sor-aurdal.no
sor-fron.no
sor-odal.no
sor-varanger.no
sorfold.no
sorocaba.br
sorreisa.no
sortland.no
sorum.no
sos.pl
sosa.chiba.jp
sosnowiec.pl
soundcast.me
sourcecraft.site
sowa.ibaraki.jp
soy
sp.gov.br
sp.it
sp.leg.br
spa
space
space-to-rent.com
spawnbase.app
spb.ru
spb.su
spdns.de
spdns.eu
spdns.org
sphinx.mythic-beasts.com
spjelkavik.no
spock.replit.dev
sport
sport.eg
sport.hu
spot
sprites.app
spryt.net
spydeberg.no
square.site
square7.ch
square7.de
square7.net
squares.net
sr
sr.gov.pl
sr.it
srht.site
srl
srv.br
srv.us
srvdns.de
sryze.cc
ss
ss.it
ssl.origin.cdn77-secure.org
st
st.no
staba.jp
stackhero-network.com
stackit.gg
stackit.rocks
stackit.run
stackit.zone
stada
stage.nodeart.io
staging.expo.app
staging.replit.dev
stalowa-wola.pl
stange.no
staples
star
starachowice.pl
stargard.pl
starostwo.gov.pl
stat.no
statebank
statefarm
stathelle.no
static-access.net
static.hf.space
static.observableusercontent.com
statichost.page
stavanger.no
stavern.no
stc
stcgroup
steigen.no
steinkjer.no
sth.ac.at
stjordal.no
stjordalshalsen.no
stockholm
stokke.no
stor-elvdal.no
storage
storage.supabase.co
storage.yandexcloud.net
stord.no
stordal.no
store
store.bb
store.cv
store.dk
store.nf
store.ro
store.st
store.ve
storebase.store
storfjord.no
strand.no
stranda.no
strapiapp.com
streak-link.com
streaklinks.com
streakusercontent.com
stream
streamlit.app
streamlitapp.com
stripper.jp
stryn.no
student.aero
studio
studio-fips.us-gov-east-1.sagemaker.aws
studio-fips.us-gov-west-1.sagemaker.aws
studio.af-south-1.sagemaker.aws
studio.ap-east-1.sagemaker.aws
studio.ap-northeast-1.sagemaker.aws
studio.ap-northeast-2.sagemaker.aws
studio.ap-northeast-3.sagemaker.aws
studio.ap-south-1.sagemaker.aws
studio.ap-southeast-1.sagemaker.aws
studio.ap-southeast-2.sagemaker.aws
studio.ap-southeast-3.sagemaker.aws
studio.ca-central-1.sagemaker.aws
studio.cn-north-1.sagemaker.com.cn
studio.cn-northwest-1.sagemaker.com.cn
studio.eu-central-1.sagemaker.aws
studio.eu-central-2.sagemaker.aws
studio.eu-north-1.sagemaker.aws
studio.eu-south-1.sagemaker.aws
studio.eu-south-2.sagemaker.aws
studio.eu-west-1.sagemaker.aws
studio.eu-west-2.sagemaker.aws
studio.eu-west-3.sagemaker.aws
studio.il-central-1.sagemaker.aws
studio.me-central-1.sagemaker.aws
studio.me-south-1.sagemaker.aws
studio.sa-east-1.sagemaker.aws
studio.us-east-1.sagemaker.aws
studio.us-east-2.sagemaker.aws
studio.us-gov-east-1.sagemaker.aws
studio.us-gov-west-1.sagemaker.aws
studio.us-west-1.sagemaker.aws
studio.us-west-2.sagemaker.aws
study
stuff-4-sale.org
stuff-4-sale.us
stufftoread.com
style
su
su.it
sub.jp
subsc-pay.com
subsc-pay.net
sucks
sud-sardegna.it
sudsardegna.it
sue.fukuoka.jp
suedtirol.it
suginami.tokyo.jp
sugito.saitama.jp
suifu.ibaraki.jp
suita.osaka.jp
sukagawa.fukushima.jp
sukumo.kochi.jp
sula.no
suldal.no
suli.hu
sulu.replit.dev
sumida.tokyo.jp
sumita.iwate.jp
sumomo.ne.jp
sumoto.hyogo.jp
sumoto.kumamoto.jp
sumy.ua
sunagawa.hokkaido.jp
sund.no
sunndal.no
sunnyday.jp
suohkan.no
supabase.co
supabase.in
supabase.net
supersale.jp
supplies
supply
support
support.site
surf
surgery
surnadal.no
surveys.so
susaki.kochi.jp
susono.shizuoka.jp
suwa.nagano.jp
suwalki.pl
suzaka.nagano.jp
suzu.ishikawa.jp
suzuka.mie.jp
suzuki
sv
sv.it
svalbard.no
sveio.no
svelvik.no
svn-repos.de
swatch
sweetpepper.org
swidnica.pl
swidnik.pl
swiebodzin.pl
swinoujscie.pl
swiss
sx
sx.cn
sy
sydney
sykkylven.no
syncloud.it
synology.me
systems
sytes.net
sz
szczecin.pl
szczytno.pl
szex.hu
szkola.pl
t.bg
t.se
t3.storage.dev
t3.storageapi.dev
ta.it
taa.it
tab
tabayama.yamanashi.jp
tabitorder.co.il
tabuse.yamaguchi.jp
tachiarai.fukuoka.jp
tachikawa.tokyo.jp
tadaoka.osaka.jp
tado.mie.jp
tadotsu.kagawa.jp
tagajo.miyagi.jp
tagami.niigata.jp
tagawa.fukuoka.jp
tahara.aichi.jp
taifun-dns.de
taiji.wakayama.jp
taiki.hokkaido.jp
taiki.mie.jp
tainai.niigata.jp
taipei
taira.toyama.jp
taishi.hyogo.jp
taishi.osaka.jp
taishin.fukushima.jp
taito.tokyo.jp
taiwa.miyagi.jp
tajimi.gifu.jp
tajiri.osaka.jp
taka.hyogo.jp
takagi.nagano.jp
takahagi.ibaraki.jp
takahama.aichi.jp`.split("\n").filter(Boolean);
