// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_04_05 = `kameyama.mie.jp
kami.kochi.jp
kami.miyagi.jp
kamiamakusa.kumamoto.jp
kamifurano.hokkaido.jp
kamigori.hyogo.jp
kamiichi.toyama.jp
kamiizumi.saitama.jp
kamijima.ehime.jp
kamikawa.hokkaido.jp
kamikawa.hyogo.jp
kamikawa.saitama.jp
kamikitayama.nara.jp
kamikoani.akita.jp
kamimine.saga.jp
kaminokawa.tochigi.jp
kaminoyama.yamagata.jp
kamioka.akita.jp
kamisato.saitama.jp
kamishihoro.hokkaido.jp
kamisu.ibaraki.jp
kamisunagawa.hokkaido.jp
kamitonda.wakayama.jp
kamitsue.oita.jp
kamo.kyoto.jp
kamo.niigata.jp
kamoenai.hokkaido.jp
kamogawa.chiba.jp
kanagawa.jp
kanan.osaka.jp
kanazawa.ishikawa.jp
kanegasaki.iwate.jp
kaneyama.fukushima.jp
kaneyama.yamagata.jp
kani.gifu.jp
kanie.aichi.jp
kanmaki.nara.jp
kanna.gunma.jp
kannami.shizuoka.jp
kanonji.kagawa.jp
kanoya.kagoshima.jp
kanra.gunma.jp
kanuma.tochigi.jp
kanzaki.saga.jp
kapsi.fi
karacol.su
karaganda.su
karasjohka.no
karasjok.no
karasuyama.tochigi.jp
karatsu.saga.jp
karelia.su
kariwa.niigata.jp
kariya.aichi.jp
karlsoy.no
karmoy.no
karpacz.pl
kartuzy.pl
karuizawa.nagano.jp
karumai.iwate.jp
kasahara.gifu.jp
kasai.hyogo.jp
kasama.ibaraki.jp
kasamatsu.gifu.jp
kasaoka.okayama.jp
kashiba.nara.jp
kashihara.nara.jp
kashima.ibaraki.jp
kashima.saga.jp
kashiwa.chiba.jp
kashiwara.osaka.jp
kashiwazaki.niigata.jp
kasserver.com
kasuga.fukuoka.jp
kasuga.hyogo.jp
kasugai.aichi.jp
kasukabe.saitama.jp
kasumigaura.ibaraki.jp
kasuya.fukuoka.jp
kaszuby.pl
katagami.akita.jp
katano.osaka.jp
katashina.gunma.jp
katori.chiba.jp
katowice.pl
katsuragi.nara.jp
katsuragi.wakayama.jp
katsushika.tokyo.jp
katsuura.chiba.jp
katsuyama.fukui.jp
kaufen
kautokeino.no
kawaba.gunma.jp
kawachinagano.osaka.jp
kawagoe.mie.jp
kawagoe.saitama.jp
kawaguchi.saitama.jp
kawahara.tottori.jp
kawai.iwate.jp
kawai.nara.jp
kawaiishop.jp
kawajima.saitama.jp
kawakami.nagano.jp
kawakami.nara.jp
kawakita.ishikawa.jp
kawamata.fukushima.jp
kawaminami.miyazaki.jp
kawanabe.kagoshima.jp
kawanehon.shizuoka.jp
kawanishi.hyogo.jp
kawanishi.nara.jp
kawanishi.yamagata.jp
kawara.fukuoka.jp
kawasaki.miyagi.jp
kawatana.nagasaki.jp
kawaue.gifu.jp
kawazu.shizuoka.jp
kayabe.hokkaido.jp
kazimierz-dolny.pl
kazo.saitama.jp
kazuno.akita.jp
kddi
kdns.fr
ke
keenetic.io
keenetic.link
keenetic.name
keenetic.pro
keisen.fukuoka.jp
keliweb.cloud
kembuchi.hokkaido.jp
kep.tr
kepno.pl
kerryhotels
kerryproperties
ketrzyn.pl
keymachine.de
keyport.wa.us
keyword-on.net
kfh
kg
kg.kr
kh
kh.ua
khakassia.su
khanhhoa.vn
kharkiv.ua
kharkov.ua
kherson.ua
khmelnitskiy.ua
khmelnytskyi.ua
khplay.nl
khsj.cn
ki
kia
kibichuo.okayama.jp
kicks-ass.net
kicks-ass.org
kids
kiengiang.vn`.split("\n").filter(Boolean);
