// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_04_06 = `kiev.ua
kiho.mie.jp
kihoku.ehime.jp
kijo.miyazaki.jp
kikirara.jp
kikonai.hokkaido.jp
kikuchi.kumamoto.jp
kikugawa.shizuoka.jp
kill.jp
kilo.jp
kiloapps.ai
kiloapps.io
kim
kim.replit.dev
kimino.wakayama.jp
kimitsu.chiba.jp
kimobetsu.hokkaido.jp
kin.okinawa.jp
kindle
kinghost.net
kingston.wa.us
kinko.kagoshima.jp
kinokawa.wakayama.jp
kira.aichi.jp
kira.replit.dev
kirara.st
kirk.replit.dev
kirkenes.no
kirovograd.ua
kiryu.gunma.jp
kisarazu.chiba.jp
kishiwada.osaka.jp
kiso.nagano.jp
kisofukushima.nagano.jp
kisosaki.mie.jp
kita.kyoto.jp
kita.osaka.jp
kita.tokyo.jp
kitaaiki.nagano.jp
kitaakita.akita.jp
kitadaito.okinawa.jp
kitagata.gifu.jp
kitagata.saga.jp
kitagawa.kochi.jp
kitagawa.miyazaki.jp
kitahata.saga.jp
kitahiroshima.hokkaido.jp
kitakami.iwate.jp
kitakata.fukushima.jp
kitakata.miyazaki.jp
kitami.hokkaido.jp
kitamoto.saitama.jp
kitanakagusuku.okinawa.jp
kitashiobara.fukushima.jp
kitaura.miyazaki.jp
kitayama.wakayama.jp
kitchen
kiwa.mie.jp
kiwi
kiwi.nz
kiyama.saga.jp
kiyokawa.kanagawa.jp
kiyosato.hokkaido.jp
kiyose.tokyo.jp
kiyosu.aichi.jp
kizu.kyoto.jp
klabu.no
klepp.no
klodzko.pl
km
km.ua
kmpsp.gov.pl
kn
knightpoint.systems
knowsitall.info
knx-server.net
kobayashi.miyazaki.jp
kobierzyce.pl
kochi.jp
kochi.kochi.jp
kodaira.tokyo.jp
koeln
kofu.yamanashi.jp
koga.fukuoka.jp
koga.ibaraki.jp
koganei.tokyo.jp
koge.tottori.jp
koka.shiga.jp
kokonoe.oita.jp
kokubunji.tokyo.jp
kolobrzeg.pl
komae.tokyo.jp
komagane.nagano.jp
komaki.aichi.jp
komatsu
komatsu.ishikawa.jp
komatsushima.tokushima.jp
komforb.se
kommunalforbund.se
kommune.no
komono.mie.jp
komoro.nagano.jp
komvux.se
konan.aichi.jp
konan.shiga.jp
kongsberg.no
kongsvinger.no
konin.pl
konskowola.pl
konsulat.gov.pl
kontum.vn
konyvelo.hu
koobin.events
koori.fukushima.jp
kop.id
kopervik.no
koriyama.fukushima.jp
koryo.nara.jp
kosai.shizuoka.jp
kosaka.akita.jp
kosei.shiga.jp
kosher
koshigaya.saitama.jp
koshimizu.hokkaido.jp
koshu.yamanashi.jp
kosuge.yamanashi.jp
kota.aichi.jp
koto.shiga.jp
koto.tokyo.jp
kotohira.kagawa.jp
kotoura.tottori.jp
kouhoku.saga.jp
kounosu.saitama.jp
kouyama.kagoshima.jp
kouzushima.tokyo.jp
koya.wakayama.jp
koza.wakayama.jp
kozagawa.wakayama.jp
kozaki.chiba.jp
kozow.com
kp
kpmg
kpn
kppsp.gov.pl
kr
kr.eu.org
kr.it
kr.ua
kraanghke.no
kragero.no
krakow.pl
krasnik.pl
krasnodar.su
krd
kred
krellian.net
kristiansand.no
kristiansund.no
krodsherad.no
krokstadelva.no`.split("\n").filter(Boolean);
