// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_03_01 = `emrnotebooks-prod.eu-south-2.amazonaws.com
emrnotebooks-prod.eu-west-1.amazonaws.com
emrnotebooks-prod.eu-west-2.amazonaws.com
emrnotebooks-prod.eu-west-3.amazonaws.com
emrnotebooks-prod.il-central-1.amazonaws.com
emrnotebooks-prod.me-central-1.amazonaws.com
emrnotebooks-prod.me-south-1.amazonaws.com
emrnotebooks-prod.sa-east-1.amazonaws.com
emrnotebooks-prod.us-east-1.amazonaws.com
emrnotebooks-prod.us-east-2.amazonaws.com
emrnotebooks-prod.us-gov-east-1.amazonaws.com
emrnotebooks-prod.us-gov-west-1.amazonaws.com
emrnotebooks-prod.us-west-1.amazonaws.com
emrnotebooks-prod.us-west-2.amazonaws.com
emrstudio-prod.af-south-1.amazonaws.com
emrstudio-prod.ap-east-1.amazonaws.com
emrstudio-prod.ap-northeast-1.amazonaws.com
emrstudio-prod.ap-northeast-2.amazonaws.com
emrstudio-prod.ap-northeast-3.amazonaws.com
emrstudio-prod.ap-south-1.amazonaws.com
emrstudio-prod.ap-south-2.amazonaws.com
emrstudio-prod.ap-southeast-1.amazonaws.com
emrstudio-prod.ap-southeast-2.amazonaws.com
emrstudio-prod.ap-southeast-3.amazonaws.com
emrstudio-prod.ap-southeast-4.amazonaws.com
emrstudio-prod.ca-central-1.amazonaws.com
emrstudio-prod.ca-west-1.amazonaws.com
emrstudio-prod.cn-north-1.amazonaws.com.cn
emrstudio-prod.cn-northwest-1.amazonaws.com.cn
emrstudio-prod.eu-central-1.amazonaws.com
emrstudio-prod.eu-central-2.amazonaws.com
emrstudio-prod.eu-north-1.amazonaws.com
emrstudio-prod.eu-south-1.amazonaws.com
emrstudio-prod.eu-south-2.amazonaws.com
emrstudio-prod.eu-west-1.amazonaws.com
emrstudio-prod.eu-west-2.amazonaws.com
emrstudio-prod.eu-west-3.amazonaws.com
emrstudio-prod.il-central-1.amazonaws.com
emrstudio-prod.me-central-1.amazonaws.com
emrstudio-prod.me-south-1.amazonaws.com
emrstudio-prod.sa-east-1.amazonaws.com
emrstudio-prod.us-east-1.amazonaws.com
emrstudio-prod.us-east-2.amazonaws.com
emrstudio-prod.us-gov-east-1.amazonaws.com
emrstudio-prod.us-gov-west-1.amazonaws.com
emrstudio-prod.us-west-1.amazonaws.com
emrstudio-prod.us-west-2.amazonaws.com
en.it
ena.gifu.jp
encoreapi.com
encr.app
endofinternet.net
endofinternet.org
endoftheinternet.org
enebakk.no
energy
enf.br
eng.br
eng.ec
eng.jo
eng.pro
engerdal.no
engine.aero
engineer
engineer.aero
engineering
eniwa.hokkaido.jp
enna.it
ens.tn
enscaled.sg
ent.platform.sh
enterprisecloud.nu
enterprises
entertainment.aero
epson
equipment
equipment.aero
er.in
ericsson
erimo.hokkaido.jp
erni
erotica.hu
erotika.hu
erp.dev
es
es-1.axarnet.cloud
es.eu.org
es.gov.br
es.kr
es.leg.br
esan.hokkaido.jp
esashi.hokkaido.jp
esm.ec
esp.br
esq
est-a-la-maison.com
est-a-la-masion.com
est-le-patron.com
est-mon-blogueur.com
est.pr
estate
et
etajima.hiroshima.jp
etc.br
eti.br
etne.no
etnedal.no
eu
eu-1.evennode.com
eu-2.evennode.com
eu-3.evennode.com
eu-4.evennode.com
eu-central-1.elasticbeanstalk.com
eu-north-1.elasticbeanstalk.com
eu-south-1.elasticbeanstalk.com
eu-south-2.elasticbeanstalk.com
eu-west-1.convex.cloud
eu-west-1.convex.site
eu-west-1.elasticbeanstalk.com
eu-west-2.elasticbeanstalk.com
eu-west-3.elasticbeanstalk.com
eu.cc
eu.com
eu.encoway.cloud
eu.int
eu.meteorapp.com
eu.ngrok.io
eu.org
eu.platform.sh
eu.pythonanywhere.com
eu1-plenit.com
eun.eg
eurodir.ru
eurovision
eus
evenassi.no
evenes.no
events
evje-og-hornnes.no
exchange
exchange.aero
exe.xyz
execute-api.af-south-1.amazonaws.com
execute-api.ap-east-1.amazonaws.com
execute-api.ap-northeast-1.amazonaws.com
execute-api.ap-northeast-2.amazonaws.com
execute-api.ap-northeast-3.amazonaws.com
execute-api.ap-south-1.amazonaws.com
execute-api.ap-south-2.amazonaws.com
execute-api.ap-southeast-1.amazonaws.com
execute-api.ap-southeast-2.amazonaws.com
execute-api.ap-southeast-3.amazonaws.com
execute-api.ap-southeast-4.amazonaws.com
execute-api.ap-southeast-5.amazonaws.com
execute-api.ca-central-1.amazonaws.com
execute-api.ca-west-1.amazonaws.com
execute-api.cn-north-1.amazonaws.com.cn
execute-api.cn-northwest-1.amazonaws.com.cn
execute-api.eu-central-1.amazonaws.com
execute-api.eu-central-2.amazonaws.com
execute-api.eu-north-1.amazonaws.com
execute-api.eu-south-1.amazonaws.com
execute-api.eu-south-2.amazonaws.com
execute-api.eu-west-1.amazonaws.com
execute-api.eu-west-2.amazonaws.com
execute-api.eu-west-3.amazonaws.com
execute-api.il-central-1.amazonaws.com
execute-api.me-central-1.amazonaws.com
execute-api.me-south-1.amazonaws.com
execute-api.sa-east-1.amazonaws.com
execute-api.us-east-1.amazonaws.com
execute-api.us-east-2.amazonaws.com
execute-api.us-gov-east-1.amazonaws.com
execute-api.us-gov-west-1.amazonaws.com
execute-api.us-west-1.amazonaws.com
execute-api.us-west-2.amazonaws.com
exnet.su
expert
experts-comptables.fr
expo.app
exposed
express
express.aero
extraspace
ezproxy.kuleuven.be
f.bg
f.se
f5.si
fage
fail
fairwinds
faith
fakefur.jp
fam.pk
family
familyds.com
familyds.net
familyds.org
fan
fans
fantasyleague.cc
far.br
farm
farmers
farsund.no
fashion
fashionstore.jp
fast
fastly-edge.com
fastly-terrarium.com
fastlylb.net
fastvps-server.com
fastvps.host
fastvps.site
fauske.no
fbx-os.fr
fbxos.fr
fc.it
fe.it
federation.aero
fedex
fedje.no
fedorainfracloud.org
fedorapeople.org
feedback
feedback.ac
feira.br
fem.jp
fentiger.mythic-beasts.com
fermo.it
ferrara.it
ferrari
ferrero
feste-ip.net
fet.no
fetsund.no
fg.it
fh-muenster.io
fh.se
fhs.no
fhsk.se
fhv.se
fi
fi.cloudplatform.fi
fi.cr
fi.eu.org
fi.it
fidelity
fido
fie.ee
figma-gov.site
figma.site
file.core.usgovcloudapi.net
file.core.windows.net
filegear-sg.me
filegear.me
film
film.hu
fin.ec
fin.in
fin.tn
final
finance
financial
finnoy.no
fire
firebaseapp.com
firenze.it
firestone
firewall-gateway.com
firewall-gateway.de
firewall-gateway.net
firewalledreplit.co
firm.dk
firm.ht
firm.in
firm.nf
firm.ng
firm.ro
firm.ve
firmdale
fish
fishing
fit
fitjar.no
fitness
fj
fj.cn
fjaler.no
fjell.no
fl.us
fla.no
flakstad.no
flatanger.no
fldrv.com
flekkefjord.no
flesberg.no
flickr
flier.jp
flight.aero
flights
flir
flog.br
flop.jp
floppy.jp
flora.no
florence.it
floripa.br
florist
floro.no
flowers
flt.cloud.muni.cz
flutterflow.app
fly
fly.dev
fm
fm.br
fm.it
fm.jo
fm.no
fnc.fr-par.scw.cloud
fnd.br
fo
foggia.it
folkebibl.no
folldal.no
foo
food
fool.jp
football
for-better.biz
for-more.biz
for-our.info
for-some.biz
for-the.biz
ford
forde.no
forex
forgeblocks.com
forgot.her.name
forgot.his.name
forks.wa.us
forli-cesena.it
forlicesena.it
forms.ac
forsale
forsand.no
fortal.br
forum
forum.hu
forumz.info
fosnes.no
fot.br
fot.ec
foundation
fox
foz.br
fr
fr-1.paas.massivegrid.net
fr-par-1.baremetal.scw.cloud
fr-par-2.baremetal.scw.cloud
fr.eu.org
fr.it
fra1-de.cloudjiffy.net
framer.ai
framer.app
framer.media
framer.photos
framer.website
framer.wiki
framercanvas.com
frana.no
fredrikstad.no
free
freebox-os.com
freebox-os.fr
freeboxos.com
freeboxos.fr
freeddns.org
freeddns.us
freedesktop.org
freemyip.com
freesite.host
freetls.fastly.net
freight.aero
frenchkiss.jp
fresenius
friuli-v-giulia.it
friuli-ve-giulia.it
friuli-vegiulia.it
friuli-venezia-giulia.it
friuli-veneziagiulia.it
friuli-vgiulia.it
friuliv-giulia.it
friulive-giulia.it
friulivegiulia.it
friulivenezia-giulia.it
friuliveneziagiulia.it
friulivgiulia.it
frl
frogans
frogn.no
froland.no
from-ak.com
from-al.com
from-ar.com
from-az.net
from-ca.com
from-co.net
from-ct.com
from-dc.com
from-de.com
from-fl.com
from-ga.com
from-hi.com
from-ia.com
from-id.com
from-il.com
from-in.com
from-ks.com
from-ky.com
from-la.net
from-ma.com
from-md.com
from-me.org
from-mi.com
from-mn.com
from-mo.com
from-ms.com
from-mt.com
from-nc.com
from-nd.com
from-ne.com
from-nh.com
from-nj.com
from-nm.com
from-nv.com
from-ny.net
from-oh.com
from-ok.com`.split("\n").filter(Boolean);
