// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_07_03 = `takahama.fukui.jp
takaharu.miyazaki.jp
takahashi.okayama.jp
takahata.yamagata.jp
takaishi.osaka.jp
takamatsu.kagawa.jp
takamori.kumamoto.jp
takamori.nagano.jp
takanabe.miyazaki.jp
takanezawa.tochigi.jp
takaoka.toyama.jp
takarazuka.hyogo.jp
takasago.hyogo.jp
takasaki.gunma.jp
takashima.shiga.jp
takasu.hokkaido.jp
takata.fukuoka.jp
takatori.nara.jp
takatsuki.osaka.jp
takatsuki.shiga.jp
takayama.gifu.jp
takayama.gunma.jp
takayama.nagano.jp
takazaki.miyazaki.jp
takehara.hiroshima.jp
taketa.oita.jp
taketomi.okinawa.jp
taki.mie.jp
takikawa.hokkaido.jp
takino.hyogo.jp
takinoue.hokkaido.jp
takko.aomori.jp
tako.chiba.jp
taku.saga.jp
talk
tama.tokyo.jp
tamakawa.fukushima.jp
tamaki.mie.jp
tamamura.gunma.jp
tamano.okayama.jp
tamatsukuri.ibaraki.jp
tamayu.shimane.jp
tamba.hyogo.jp
tana.no
tanabe.kyoto.jp
tanabe.wakayama.jp
tanagura.fukushima.jp
tananger.no
tank.jp
tanohata.iwate.jp
taobao
tara.saga.jp
tarama.okinawa.jp
taranto.it
target
targi.pl
tarnobrzeg.pl
tarpit.replit.dev
tarui.gifu.jp
tarumizu.kagoshima.jp
tas.au
tas.edu.au
tas.gov.au
tashkent.su
tatamotors
tatar
tatebayashi.gunma.jp
tateshina.nagano.jp
tateyama.chiba.jp
tateyama.toyama.jp
tatsuno.hyogo.jp
tatsuno.nagano.jp
tattoo
taveusercontent.com
tawaramoto.nara.jp
tax
taxi
taxi.aero
taxi.br
tayninh.vn
tc
tc.br
tche.br
tci
tcp4.me
td
tdk
te.it
te.ua
teaches-yoga.com
team
teams.replit.dev
tec.br
tec.mi.us
tec.ve
tech
tech.ec
tech.orange
technology
tecnologia.bo
tel
tel.tr
telebit.app
telebit.io
teleport.sh
temasek
temp-dns.com
tempio-olbia.it
tempioolbia.it
tempurl.host
tendo.yamagata.jp
tenei.fukushima.jp
tenkawa.nara.jp
tennis
tenri.nara.jp
teo.br
teramo.it
termez.su
terni.it
ternopil.ua
teshikaga.hokkaido.jp
test-iserv.de
test.tj
tests.cx
teva
tf
tg
tgory.pl
th
thaibinh.vn
thainguyen.vn
thanhhoa.vn
thanhphohochiminh.vn
thd
the.br
theater
theatre
theshop.jp
theworkpc.com
thick.jp
thingdustdata.com
thruhere.net
thuathienhue.vn
tiaa
tickets
tickets.io
tienda
tiengiang.vn
time.no
tingvoll.no
tinn.no
tips
tires
tirol
tj
tj.cn
tjeldsund.no
tjielte.no
tjmaxx
tjome.no
tjx
tk
tkmaxx
tksat.bo
tl
tlon.network
tm
tm.cy
tm.dz
tm.fr
tm.hu
tm.km
tm.mc
tm.no
tm.pl
tm.ro
tm.se
tm.za
tmall
tmp.br
tn
tn.it
tn.oxa.cloud
tn.us
tnx.ge
to
to.gov.br
to.it
to.leg.br
toba.mie.jp
tobe.ehime.jp
tobetsu.hokkaido.jp
tobishima.aichi.jp
tochigi.jp
tochigi.tochigi.jp
tochio.niigata.jp
toda.saitama.jp
today
toei.aichi.jp
toga.toyama.jp
togakushi.nagano.jp
togane.chiba.jp
togitsu.nagasaki.jp
togliatti.su
togo.aichi.jp
togura.nagano.jp
tohma.hokkaido.jp
tohnosho.chiba.jp
toho.fukuoka.jp
tokai.aichi.jp
tokai.ibaraki.jp
tokamachi.niigata.jp
tokashiki.okinawa.jp
toki.gifu.jp
tokigawa.saitama.jp
tokke.no
tokoname.aichi.jp
tokorozawa.saitama.jp
tokushima.jp
tokushima.tokushima.jp
tokuyama.yamaguchi.jp
tokyo
tokyo.jp
tolga.no
tomakomai.hokkaido.jp
tomari.hokkaido.jp
tome.miyagi.jp
tomi.nagano.jp
tomigusuku.okinawa.jp
tomika.gifu.jp
tomioka.gunma.jp
tomisato.chiba.jp
tomiya.miyagi.jp
tomobe.ibaraki.jp
tonaki.okinawa.jp
tonami.toyama.jp
tondabayashi.osaka.jp
tone.ibaraki.jp
tonkotsu.jp
tono.iwate.jp
tonosho.kagawa.jp
tonsberg.no
toolforge.org
tools
toon.ehime.jp
top
topaz.ne.jp
torahime.shiga.jp
toray
toride.ibaraki.jp
torino.it
torproject.net
torsken.no
torun.pl
tos.it
tosa.kochi.jp
tosashimizu.kochi.jp
toscana.it
toshiba
toshima.tokyo.jp
tosu.saga.jp
total
tottori.jp
tottori.tottori.jp
tourism.bj
tourism.pl
tourism.tn
tours
towada.aomori.jp
town
townnews-staging.com
toya.hokkaido.jp
toyako.hokkaido.jp
toyama.jp
toyama.toyama.jp
toyo.kochi.jp
toyoake.aichi.jp
toyohashi.aichi.jp
toyokawa.aichi.jp
toyonaka.osaka.jp
toyone.aichi.jp
toyono.osaka.jp
toyooka.hyogo.jp
toyosato.shiga.jp
toyota
toyota.aichi.jp
toyota.yamaguchi.jp
toyotomi.hokkaido.jp
toyotsu.fukuoka.jp
toyoura.hokkaido.jp
toys
tozawa.yamagata.jp
tozsde.hu
tp.it
tr
tr.eu.org
tr.it
tr.no
tra.kp
trade
trader.aero
trading
trading.aero
traeumtgerade.de
trafficmanager.net
trafficplex.cloud
trainer.aero
training
trana.no
tranby.no
trani-andria-barletta.it
trani-barletta-andria.it
traniandriabarletta.it
tranibarlettaandria.it
tranoy.no
transfer-webapp-fips.us-gov-east-1.on.aws
transfer-webapp-fips.us-gov-west-1.on.aws
transfer-webapp.af-south-1.on.aws
transfer-webapp.ap-east-1.on.aws
transfer-webapp.ap-northeast-1.on.aws
transfer-webapp.ap-northeast-2.on.aws
transfer-webapp.ap-northeast-3.on.aws
transfer-webapp.ap-south-1.on.aws
transfer-webapp.ap-south-2.on.aws
transfer-webapp.ap-southeast-1.on.aws
transfer-webapp.ap-southeast-2.on.aws
transfer-webapp.ap-southeast-3.on.aws
transfer-webapp.ap-southeast-4.on.aws
transfer-webapp.ap-southeast-5.on.aws
transfer-webapp.ap-southeast-7.on.aws
transfer-webapp.ca-central-1.on.aws
transfer-webapp.ca-west-1.on.aws
transfer-webapp.cn-north-1.on.amazonwebservices.com.cn
transfer-webapp.cn-northwest-1.on.amazonwebservices.com.cn
transfer-webapp.eu-central-1.on.aws
transfer-webapp.eu-central-2.on.aws
transfer-webapp.eu-north-1.on.aws
transfer-webapp.eu-south-1.on.aws
transfer-webapp.eu-south-2.on.aws
transfer-webapp.eu-west-1.on.aws
transfer-webapp.eu-west-2.on.aws
transfer-webapp.eu-west-3.on.aws
transfer-webapp.il-central-1.on.aws
transfer-webapp.me-central-1.on.aws
transfer-webapp.me-south-1.on.aws
transfer-webapp.mx-central-1.on.aws
transfer-webapp.sa-east-1.on.aws
transfer-webapp.us-east-1.on.aws
transfer-webapp.us-east-2.on.aws
transfer-webapp.us-gov-east-1.on.aws
transfer-webapp.us-gov-west-1.on.aws
transfer-webapp.us-west-1.on.aws
transfer-webapp.us-west-2.on.aws
translate.goog
transporte.bo
trapani.it
travel
travel.in
travel.pl
travelers
travelersinsurance
travinh.vn
trd.br
trentin-sud-tirol.it
trentin-sudtirol.it
trentin-sued-tirol.it
trentin-suedtirol.it
trentino-a-adige.it
trentino-aadige.it
trentino-alto-adige.it
trentino-altoadige.it
trentino-s-tirol.it
trentino-stirol.it
trentino-sud-tirol.it
trentino-sudtirol.it
trentino-sued-tirol.it
trentino-suedtirol.it
trentino.it
trentinoa-adige.it
trentinoaadige.it
trentinoalto-adige.it
trentinoaltoadige.it
trentinos-tirol.it
trentinostirol.it
trentinosud-tirol.it
trentinosued-tirol.it
trentinosuedtirol.it
trentinsud-tirol.it
trentinsudtirol.it
trentinsued-tirol.it
trentinsuedtirol.it
trento.it
treviso.it
trieste.it
troandin.no
trogstad.no
troitsk.su
tromsa.no
tromso.no
trondheim.no
trust
trv
try-snowplow.com
trycloudflare.com
trysil.no
ts.it
ts.net
tselinograd.su
tsk.tr
tsu.mie.jp
tsubame.niigata.jp
tsubata.ishikawa.jp
tsubetsu.hokkaido.jp`.split("\n").filter(Boolean);
