// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_08_02 = `webview-assets.aws-cloud9.af-south-1.amazonaws.com
webview-assets.aws-cloud9.ap-east-1.amazonaws.com
webview-assets.aws-cloud9.ap-northeast-1.amazonaws.com
webview-assets.aws-cloud9.ap-northeast-2.amazonaws.com
webview-assets.aws-cloud9.ap-northeast-3.amazonaws.com
webview-assets.aws-cloud9.ap-south-1.amazonaws.com
webview-assets.aws-cloud9.ap-southeast-1.amazonaws.com
webview-assets.aws-cloud9.ap-southeast-2.amazonaws.com
webview-assets.aws-cloud9.ca-central-1.amazonaws.com
webview-assets.aws-cloud9.eu-central-1.amazonaws.com
webview-assets.aws-cloud9.eu-north-1.amazonaws.com
webview-assets.aws-cloud9.eu-south-1.amazonaws.com
webview-assets.aws-cloud9.eu-west-1.amazonaws.com
webview-assets.aws-cloud9.eu-west-2.amazonaws.com
webview-assets.aws-cloud9.eu-west-3.amazonaws.com
webview-assets.aws-cloud9.il-central-1.amazonaws.com
webview-assets.aws-cloud9.me-south-1.amazonaws.com
webview-assets.aws-cloud9.sa-east-1.amazonaws.com
webview-assets.aws-cloud9.us-east-1.amazonaws.com
webview-assets.aws-cloud9.us-east-2.amazonaws.com
webview-assets.aws-cloud9.us-west-1.amazonaws.com
webview-assets.aws-cloud9.us-west-2.amazonaws.com
webview-assets.cloud9.af-south-1.amazonaws.com
webview-assets.cloud9.ap-east-1.amazonaws.com
webview-assets.cloud9.ap-northeast-1.amazonaws.com
webview-assets.cloud9.ap-northeast-2.amazonaws.com
webview-assets.cloud9.ap-northeast-3.amazonaws.com
webview-assets.cloud9.ap-south-1.amazonaws.com
webview-assets.cloud9.ap-southeast-1.amazonaws.com
webview-assets.cloud9.ap-southeast-2.amazonaws.com
webview-assets.cloud9.ca-central-1.amazonaws.com
webview-assets.cloud9.eu-central-1.amazonaws.com
webview-assets.cloud9.eu-north-1.amazonaws.com
webview-assets.cloud9.eu-south-1.amazonaws.com
webview-assets.cloud9.eu-west-1.amazonaws.com
webview-assets.cloud9.eu-west-2.amazonaws.com
webview-assets.cloud9.eu-west-3.amazonaws.com
webview-assets.cloud9.me-south-1.amazonaws.com
webview-assets.cloud9.sa-east-1.amazonaws.com
webview-assets.cloud9.us-east-1.amazonaws.com
webview-assets.cloud9.us-east-2.amazonaws.com
webview-assets.cloud9.us-west-1.amazonaws.com
webview-assets.cloud9.us-west-2.amazonaws.com
wed
wedding
weeklylottery.org.uk
wegrow.pl
weibo
weir
wesley.replit.dev
west1-us.cloudjiffy.net
westeurope.azurestaticapps.net
westus2.azurestaticapps.net
wf
whitesnow.jp
whm.fr-par.scw.cloud
whm.nl-ams.scw.cloud
whoswho
wi.us
wielun.pl
wien
wien.funkfeuer.at
wif.gov.pl
wiih.gov.pl
wiki
wiki.bo
wiki.br
williamhill
win
winb.gov.pl
windows
windsurf.app
windsurf.build
wine
winners
wios.gov.pl
wiredbladehosting.com
witd.gov.pl
with.playit.plus
withgoogle.com
withyoutube.com
wiw.gov.pl
wix.run
wixsite.com
wixstudio.com
wixstudio.io
wjg.jp
wkz.gov.pl
wlocl.pl
wloclawek.pl
wmcloud.org
wme
wmflabs.org
wnext.app
wodzislaw.pl
wolomin.pl
woltlab-demo.com
woodside
worf.replit.dev
work
workers.dev
workinggroup.aero
workisboring.com
works
works.aero
world
worse-than.tv
wow
wp2.host
wpdevcloud.com
wpenginepowered.com
wphostedmail.com
wpmucdn.com
wpmudev.host
wpsquared.site
writesthisblog.com
wroc.pl
wroclaw.pl
ws
wsa.gov.pl
wskr.gov.pl
wsse.gov.pl
wtc
wtf
wuoz.gov.pl
wv.us
www.ro
wy.us
wzmiuw.gov.pl
x.bg
x.mythic-beasts.com
x.se
x0.com
x0.to
x443.pw
xbox
xen.prgmr.com
xerox
xihuan
xii.jp
xin
xj.cn
xmit.dev
xn--0trq7p7nn.jp
xn--11b4c3d
xn--12c1fe0br.xn--o3cw4h
xn--12cfi8ixb8l.xn--o3cw4h
xn--12co0c3b4eva.xn--o3cw4h
xn--1ck2e1b
xn--1ctwo.jp
xn--1lqs03n.jp
xn--1lqs71d.jp
xn--1qqw23a
xn--2m4a15e.jp
xn--2scrj9c
xn--30rr7y
xn--32vp30h.jp
xn--3bst00m
xn--3ds443g
xn--3e0b707e
xn--3hcrj9c
xn--3pxu8k
xn--41a.xn--p1acf
xn--42c2d9a
xn--45br5cyl
xn--45brj9c
xn--45q11c
xn--4dbgdty6c.xn--4dbrk0ce
xn--4dbrk0ce
xn--4gbrim
xn--4it168d.jp
xn--4it797k.jp
xn--4pvxs.jp
xn--54b7fta0cc
xn--55qw42g
xn--55qx5d
xn--55qx5d.cn
xn--55qx5d.hk
xn--55qx5d.xn--j6w193g
xn--5dbhl8d.xn--4dbrk0ce
xn--5js045d.jp
xn--5rtp49c.jp
xn--5rtq34k.jp
xn--5su34j936bgsg
xn--5tzm5g
xn--6btw5a.jp
xn--6frz82g
xn--6orx2r.jp
xn--6qq986b3xl
xn--7t0a264c.jp
xn--80aaa0cvac.xn--p1acf
xn--80adxhks
xn--80ao21a
xn--80aqecdr1a
xn--80asehdb
xn--80aswg
xn--80au.xn--90a3ac
xn--8dbq2a.xn--4dbrk0ce
xn--8ltr62k.jp
xn--8pvr4u.jp
xn--8y0a063a
xn--90a1af.xn--p1acf
xn--90a3ac
xn--90ae
xn--90ais
xn--90amc.xn--p1acf
xn--90azh.xn--90a3ac
xn--9dbq2a
xn--9et52u
xn--9krt00a
xn--9tfky.id
xn--andy-ira.no
xn--aroport-bya.ci
xn--asky-ira.no
xn--aurskog-hland-jnb.no
xn--avery-yua.no
xn--b-5ga.nordland.no
xn--b-5ga.telemark.no
xn--b4w605ferd
xn--balsan-sdtirol-nsb.it
xn--bck1b9a5dre4c
xn--bdddj-mrabd.no
xn--bearalvhki-y4a.no
xn--berlevg-jxa.no
xn--bhcavuotna-s4a.no
xn--bhccavuotna-k7a.no
xn--bidr-5nac.no
xn--bievt-0qa.no
xn--bjddar-pta.no
xn--blt-elab.no
xn--bmlo-gra.no
xn--bod-2na.no
xn--bozen-sdtirol-2ob.it
xn--brnny-wuac.no
xn--brnnysund-m8ac.no
xn--brum-voa.no
xn--btsfjord-9za.no
xn--bulsan-sdtirol-nsb.it
xn--c1avg
xn--c1avg.xn--90a3ac
xn--c1avg.xn--p1acf
xn--c2br7g
xn--c3s14m.jp
xn--cck2b3b
xn--cckwcxetd
xn--cesena-forl-mcb.it
xn--cesenaforl-i8a.it
xn--cg4bki
xn--ciqpn.hk
xn--clchc0ea0b2g2a9gcd
xn--czr694b
xn--czrs0t
xn--czru2d
xn--d1acj3b
xn--d1alf
xn--d1at.xn--90a3ac
xn--d5qv7z876c.jp
xn--davvenjrga-y4a.no
xn--djrs72d6uy.jp
xn--djty4k.jp
xn--dnna-gra.no
xn--drbak-wua.no
xn--dyry-ira.no
xn--e1a4c
xn--eckvdtc9d
xn--efvn9s.jp
xn--efvy88h
xn--ehqz56n.jp
xn--elqq16h.jp
xn--eveni-0qa01ga.no
xn--f6qx53a.jp
xn--fct429k
xn--fhbei
xn--finny-yua.no
xn--fiq228c5hs
xn--fiq64b
xn--fiqs8s
xn--fiqz9s
xn--fjord-lra.no
xn--fjq720a
xn--fl-zia.no
xn--flor-jra.no
xn--flw351e
xn--forl-cesena-fcb.it
xn--forlcesena-c8a.it
xn--fpcrj9c3d
xn--frde-gra.no
xn--frna-woa.no
xn--frya-hra.no
xn--fzc2c9e2c
xn--fzys8d69uvgm
xn--g2xx48c
xn--gckr3f0f
xn--gecrj9c
xn--ggaviika-8ya47h.no
xn--gildeskl-g0a.no
xn--givuotna-8ya.no
xn--gjvik-wua.no
xn--gk3at1e
xn--gls-elac.no
xn--gmq050i.hk
xn--gmqw5a.hk
xn--gmqw5a.xn--j6w193g
xn--gnstigbestellen-zvb.de
xn--gnstigliefern-wob.de
xn--h-2fa.no
xn--h1ahn.xn--p1acf
xn--h1aliz.xn--p1acf
xn--h2breg3eve
xn--h2brj9c
xn--h2brj9c8c
xn--h3cuzk1di.xn--o3cw4h
xn--hamary-fya.no
xn--hbmer-xqa.no
xn--hcesuolo-7ya35b.no
xn--hebda8b.xn--4dbrk0ce
xn--hery-ira.nordland.no
xn--hery-ira.xn--mre-og-romsdal-qqb.no
xn--hgebostad-g3a.no
xn--hkkinen-5wa.fi
xn--hmmrfeasta-s4ac.no
xn--hnefoss-q1a.no
xn--hobl-ira.no
xn--holtlen-hxa.no
xn--hpmir-xqa.no
xn--hxt814e
xn--hyanger-q1a.no
xn--hylandet-54a.no
xn--i1b6b1a6a2e
xn--imr513n
xn--indery-fya.no
xn--io0a7i
xn--io0a7i.cn
xn--io0a7i.hk
xn--j1adp.xn--p1acf
xn--j1aef
xn--j1aef.xn--p1acf
xn--j1ael8b.xn--p1acf
xn--j1amh
xn--j6w193g
xn--jlq480n2rg`.split("\n").filter(Boolean);
