// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_03_06 = `hakuba.nagano.jp
hakui.ishikawa.jp
hakusan.ishikawa.jp
halden.no
half.host
halfmoon.jp
halsa.no
ham-radio-op.net
hamada.shimane.jp
hamamatsu.shizuoka.jp
hamar.no
hamaroy.no
hamatama.saga.jp
hamatonbetsu.hokkaido.jp
hamburg
hammarfeasta.no
hammerfest.no
hamura.tokyo.jp
hanam.vn
hanamaki.iwate.jp
hanamigawa.chiba.jp
hanawa.fukushima.jp
handa.aichi.jp
handcrafted.jp
hanggliding.aero
hangout
hannan.osaka.jp
hanno.saitama.jp
hanoi.vn
hanyu.saitama.jp
hapmir.no
happou.akita.jp
hara.nagano.jp
haram.no
hareid.no
harima.hyogo.jp
harstad.no
hasama.oita.jp
hasami.nagasaki.jp
hashbang.sh
hashikami.aomori.jp
hashima.gifu.jp
hashimoto.wakayama.jp
hasuda.saitama.jp
hasura-app.io
hasura.app
hasvik.no
hateblo.jp
hatenablog.com
hatenablog.jp
hatenadiary.com
hatenadiary.jp
hatenadiary.org
hatinh.vn
hatogaya.saitama.jp
hatoyama.saitama.jp
hatsukaichi.hiroshima.jp
hattfjelldal.no
haugesund.no
haugiang.vn
haus
hayakawa.yamanashi.jp
hayashima.okayama.jp
hazu.aichi.jp
hb.cldmail.ru
hb.cn
hbo
hdfc
hdfcbank
he.cn
health
health-carereform.com
health.nz
health.vn
healthcare
heavy.jp
heguri.nara.jp
heimdns.de
heimdns.online
heiyu.space
hekinan.aichi.jp
helioho.st
heliohost.us
help
helsinki
hemne.no
hemnes.no
hemsedal.no
hepforge.org
her.jp
herad.no
hercules-app.com
hercules-dev.com
here
here-for-more.info
hermes
herokuapp.com
heroy.more-og-romsdal.no
heroy.nordland.no
heteml.net
heyflow.page
heyflow.site
hf.space
hi.cn
hi.us
hicam.net
hichiso.gifu.jp
hida.gifu.jp
hidaka.hokkaido.jp
hidaka.kochi.jp
hidaka.saitama.jp
hidaka.wakayama.jp
hidns.co
hidns.vip
higashi.fukuoka.jp
higashi.fukushima.jp
higashi.okinawa.jp
higashiagatsuma.gunma.jp
higashichichibu.saitama.jp
higashihiroshima.hiroshima.jp
higashiizu.shizuoka.jp
higashiizumo.shimane.jp
higashikagawa.kagawa.jp
higashikagura.hokkaido.jp
higashikawa.hokkaido.jp
higashikurume.tokyo.jp
higashimatsushima.miyagi.jp
higashimatsuyama.saitama.jp
higashimurayama.tokyo.jp
higashinaruse.akita.jp
higashine.yamagata.jp
higashiomi.shiga.jp
higashiosaka.osaka.jp
higashishirakawa.gifu.jp
higashisumiyoshi.osaka.jp
higashitsuno.kochi.jp
higashiura.aichi.jp
higashiyama.kyoto.jp
higashiyamato.tokyo.jp
higashiyodogawa.osaka.jp`.split("\n").filter(Boolean);
