// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_08_03 = `xn--jlster-bya.no
xn--jrpeland-54a.no
xn--jvr189m
xn--k7yn95e.jp
xn--karlsy-fya.no
xn--karmy-yua.no
xn--kbrq7o.jp
xn--kcrx77d1x4a
xn--kfjord-iua.no
xn--klbu-woa.no
xn--klt787d.jp
xn--kltp7d.jp
xn--kltx9a.jp
xn--klty5x.jp
xn--koluokta-7ya57h.no
xn--kprw13d
xn--kpry57d
xn--kput3i
xn--krager-gya.no
xn--kranghke-b0a.no
xn--krdsherad-m8a.no
xn--krehamn-dxa.no
xn--krjohka-hwab49j.no
xn--ksnes-uua.no
xn--kvfjord-nxa.no
xn--kvitsy-fya.no
xn--kvnangen-k0a.no
xn--l-1fa.no
xn--l1acc
xn--laheadju-7ya.no
xn--langevg-jxa.no
xn--lcvr32d.hk
xn--ldingen-q1a.no
xn--leagaviika-52b.no
xn--lesund-hua.no
xn--lgbbat1ad8j
xn--lgrd-poac.no
xn--lhppi-xqa.no
xn--linds-pra.no
xn--loabt-0qa.no
xn--lrdal-sra.no
xn--lrenskog-54a.no
xn--lt-liac.no
xn--lten-gra.no
xn--lury-ira.no
xn--m3ch0j3a.xn--o3cw4h
xn--mely-ira.no
xn--merker-kua.no
xn--mgb2ddes
xn--mgb9awbf
xn--mgba3a3ejt
xn--mgba3a4f16a
xn--mgba3a4f16a.ir
xn--mgba3a4fra
xn--mgba3a4fra.ir
xn--mgba7c0bbn0a
xn--mgbaam7a8h
xn--mgbab2bd
xn--mgbah1a3hjkrd
xn--mgbai9a5eva00b
xn--mgbai9azgqp6j
xn--mgbayh7gpa
xn--mgbbh1a
xn--mgbbh1a71e
xn--mgbc0a9azcg
xn--mgbca7dzdo
xn--mgbcpq6gpa1a
xn--mgberp4a5d4a87g
xn--mgberp4a5d4ar
xn--mgbgu82a
xn--mgbi4ecexp
xn--mgbpl2fh
xn--mgbqly7c0a67fbc
xn--mgbqly7cvafr
xn--mgbt3dhd
xn--mgbtf8fl
xn--mgbtx2b
xn--mgbx4cd0ab
xn--mix082f
xn--mix891f
xn--mjndalen-64a.no
xn--mk0axi.hk
xn--mk1bu44c
xn--mkru45i.jp
xn--mlatvuopmi-s4a.no
xn--mli-tla.no
xn--mlselv-iua.no
xn--moreke-jua.no
xn--mori-qsa.nz
xn--mosjen-eya.no
xn--mot-tla.no
xn--msy-ula0h.no
xn--mtta-vrjjat-k7af.no
xn--muost-0qa.no
xn--mxtq1m
xn--mxtq1m.hk
xn--mxtq1m.xn--j6w193g
xn--ngbc5azd
xn--ngbe9e0a
xn--ngbrx
xn--nit225k.jp
xn--nmesjevuemie-tcba.no
xn--nnx388a
xn--node
xn--nqv7f
xn--nqv7fs00ema
xn--nry-yla5g.no
xn--ntso0iqx3a.jp
xn--ntsq17g.jp
xn--nttery-byae.no
xn--nvuotna-hwa.no
xn--nyqy26a
xn--o1ac.xn--90a3ac
xn--o1ach.xn--90a3ac
xn--o3cw4h
xn--o3cyx2a.xn--o3cw4h
xn--od0alg.cn
xn--od0alg.hk
xn--od0alg.xn--j6w193g
xn--od0aq3b.hk
xn--ogbpf8fl
xn--oppegrd-ixa.no
xn--ostery-fya.no
xn--osyro-wua.no
xn--otu796d
xn--p1acf
xn--p1ai
xn--pgbs0dh
xn--porsgu-sta26f.no
xn--pssu33l.jp
xn--pssy2u
xn--q7ce6a
xn--q9jyb4c
xn--qcka1pmc
xn--qqqt11m.jp
xn--qxa6a
xn--qxam
xn--rady-ira.no
xn--rdal-poa.no
xn--rde-ula.no
xn--rdy-0nab.no
xn--rennesy-v1a.no
xn--rhkkervju-01af.no
xn--rholt-mra.no
xn--rhqv96g
xn--rht27z.jp
xn--rht3d.jp
xn--rht61e.jp
xn--risa-5na.no
xn--risr-ira.no
xn--rland-uua.no
xn--rlingen-mxa.no
xn--rmskog-bya.no
xn--rny31h.jp
xn--rovu88b
xn--rros-gra.no
xn--rskog-uua.no
xn--rst-0na.no
xn--rsta-fra.no
xn--rvc1e0am3e
xn--ryken-vua.no
xn--ryrvik-bya.no
xn--s-1fa.no
xn--s9brj9c
xn--sandnessjen-ogb.no
xn--sandy-yua.no
xn--sdtirol-n2a.it
xn--seral-lra.no
xn--ses554g
xn--sgne-gra.no
xn--skierv-uta.no
xn--skjervy-v1a.no
xn--skjk-soa.no
xn--sknit-yqa.no
xn--sknland-fxa.no
xn--slat-5na.no
xn--slt-elab.no
xn--smla-hra.no
xn--smna-gra.no
xn--snase-nra.no
xn--sndre-land-0cb.no
xn--snes-poa.no
xn--snsa-roa.no
xn--sr-aurdal-l8a.no
xn--sr-fron-q1a.no
xn--sr-odal-q1a.no
xn--sr-varanger-ggb.no
xn--srfold-bya.no
xn--srreisa-q1a.no
xn--srum-gra.no
xn--stjrdal-s1a.no
xn--stjrdalshalsen-sqb.no
xn--stre-toten-zcb.no
xn--t60b56a
xn--tckwe
xn--tiq49xqyj
xn--tjme-hra.no
xn--tn0ag.hk
xn--tnsberg-q1a.no
xn--tor131o.jp
xn--trany-yua.no
xn--trentin-sd-tirol-rzb.it
xn--trentin-sdtirol-7vb.it
xn--trentino-sd-tirol-c3b.it
xn--trentino-sdtirol-szb.it
xn--trentinosd-tirol-rzb.it
xn--trentinosdtirol-7vb.it
xn--trentinsd-tirol-6vb.it
xn--trentinsdtirol-nsb.it
xn--trgstad-r1a.no
xn--trna-woa.no
xn--troms-zua.no
xn--tysvr-vra.no
xn--uc0atv.hk
xn--uc0atv.xn--j6w193g
xn--uc0ay4a.hk
xn--uist22h.jp
xn--uisz3g.jp
xn--unjrga-rta.no
xn--unup4y
xn--uuwu58a.jp
xn--vads-jra.no
xn--valle-aoste-ebb.it
xn--valle-d-aoste-ehb.it
xn--valleaoste-e7a.it
xn--valledaoste-ebb.it
xn--vard-jra.no
xn--vegrshei-c0a.no
xn--vermgensberater-ctb
xn--vermgensberatung-pwb
xn--vestvgy-ixa6o.no
xn--vg-yiab.no
xn--vgan-qoa.no
xn--vgsy-qoa0j.no
xn--vgu402c.jp
xn--vhquv
xn--vler-qoa.hedmark.no
xn--vler-qoa.xn--stfold-9xa.no
xn--vre-eiker-k8a.no
xn--vrggt-xqad.no
xn--vry-yla5g.no
xn--vuq861b
xn--w4r85el8fhu5dnra
xn--w4rs40l
xn--wcvs22d.hk
xn--wcvs22d.xn--j6w193g
xn--wgbh1c
xn--wgbl6a
xn--xhq521b
xn--xkc2al3hye2a
xn--xkc2dl3a5ee0h
xn--y9a3aq
xn--yer-zna.no
xn--yfro4i67o
xn--ygarden-p1a.no
xn--ygbi2ammx
xn--ystre-slidre-ujb.no
xn--zbx025d.jp
xn--zf0avx.hk
xn--zfr164b
xnbay.com
xs4all.space
xtooldevice.com
xx.kg
xxx
xxx.ec
xyz
xyz.br
xz.cn
y.bg
y.se
yabu.hyogo.jp
yabuki.fukushima.jp
yachimata.chiba.jp
yachiyo.chiba.jp
yachiyo.ibaraki.jp
yachts
yaese.okinawa.jp
yahaba.iwate.jp
yahiko.niigata.jp
yahoo
yaita.tochigi.jp
yaizu.shizuoka.jp
yakage.okayama.jp
yakumo.hokkaido.jp
yakumo.shimane.jp
yali.mythic-beasts.com
yalta.ua
yamada.fukuoka.jp
yamada.iwate.jp
yamada.toyama.jp
yamaga.kumamoto.jp
yamagata.gifu.jp
yamagata.ibaraki.jp
yamagata.jp
yamagata.nagano.jp
yamagata.yamagata.jp
yamaguchi.jp
yamakita.kanagawa.jp
yamamoto.miyagi.jp
yamanakako.yamanashi.jp
yamanashi.jp
yamanashi.yamanashi.jp
yamanobe.yamagata.jp
yamanouchi.nagano.jp
yamashina.kyoto.jp
yamato.fukushima.jp
yamato.kanagawa.jp
yamato.kumamoto.jp
yamatokoriyama.nara.jp
yamatotakada.nara.jp
yamatsuri.fukushima.jp
yamaxun
yamazoe.nara.jp
yame.fukuoka.jp
yanagawa.fukuoka.jp
yanaizu.fukushima.jp
yandex
yandexcloud.net
yao.osaka.jp
yaotsu.gifu.jp
yarrow-point.wa.us
yasaka.nagano.jp
yashio.saitama.jp
yashiro.hyogo.jp
yasu.shiga.jp
yasuda.kochi.jp
yasugi.shimane.jp
yasuoka.nagano.jp
yatomi.aichi.jp
yatsuka.shimane.jp
yatsushiro.kumamoto.jp
yawara.ibaraki.jp
yawata.kyoto.jp
yawatahama.ehime.jp
yazu.tottori.jp
ye
yenbai.vn
yicp.fun
yk.ca
yn.cn
ynh.fr
yodobashi
yoga
yoichi.hokkaido.jp
yoita.niigata.jp
yoka.hyogo.jp
yokaichiba.chiba.jp
yokawa.hyogo.jp
yokkaichi.mie.jp
yokohama
yokoshibahikari.chiba.jp
yokosuka.kanagawa.jp
yokote.akita.jp
yokoze.saitama.jp
yolasite.com
yomitan.okinawa.jp
yonabaru.okinawa.jp
yonago.tottori.jp
yonaguni.okinawa.jp
yonezawa.yamagata.jp
yono.saitama.jp
yorii.saitama.jp
yoro.gifu.jp
yoshida.saitama.jp
yoshida.shizuoka.jp
yoshikawa.saitama.jp
yoshimi.saitama.jp
yoshino.nara.jp
yoshinogari.saga.jp
yoshioka.gunma.jp
yotsukaido.chiba.jp
you
you2.pl
youtube
yt
yuasa.wakayama.jp
yufu.oita.jp
yugawa.fukushima.jp
yugawara.kanagawa.jp
yuki.ibaraki.jp
yukuhashi.fukuoka.jp
yun
yura.wakayama.jp
yurihonjo.akita.jp
yusuhara.kochi.jp
yusui.kagoshima.jp
yuu.yamaguchi.jp
yuza.yamagata.jp
yuzawa.niigata.jp
z.bg
z.se
za.bz
za.com
za.net
za.org
zabc.net
zachpomor.pl
zagan.pl
zakarpattia.ua
zakopane.pl`.split("\n").filter(Boolean);
