// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_06_04 = `s3-website.dualstack.cn-north-1.amazonaws.com.cn
s3-website.dualstack.eu-central-1.amazonaws.com
s3-website.dualstack.eu-central-2.amazonaws.com
s3-website.dualstack.eu-south-1.amazonaws.com
s3-website.dualstack.eu-south-2.amazonaws.com
s3-website.dualstack.eu-west-1.amazonaws.com
s3-website.dualstack.eu-west-3.amazonaws.com
s3-website.dualstack.il-central-1.amazonaws.com
s3-website.dualstack.me-central-1.amazonaws.com
s3-website.dualstack.sa-east-1.amazonaws.com
s3-website.dualstack.us-east-1.amazonaws.com
s3-website.dualstack.us-east-2.amazonaws.com
s3-website.dualstack.us-gov-east-1.amazonaws.com
s3-website.dualstack.us-gov-west-1.amazonaws.com
s3-website.dualstack.us-west-1.amazonaws.com
s3-website.dualstack.us-west-2.amazonaws.com
s3-website.eu-central-1.amazonaws.com
s3-website.eu-central-2.amazonaws.com
s3-website.eu-north-1.amazonaws.com
s3-website.eu-south-1.amazonaws.com
s3-website.eu-south-2.amazonaws.com
s3-website.eu-west-1.amazonaws.com
s3-website.eu-west-2.amazonaws.com
s3-website.eu-west-3.amazonaws.com
s3-website.fr-par.scw.cloud
s3-website.il-central-1.amazonaws.com
s3-website.me-central-1.amazonaws.com
s3-website.me-south-1.amazonaws.com
s3-website.nl-ams.scw.cloud
s3-website.pl-waw.scw.cloud
s3-website.sa-east-1.amazonaws.com
s3-website.us-east-1.amazonaws.com
s3-website.us-east-2.amazonaws.com
s3-website.us-gov-east-1.amazonaws.com
s3-website.us-gov-west-1.amazonaws.com
s3-website.us-west-1.amazonaws.com
s3-website.us-west-2.amazonaws.com
s3.af-south-1.amazonaws.com
s3.amazonaws.com
s3.ap-east-1.amazonaws.com
s3.ap-northeast-1.amazonaws.com
s3.ap-northeast-2.amazonaws.com
s3.ap-northeast-3.amazonaws.com
s3.ap-south-1.amazonaws.com
s3.ap-south-2.amazonaws.com
s3.ap-southeast-1.amazonaws.com
s3.ap-southeast-2.amazonaws.com
s3.ap-southeast-3.amazonaws.com
s3.ap-southeast-4.amazonaws.com
s3.ap-southeast-5.amazonaws.com
s3.ca-central-1.amazonaws.com
s3.ca-west-1.amazonaws.com
s3.cn-north-1.amazonaws.com.cn
s3.cn-northwest-1.amazonaws.com.cn`.split("\n").filter(Boolean);
