// Generated from the official Public Suffix List snapshot. Do not edit manually.
export const PUBLIC_SUFFIX_RULES_04_07 = `kropyvnytskyi.ua
krym.ua
ks.ua
ks.us
kuchinotsu.nagasaki.jp
kudamatsu.yamaguchi.jp
kudoyama.wakayama.jp
kui.hiroshima.jp
kuji.iwate.jp
kuju.oita.jp
kujukuri.chiba.jp
kuki.saitama.jp
kuleuven.cloud
kumagaya.saitama.jp
kumakogen.ehime.jp
kumamoto.jp
kumamoto.kumamoto.jp
kumano.hiroshima.jp
kumano.mie.jp
kumatori.osaka.jp
kumejima.okinawa.jp
kumenan.okayama.jp
kumiyama.kyoto.jp
kunigami.okinawa.jp
kunimi.fukushima.jp
kunisaki.oita.jp
kunitachi.tokyo.jp
kunitomi.miyazaki.jp
kunneppu.hokkaido.jp
kunohe.iwate.jp
kuokgroup
kurashiki.okayama.jp
kurate.fukuoka.jp
kure.hiroshima.jp
kurgan.su
kuriyama.hokkaido.jp
kurobe.toyama.jp
kurogi.fukuoka.jp
kuroishi.aomori.jp
kuroiso.tochigi.jp
kuromatsunai.hokkaido.jp
kuron.jp
kurotaki.nara.jp
kurume.fukuoka.jp
kusatsu.gunma.jp
kusatsu.shiga.jp
kushima.miyazaki.jp
kushimoto.wakayama.jp
kushiro.hokkaido.jp
kustanai.ru
kustanai.su
kusu.oita.jp
kutchan.hokkaido.jp
kutno.pl
kuwana.mie.jp
kuzumaki.iwate.jp
kv.ua
kvafjord.no
kvalsund.no
kvam.no
kvanangen.no
kvinesdal.no
kvinnherad.no
kviteseid.no
kvitsoy.no
kw
kwp.gov.pl
kwpsp.gov.pl
ky
ky.us
kyiv.ua
kyonan.chiba.jp
kyotamba.kyoto.jp
kyotanabe.kyoto.jp
kyotango.kyoto.jp
kyoto
kyoto.jp
kyowa.akita.jp
kyowa.hokkaido.jp
kyuragi.saga.jp
kz
l-o-g-i-n.de
l.bg
l.se
la
la-spezia.it
la.us
la1-plenit.com
laakesvuemie.no
labeling.ap-northeast-1.sagemaker.aws
labeling.ap-northeast-2.sagemaker.aws
labeling.ap-south-1.sagemaker.aws
labeling.ap-southeast-1.sagemaker.aws
labeling.ap-southeast-2.sagemaker.aws
labeling.ca-central-1.sagemaker.aws
labeling.eu-central-1.sagemaker.aws
labeling.eu-west-1.sagemaker.aws
labeling.eu-west-2.sagemaker.aws
labeling.us-east-1.sagemaker.aws
labeling.us-east-2.sagemaker.aws
labeling.us-west-2.sagemaker.aws
lacaixa
ladesk.com
lahppi.no
laichau.vn
lakas.hu
lambda-url.af-south-1.on.aws
lambda-url.ap-east-1.on.aws
lambda-url.ap-northeast-1.on.aws
lambda-url.ap-northeast-2.on.aws
lambda-url.ap-northeast-3.on.aws
lambda-url.ap-south-1.on.aws
lambda-url.ap-southeast-1.on.aws
lambda-url.ap-southeast-2.on.aws
lambda-url.ap-southeast-3.on.aws
lambda-url.ca-central-1.on.aws
lambda-url.eu-central-1.on.aws
lambda-url.eu-north-1.on.aws
lambda-url.eu-south-1.on.aws
lambda-url.eu-west-1.on.aws
lambda-url.eu-west-2.on.aws
lambda-url.eu-west-3.on.aws
lambda-url.me-south-1.on.aws
lambda-url.sa-east-1.on.aws
lambda-url.us-east-1.on.aws
lambda-url.us-east-2.on.aws
lambda-url.us-west-1.on.aws
lambda-url.us-west-2.on.aws
lamborghini
lamdong.vn
lamer
lanbib.se
land
land-4-sale.us
landrover
langevag.no
langson.vn
lanxess
laocai.vn
lapy.pl
laquila.it
laravel.cloud
lardal.no
larvik.no
lasalle
laspezia.it
lat
lat.ec
latina.it
latino
latrobe
lavagis.no
lavangen.no
law
law.pro
law.za
lawyer
laz.it
lazio.it
lb`.split("\n").filter(Boolean);
