import assert from 'node:assert/strict';import {build} from 'esbuild';import {pathToFileURL} from 'node:url';
const {JSDOM,VirtualConsole}=await import(pathToFileURL(process.env.ROUND52_JSDOM_MODULE));
const bundle=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import {Route} from './src/routes/_authenticated.admin.memberships';const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const root=createRoot(document.getElementById('root'));const Page=Route.options.component;root.render(<QueryClientProvider client={client}><Page/></QueryClientProvider>);window.exit=()=>{root.unmount();client.clear()};`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,jsx:'automatic',plugins:[{name:'controlled-members',setup(b){b.onResolve({filter:/^(@tanstack\/react-router|@\/lib\/api\/(tenant-lifecycle.functions|rbac.functions))$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({loader:'js',contents:a.path==='@tanstack/react-router'?`export const createFileRoute=()=>options=>({options});`:a.path.endsWith('rbac.functions')?`export const customizeTenantAccessProfile=async({data})=>{window.clones.push(data);window.profiles.push({id:'copy',nome:'Captador personalizado',sistema:false});return {id:'copy'}};export const listarModulos=async()=>[{id:'leads',name:'Leads'}];export const obterPerfilComPermissoes=async({data})=>({perfil:window.profiles.find(p=>p.id===data.id),permissoes:[]});export const togglePermissao=async({data})=>{window.permissionWrites.push(data);return {}};export const salvarPerfil=async()=>({});export const excluirPerfil=async()=>({});export const listarPerfis=async()=>{if(window.allowProfiles)return window.profiles;throw Error('permission_denied')};export const listarPerfisPorUsuario=listarPerfis;export const setUserPerfis=()=>{throw Error('unexpected profile write')};`:`export const listTenantMemberships=async()=>window.rows;export const inviteTenantMember=async({data})=>{window.registrations.push(data);return {deliveryMode:'automated_email'}};export const changeTenantMemberRole=async()=>{};export const reactivateTenantMember=async()=>{};export const revokeTenantMember=async()=>{};export const suspendTenantMember=async()=>{};export const transferTenantOwnership=async()=>{throw Error('unexpected ownership mutation')};`}));}}]});
for(const owner of [false,true]){
 const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.invalid/admin/memberships',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;
 w.rows=[{userId:'owner',email:'owner@example.invalid',role:'owner',status:'active',isOwner:true,canTransferOwnership:owner},{userId:'member',email:'member@example.invalid',role:'viewer',status:'active',isOwner:false,canTransferOwnership:owner}];
 try{w.eval(bundle.outputFiles[0].text);for(let n=0;n<100&&!w.document.body.textContent.includes('member@example.invalid');n++)await new Promise(r=>setTimeout(r,15));const buttons=[...w.document.querySelectorAll('button')].map(b=>b.textContent);assert.ok(w.document.body.textContent.includes('member@example.invalid'));assert.ok(buttons.some(t=>t.includes('Revogar')));assert.ok(w.document.body.textContent.includes('Perfis indisponíveis'));assert.ok(!w.document.body.textContent.includes('Sem perfil'));assert.equal(buttons.some(t=>t.includes('Transferir propriedade')),owner);assert.ok(!buttons.some(t=>t.includes('Gerenciar perfis')));assert.deepEqual(errors,[]);}finally{w.exit?.();dom.window.close();}
}
console.log('PASS member UI: denied optional profiles do not hide members/CRUD; transfer shown only to owner capability; no profile/ownership writes.');

const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.invalid/admin/memberships',runScripts:'outside-only',pretendToBeVisual:true});
try {
 const w=dom.window,d=w.document;w.fetch=()=>{throw Error('NETWORK_FORBIDDEN')};w.rows=[];w.allowProfiles=true;w.profiles=[{id:'template',nome:'Captador',sistema:true}];w.clones=[];w.permissionWrites=[];w.registrations=[];
 w.eval(bundle.outputFiles[0].text);
 const tick=()=>new Promise(r=>setTimeout(r,20));const until=async p=>{for(let n=0;n<150&&!p();n++)await tick();assert.ok(p())};
 const button=t=>[...d.querySelectorAll('button')].find(b=>b.textContent.trim()===t);
 await until(()=>button('Novo usuário'));button('Novo usuário').click();await until(()=>d.getElementById('new-user-name'));
 assert.ok(button('Cadastrar e enviar ativação').disabled);
 for(const [id,value] of [['new-user-name','Pessoa de teste'],['new-user-email','new@example.invalid']]){const el=d.getElementById(id);Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new w.Event('input',{bubbles:true}));}
 await tick();d.querySelector('[role=checkbox]').click();await tick();button('Personalizar permissões').click();
 await until(()=>button('Personalizar para a empresa'));button('Personalizar para a empresa').click();
 await until(()=>d.querySelector('input[type=checkbox]')&&!d.querySelector('input[type=checkbox]').disabled);
 assert.equal(w.clones.length,1);assert.equal(w.registrations.length,0);
 d.querySelector('input[type=checkbox]').click();await until(()=>w.permissionWrites.length===1);assert.equal(w.permissionWrites[0].profile_id,'copy');
 const dialogs=[...d.querySelectorAll('[role=dialog]')];[...dialogs.at(-1).querySelectorAll('button')].find(b=>b.textContent==='Fechar').click();
 await until(()=>d.querySelectorAll('[role=dialog]').length===1);await until(()=>!button('Cadastrar e enviar ativação').disabled);button('Cadastrar e enviar ativação').click();
 await until(()=>w.registrations.length===1);assert.equal(w.registrations[0].name,'Pessoa de teste');assert.deepEqual(Array.from(w.registrations[0].profileIds),['copy']);assert.ok(!('password' in w.registrations[0]));
 console.log('PASS actual user UI: name/email/profile required, clone opens editable permissions, template replaced by customized profile, configuration precedes registration, no operator password or network.');
} finally {dom.window.exit?.();dom.window.close()}
