import assert from 'node:assert/strict';import {build} from 'esbuild';import {pathToFileURL} from 'node:url';
const {JSDOM,VirtualConsole}=await import(pathToFileURL(process.env.ROUND52_JSDOM_MODULE));
const bundle=await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import {Route} from './src/routes/_authenticated.admin.memberships';const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const root=createRoot(document.getElementById('root'));const Page=Route.options.component;root.render(<QueryClientProvider client={client}><Page/></QueryClientProvider>);window.exit=()=>{root.unmount();client.clear()};`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,jsx:'automatic',plugins:[{name:'controlled-members',setup(b){b.onResolve({filter:/^(@tanstack\/react-router|@\/lib\/api\/(tenant-lifecycle.functions|rbac.functions))$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({loader:'js',contents:a.path==='@tanstack/react-router'?`export const createFileRoute=()=>options=>({options});`:a.path.endsWith('rbac.functions')?`export const listarPerfis=async()=>{throw Error('permission_denied')};export const listarPerfisPorUsuario=listarPerfis;export const setUserPerfis=()=>{throw Error('unexpected profile write')};`:`export const listTenantMemberships=async()=>window.rows;export const inviteTenantMember=async()=>{};export const changeTenantMemberRole=async()=>{};export const reactivateTenantMember=async()=>{};export const revokeTenantMember=async()=>{};export const suspendTenantMember=async()=>{};export const transferTenantOwnership=async()=>{throw Error('unexpected ownership mutation')};`}));}}]});
for(const owner of [false,true]){
 const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.invalid/admin/memberships',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;
 w.rows=[{userId:'owner',email:'owner@example.invalid',role:'owner',status:'active',isOwner:true,canTransferOwnership:owner},{userId:'member',email:'member@example.invalid',role:'viewer',status:'active',isOwner:false,canTransferOwnership:owner}];
 try{w.eval(bundle.outputFiles[0].text);for(let n=0;n<100&&!w.document.body.textContent.includes('member@example.invalid');n++)await new Promise(r=>setTimeout(r,15));const buttons=[...w.document.querySelectorAll('button')].map(b=>b.textContent);assert.ok(w.document.body.textContent.includes('member@example.invalid'));assert.ok(buttons.some(t=>t.includes('Revogar')));assert.ok(w.document.body.textContent.includes('Perfis indisponíveis'));assert.ok(!w.document.body.textContent.includes('Sem perfil'));assert.equal(buttons.some(t=>t.includes('Tornar owner')),owner);assert.ok(!buttons.some(t=>t.includes('Gerenciar perfis')));assert.deepEqual(errors,[]);}finally{w.exit?.();dom.window.close();}
}
console.log('PASS member UI: denied optional profiles do not hide members/CRUD; transfer shown only to owner capability; no profile/ownership writes.');
