import {build} from 'esbuild';import assert from 'node:assert/strict';import {writeFileSync,mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {pathToFileURL} from 'node:url';
const output=await build({entryPoints:['src/lib/api/tenant-lifecycle.functions.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'controlled',setup(b){b.onResolve({filter:/^(@tanstack\/react-start|@\/integrations\/supabase\/(auth-middleware|tenant-middleware|client.server))$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({loader:'js',contents:a.path==='@tanstack/react-start'?`export const createServerFn=()=>({middleware(){return this},inputValidator(v){this.v=v;return this},handler(h){const v=this.v;return data=>h({data:v?v(data):data,context:globalThis.ctx})}});`:a.path.endsWith('client.server')?`export const supabaseAdmin=globalThis.admin;`:`export const requireTenant={};export const requireSupabaseAuth={};`}));}}]});
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;let calls=[],membership;
const rows=[{tenant_id:id(10),user_id:id(1),tenant_role:'owner',membership_status:'active',is_owner:true},{tenant_id:id(10),user_id:id(2),tenant_role:'admin',membership_status:'active',is_owner:false},{tenant_id:id(11),user_id:id(3),tenant_role:'viewer',membership_status:'active',is_owner:false}];
globalThis.admin={from(table){assert.equal(table,'tenant_members');calls.push('list');let tenant;return{select(){return this},eq(k,v){assert.equal(k,'tenant_id');tenant=v;return this},order(){return this},then(ok){return Promise.resolve({data:rows.filter(r=>r.tenant_id===tenant),error:null}).then(ok)}}},auth:{admin:{getUserById:async id=>{calls.push('auth');return{data:{user:{email:id+'@example.invalid'}}}},listUsers:async()=>{calls.push('find');return{data:{users:[{id:id(4),email:'invite@example.invalid',email_confirmed_at:'controlled'}]}}}}},rpc:async(name,args)=>{calls.push(name);assert.equal(args._actor_user_id,id(2));assert.equal(args._tenant_id,id(10));return{data:{tenantId:id(10),targetUserId:id(4),operation:'invite',changed:true,status:'invited',role:'viewer',invitedAt:'2026-09-09T00:00:00Z'},error:null}}};
globalThis.ctx={userId:id(2),tenant:{tenantId:id(10),origin:'selection',isSuperAdmin:false,impersonation:false},supabase:{from(table){assert.equal(table,'tenant_members');let filters={};return{select(){return this},eq(k,v){filters[k]=v;return this},async maybeSingle(){assert.equal(filters.tenant_id,ctx.tenant.tenantId);assert.equal(filters.user_id,ctx.userId);return{data:membership,error:null}}}}}};
const file=join(mkdtempSync(join(tmpdir(),'p0-members-')),'server.mjs');writeFileSync(file,output.outputFiles[0].text);const api=await import(pathToFileURL(file));
membership={tenant_role:'admin',membership_status:'active',is_owner:false};let result=await api.listTenantMemberships();assert.equal(result.length,2);assert.ok(result.every(r=>!r.canTransferOwnership));await api.inviteTenantMember({email:'invite@example.invalid',targetRole:'viewer'});assert.ok(calls.includes('invite_tenant_member'));
ctx.userId=id(1);membership={tenant_role:'owner',membership_status:'active',is_owner:true};result=await api.listTenantMemberships();assert.ok(result.every(r=>r.canTransferOwnership));
for(const m of [{tenant_role:'admin',membership_status:'suspended',is_owner:false},{tenant_role:'viewer',membership_status:'active',is_owner:false},null]){membership=m;calls=[];await assert.rejects(api.listTenantMemberships());await assert.rejects(api.inviteTenantMember({email:'invite@example.invalid',targetRole:'viewer'}));assert.deepEqual(calls,[]);}
membership={tenant_role:'admin',membership_status:'active',is_owner:false};ctx.tenant.isSuperAdmin=true;calls=[];await assert.rejects(api.listTenantMemberships(),/Super Admin/);await assert.rejects(api.inviteTenantMember({email:'invite@example.invalid',targetRole:'viewer'}),/Super Admin/);assert.deepEqual(calls,[]);
ctx.tenant.isSuperAdmin=false;ctx.tenant.impersonation=true;await assert.rejects(api.listTenantMemberships());assert.deepEqual(calls,[]);
console.log('PASS server: Admin list/invite within tenant; owner-only transfer capability; viewer/suspended/missing/Super/impersonation denied before privileged Auth calls.');
