/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LancamentosSlugRouteImport } from './routes/lancamentos.$slug'
import { Route as ImovelSlugRouteImport } from './routes/imovel.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated.super'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated.invitations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedSuperIndexRouteImport } from './routes/_authenticated.super.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicPortalLeadsRouteImport } from './routes/api/public/portal-leads'
import { Route as ApiInternalSpr03ManagedSecretProvisionRouteImport } from './routes/api/internal/spr-03-managed-secret-provision'
import { Route as ApiInternalBillingReconcileRouteImport } from './routes/api/internal/billing-reconcile'
import { Route as ApiInternalBillingPortalRouteImport } from './routes/api/internal/billing-portal'
import { Route as ApiInternalBillingCheckoutRouteImport } from './routes/api/internal/billing-checkout'
import { Route as AuthenticatedSuperObservabilidadeRouteImport } from './routes/_authenticated.super.observabilidade'
import { Route as AuthenticatedSuperDomainsRouteImport } from './routes/_authenticated.super.domains'
import { Route as AuthenticatedSuperDlqRouteImport } from './routes/_authenticated.super.dlq'
import { Route as AuthenticatedSuperControlPlaneRouteImport } from './routes/_authenticated.super.control-plane'
import { Route as AuthenticatedAdminTrackingRouteImport } from './routes/_authenticated.admin.tracking'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated.admin.site'
import { Route as AuthenticatedAdminPortaisRouteImport } from './routes/_authenticated.admin.portais'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated.admin.pipeline'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated.admin.perfis'
import { Route as AuthenticatedAdminOrigensRouteImport } from './routes/_authenticated.admin.origens'
import { Route as AuthenticatedAdminMotivosRouteImport } from './routes/_authenticated.admin.motivos'
import { Route as AuthenticatedAdminMidiasRouteImport } from './routes/_authenticated.admin.midias'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated.admin.memberships'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated.admin.marketing'
import { Route as AuthenticatedAdminLeadsWorkspaceRouteImport } from './routes/_authenticated.admin.leads-workspace'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated.admin.leads'
import { Route as AuthenticatedAdminEquipesRouteImport } from './routes/_authenticated.admin.equipes'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated.admin.domains'
import { Route as AuthenticatedAdminCrmOperacoesRouteImport } from './routes/_authenticated.admin.crm-operacoes'
import { Route as AuthenticatedAdminCorretoresRouteImport } from './routes/_authenticated.admin.corretores'
import { Route as AuthenticatedAdminCmsTransferenciaRouteImport } from './routes/_authenticated.admin.cms-transferencia'
import { Route as AuthenticatedAdminCmsInventarioRouteImport } from './routes/_authenticated.admin.cms-inventario'
import { Route as AuthenticatedAdminCmsAuditoriaRouteImport } from './routes/_authenticated.admin.cms-auditoria'
import { Route as AuthenticatedAdminCidadesRouteImport } from './routes/_authenticated.admin.cidades'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated.admin.blog'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated.admin.billing'
import { Route as AuthenticatedAdminBairrosRouteImport } from './routes/_authenticated.admin.bairros'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated.admin.auditoria'
import { Route as AuthenticatedAdminPaginasIndexRouteImport } from './routes/_authenticated.admin.paginas.index'
import { Route as AuthenticatedAdminLancamentosIndexRouteImport } from './routes/_authenticated.admin.lancamentos.index'
import { Route as AuthenticatedAdminImoveisIndexRouteImport } from './routes/_authenticated.admin.imoveis.index'
import { Route as AuthenticatedAdminFormulariosIndexRouteImport } from './routes/_authenticated.admin.formularios.index'
import { Route as AuthenticatedAdminCampanhasIndexRouteImport } from './routes/_authenticated.admin.campanhas.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated.admin.blog.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksPortalDlqRetryRouteImport } from './routes/api/public/hooks/portal-dlq-retry'
import { Route as ApiPublicHooksBillingStripeWebhookRouteImport } from './routes/api/public/hooks/billing-stripe-webhook'
import { Route as AuthenticatedAdminPaginasIdRouteImport } from './routes/_authenticated.admin.paginas.$id'
import { Route as AuthenticatedAdminLancamentosNovoRouteImport } from './routes/_authenticated.admin.lancamentos.novo'
import { Route as AuthenticatedAdminLancamentosIdRouteImport } from './routes/_authenticated.admin.lancamentos.$id'
import { Route as AuthenticatedAdminImoveisNovoRouteImport } from './routes/_authenticated.admin.imoveis.novo'
import { Route as AuthenticatedAdminImoveisIdRouteImport } from './routes/_authenticated.admin.imoveis.$id'
import { Route as AuthenticatedAdminFormulariosIdRouteImport } from './routes/_authenticated.admin.formularios.$id'
import { Route as AuthenticatedAdminCampanhasIdRouteImport } from './routes/_authenticated.admin.campanhas.$id'
import { Route as AuthenticatedAdminBlogNovoRouteImport } from './routes/_authenticated.admin.blog.novo'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated.admin.blog.$id'
import { Route as ApiPublicFeedsPortalTokenRouteImport } from './routes/api/public/feeds.$portal.$token'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosSlugRoute = LancamentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LancamentosRoute,
} as any)
const ImovelSlugRoute = ImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperIndexRoute = AuthenticatedSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSuperRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalLeadsRoute = ApiPublicPortalLeadsRouteImport.update({
  id: '/api/public/portal-leads',
  path: '/api/public/portal-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalSpr03ManagedSecretProvisionRoute =
  ApiInternalSpr03ManagedSecretProvisionRouteImport.update({
    id: '/api/internal/spr-03-managed-secret-provision',
    path: '/api/internal/spr-03-managed-secret-provision',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalBillingReconcileRoute =
  ApiInternalBillingReconcileRouteImport.update({
    id: '/api/internal/billing-reconcile',
    path: '/api/internal/billing-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalBillingPortalRoute =
  ApiInternalBillingPortalRouteImport.update({
    id: '/api/internal/billing-portal',
    path: '/api/internal/billing-portal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalBillingCheckoutRoute =
  ApiInternalBillingCheckoutRouteImport.update({
    id: '/api/internal/billing-checkout',
    path: '/api/internal/billing-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperObservabilidadeRoute =
  AuthenticatedSuperObservabilidadeRouteImport.update({
    id: '/observabilidade',
    path: '/observabilidade',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperDomainsRoute =
  AuthenticatedSuperDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedSuperDlqRoute = AuthenticatedSuperDlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => AuthenticatedSuperRoute,
} as any)
const AuthenticatedSuperControlPlaneRoute =
  AuthenticatedSuperControlPlaneRouteImport.update({
    id: '/control-plane',
    path: '/control-plane',
    getParentRoute: () => AuthenticatedSuperRoute,
  } as any)
const AuthenticatedAdminTrackingRoute =
  AuthenticatedAdminTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPortaisRoute =
  AuthenticatedAdminPortaisRouteImport.update({
    id: '/portais',
    path: '/portais',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/perfis',
    path: '/perfis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrigensRoute =
  AuthenticatedAdminOrigensRouteImport.update({
    id: '/origens',
    path: '/origens',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMotivosRoute =
  AuthenticatedAdminMotivosRouteImport.update({
    id: '/motivos',
    path: '/motivos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMidiasRoute =
  AuthenticatedAdminMidiasRouteImport.update({
    id: '/midias',
    path: '/midias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsWorkspaceRoute =
  AuthenticatedAdminLeadsWorkspaceRouteImport.update({
    id: '/leads-workspace',
    path: '/leads-workspace',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEquipesRoute =
  AuthenticatedAdminEquipesRouteImport.update({
    id: '/equipes',
    path: '/equipes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmOperacoesRoute =
  AuthenticatedAdminCrmOperacoesRouteImport.update({
    id: '/crm-operacoes',
    path: '/crm-operacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCorretoresRoute =
  AuthenticatedAdminCorretoresRouteImport.update({
    id: '/corretores',
    path: '/corretores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsTransferenciaRoute =
  AuthenticatedAdminCmsTransferenciaRouteImport.update({
    id: '/cms-transferencia',
    path: '/cms-transferencia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsInventarioRoute =
  AuthenticatedAdminCmsInventarioRouteImport.update({
    id: '/cms-inventario',
    path: '/cms-inventario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsAuditoriaRoute =
  AuthenticatedAdminCmsAuditoriaRouteImport.update({
    id: '/cms-auditoria',
    path: '/cms-auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCidadesRoute =
  AuthenticatedAdminCidadesRouteImport.update({
    id: '/cidades',
    path: '/cidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBairrosRoute =
  AuthenticatedAdminBairrosRouteImport.update({
    id: '/bairros',
    path: '/bairros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaginasIndexRoute =
  AuthenticatedAdminPaginasIndexRouteImport.update({
    id: '/paginas/',
    path: '/paginas/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLancamentosIndexRoute =
  AuthenticatedAdminLancamentosIndexRouteImport.update({
    id: '/lancamentos/',
    path: '/lancamentos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImoveisIndexRoute =
  AuthenticatedAdminImoveisIndexRouteImport.update({
    id: '/imoveis/',
    path: '/imoveis/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFormulariosIndexRoute =
  AuthenticatedAdminFormulariosIndexRouteImport.update({
    id: '/formularios/',
    path: '/formularios/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampanhasIndexRoute =
  AuthenticatedAdminCampanhasIndexRouteImport.update({
    id: '/campanhas/',
    path: '/campanhas/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPortalDlqRetryRoute =
  ApiPublicHooksPortalDlqRetryRouteImport.update({
    id: '/api/public/hooks/portal-dlq-retry',
    path: '/api/public/hooks/portal-dlq-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBillingStripeWebhookRoute =
  ApiPublicHooksBillingStripeWebhookRouteImport.update({
    id: '/api/public/hooks/billing-stripe-webhook',
    path: '/api/public/hooks/billing-stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPaginasIdRoute =
  AuthenticatedAdminPaginasIdRouteImport.update({
    id: '/paginas/$id',
    path: '/paginas/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLancamentosNovoRoute =
  AuthenticatedAdminLancamentosNovoRouteImport.update({
    id: '/lancamentos/novo',
    path: '/lancamentos/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLancamentosIdRoute =
  AuthenticatedAdminLancamentosIdRouteImport.update({
    id: '/lancamentos/$id',
    path: '/lancamentos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImoveisNovoRoute =
  AuthenticatedAdminImoveisNovoRouteImport.update({
    id: '/imoveis/novo',
    path: '/imoveis/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImoveisIdRoute =
  AuthenticatedAdminImoveisIdRouteImport.update({
    id: '/imoveis/$id',
    path: '/imoveis/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFormulariosIdRoute =
  AuthenticatedAdminFormulariosIdRouteImport.update({
    id: '/formularios/$id',
    path: '/formularios/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCampanhasIdRoute =
  AuthenticatedAdminCampanhasIdRouteImport.update({
    id: '/campanhas/$id',
    path: '/campanhas/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogNovoRoute =
  AuthenticatedAdminBlogNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBlogRoute,
  } as any)
const ApiPublicFeedsPortalTokenRoute =
  ApiPublicFeedsPortalTokenRouteImport.update({
    id: '/api/public/feeds/$portal/$token',
    path: '/api/public/feeds/$portal/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/super': typeof AuthenticatedSuperRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/lancamentos/$slug': typeof LancamentosSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/bairros': typeof AuthenticatedAdminBairrosRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/cms-auditoria': typeof AuthenticatedAdminCmsAuditoriaRoute
  '/admin/cms-inventario': typeof AuthenticatedAdminCmsInventarioRoute
  '/admin/cms-transferencia': typeof AuthenticatedAdminCmsTransferenciaRoute
  '/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/admin/crm-operacoes': typeof AuthenticatedAdminCrmOperacoesRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/equipes': typeof AuthenticatedAdminEquipesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/leads-workspace': typeof AuthenticatedAdminLeadsWorkspaceRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/midias': typeof AuthenticatedAdminMidiasRoute
  '/admin/motivos': typeof AuthenticatedAdminMotivosRoute
  '/admin/origens': typeof AuthenticatedAdminOrigensRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/portais': typeof AuthenticatedAdminPortaisRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/super/control-plane': typeof AuthenticatedSuperControlPlaneRoute
  '/super/dlq': typeof AuthenticatedSuperDlqRoute
  '/super/domains': typeof AuthenticatedSuperDomainsRoute
  '/super/observabilidade': typeof AuthenticatedSuperObservabilidadeRoute
  '/api/internal/billing-checkout': typeof ApiInternalBillingCheckoutRoute
  '/api/internal/billing-portal': typeof ApiInternalBillingPortalRoute
  '/api/internal/billing-reconcile': typeof ApiInternalBillingReconcileRoute
  '/api/internal/spr-03-managed-secret-provision': typeof ApiInternalSpr03ManagedSecretProvisionRoute
  '/api/public/portal-leads': typeof ApiPublicPortalLeadsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super/': typeof AuthenticatedSuperIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/novo': typeof AuthenticatedAdminBlogNovoRoute
  '/admin/campanhas/$id': typeof AuthenticatedAdminCampanhasIdRoute
  '/admin/formularios/$id': typeof AuthenticatedAdminFormulariosIdRoute
  '/admin/imoveis/$id': typeof AuthenticatedAdminImoveisIdRoute
  '/admin/imoveis/novo': typeof AuthenticatedAdminImoveisNovoRoute
  '/admin/lancamentos/$id': typeof AuthenticatedAdminLancamentosIdRoute
  '/admin/lancamentos/novo': typeof AuthenticatedAdminLancamentosNovoRoute
  '/admin/paginas/$id': typeof AuthenticatedAdminPaginasIdRoute
  '/api/public/hooks/billing-stripe-webhook': typeof ApiPublicHooksBillingStripeWebhookRoute
  '/api/public/hooks/portal-dlq-retry': typeof ApiPublicHooksPortalDlqRetryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/campanhas/': typeof AuthenticatedAdminCampanhasIndexRoute
  '/admin/formularios/': typeof AuthenticatedAdminFormulariosIndexRoute
  '/admin/imoveis/': typeof AuthenticatedAdminImoveisIndexRoute
  '/admin/lancamentos/': typeof AuthenticatedAdminLancamentosIndexRoute
  '/admin/paginas/': typeof AuthenticatedAdminPaginasIndexRoute
  '/api/public/feeds/$portal/$token': typeof ApiPublicFeedsPortalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/lancamentos/$slug': typeof LancamentosSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/bairros': typeof AuthenticatedAdminBairrosRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/cms-auditoria': typeof AuthenticatedAdminCmsAuditoriaRoute
  '/admin/cms-inventario': typeof AuthenticatedAdminCmsInventarioRoute
  '/admin/cms-transferencia': typeof AuthenticatedAdminCmsTransferenciaRoute
  '/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/admin/crm-operacoes': typeof AuthenticatedAdminCrmOperacoesRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/equipes': typeof AuthenticatedAdminEquipesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/leads-workspace': typeof AuthenticatedAdminLeadsWorkspaceRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/midias': typeof AuthenticatedAdminMidiasRoute
  '/admin/motivos': typeof AuthenticatedAdminMotivosRoute
  '/admin/origens': typeof AuthenticatedAdminOrigensRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/portais': typeof AuthenticatedAdminPortaisRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/super/control-plane': typeof AuthenticatedSuperControlPlaneRoute
  '/super/dlq': typeof AuthenticatedSuperDlqRoute
  '/super/domains': typeof AuthenticatedSuperDomainsRoute
  '/super/observabilidade': typeof AuthenticatedSuperObservabilidadeRoute
  '/api/internal/billing-checkout': typeof ApiInternalBillingCheckoutRoute
  '/api/internal/billing-portal': typeof ApiInternalBillingPortalRoute
  '/api/internal/billing-reconcile': typeof ApiInternalBillingReconcileRoute
  '/api/internal/spr-03-managed-secret-provision': typeof ApiInternalSpr03ManagedSecretProvisionRoute
  '/api/public/portal-leads': typeof ApiPublicPortalLeadsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super': typeof AuthenticatedSuperIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/novo': typeof AuthenticatedAdminBlogNovoRoute
  '/admin/campanhas/$id': typeof AuthenticatedAdminCampanhasIdRoute
  '/admin/formularios/$id': typeof AuthenticatedAdminFormulariosIdRoute
  '/admin/imoveis/$id': typeof AuthenticatedAdminImoveisIdRoute
  '/admin/imoveis/novo': typeof AuthenticatedAdminImoveisNovoRoute
  '/admin/lancamentos/$id': typeof AuthenticatedAdminLancamentosIdRoute
  '/admin/lancamentos/novo': typeof AuthenticatedAdminLancamentosNovoRoute
  '/admin/paginas/$id': typeof AuthenticatedAdminPaginasIdRoute
  '/api/public/hooks/billing-stripe-webhook': typeof ApiPublicHooksBillingStripeWebhookRoute
  '/api/public/hooks/portal-dlq-retry': typeof ApiPublicHooksPortalDlqRetryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/campanhas': typeof AuthenticatedAdminCampanhasIndexRoute
  '/admin/formularios': typeof AuthenticatedAdminFormulariosIndexRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisIndexRoute
  '/admin/lancamentos': typeof AuthenticatedAdminLancamentosIndexRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasIndexRoute
  '/api/public/feeds/$portal/$token': typeof ApiPublicFeedsPortalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/lancamentos': typeof LancamentosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/super': typeof AuthenticatedSuperRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/lancamentos/$slug': typeof LancamentosSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/bairros': typeof AuthenticatedAdminBairrosRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRouteWithChildren
  '/_authenticated/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/_authenticated/admin/cms-auditoria': typeof AuthenticatedAdminCmsAuditoriaRoute
  '/_authenticated/admin/cms-inventario': typeof AuthenticatedAdminCmsInventarioRoute
  '/_authenticated/admin/cms-transferencia': typeof AuthenticatedAdminCmsTransferenciaRoute
  '/_authenticated/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/_authenticated/admin/crm-operacoes': typeof AuthenticatedAdminCrmOperacoesRoute
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/equipes': typeof AuthenticatedAdminEquipesRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/leads-workspace': typeof AuthenticatedAdminLeadsWorkspaceRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_authenticated/admin/midias': typeof AuthenticatedAdminMidiasRoute
  '/_authenticated/admin/motivos': typeof AuthenticatedAdminMotivosRoute
  '/_authenticated/admin/origens': typeof AuthenticatedAdminOrigensRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/portais': typeof AuthenticatedAdminPortaisRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/_authenticated/admin/tracking': typeof AuthenticatedAdminTrackingRoute
  '/_authenticated/super/control-plane': typeof AuthenticatedSuperControlPlaneRoute
  '/_authenticated/super/dlq': typeof AuthenticatedSuperDlqRoute
  '/_authenticated/super/domains': typeof AuthenticatedSuperDomainsRoute
  '/_authenticated/super/observabilidade': typeof AuthenticatedSuperObservabilidadeRoute
  '/api/internal/billing-checkout': typeof ApiInternalBillingCheckoutRoute
  '/api/internal/billing-portal': typeof ApiInternalBillingPortalRoute
  '/api/internal/billing-reconcile': typeof ApiInternalBillingReconcileRoute
  '/api/internal/spr-03-managed-secret-provision': typeof ApiInternalSpr03ManagedSecretProvisionRoute
  '/api/public/portal-leads': typeof ApiPublicPortalLeadsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super/': typeof AuthenticatedSuperIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/blog/novo': typeof AuthenticatedAdminBlogNovoRoute
  '/_authenticated/admin/campanhas/$id': typeof AuthenticatedAdminCampanhasIdRoute
  '/_authenticated/admin/formularios/$id': typeof AuthenticatedAdminFormulariosIdRoute
  '/_authenticated/admin/imoveis/$id': typeof AuthenticatedAdminImoveisIdRoute
  '/_authenticated/admin/imoveis/novo': typeof AuthenticatedAdminImoveisNovoRoute
  '/_authenticated/admin/lancamentos/$id': typeof AuthenticatedAdminLancamentosIdRoute
  '/_authenticated/admin/lancamentos/novo': typeof AuthenticatedAdminLancamentosNovoRoute
  '/_authenticated/admin/paginas/$id': typeof AuthenticatedAdminPaginasIdRoute
  '/api/public/hooks/billing-stripe-webhook': typeof ApiPublicHooksBillingStripeWebhookRoute
  '/api/public/hooks/portal-dlq-retry': typeof ApiPublicHooksPortalDlqRetryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/campanhas/': typeof AuthenticatedAdminCampanhasIndexRoute
  '/_authenticated/admin/formularios/': typeof AuthenticatedAdminFormulariosIndexRoute
  '/_authenticated/admin/imoveis/': typeof AuthenticatedAdminImoveisIndexRoute
  '/_authenticated/admin/lancamentos/': typeof AuthenticatedAdminLancamentosIndexRoute
  '/_authenticated/admin/paginas/': typeof AuthenticatedAdminPaginasIndexRoute
  '/api/public/feeds/$portal/$token': typeof ApiPublicFeedsPortalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/contato'
    | '/imoveis'
    | '/lancamentos'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/unsubscribe'
    | '/admin'
    | '/invitations'
    | '/super'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/imovel/$slug'
    | '/lancamentos/$slug'
    | '/p/$slug'
    | '/blog/'
    | '/admin/auditoria'
    | '/admin/bairros'
    | '/admin/billing'
    | '/admin/blog'
    | '/admin/cidades'
    | '/admin/cms-auditoria'
    | '/admin/cms-inventario'
    | '/admin/cms-transferencia'
    | '/admin/corretores'
    | '/admin/crm-operacoes'
    | '/admin/domains'
    | '/admin/equipes'
    | '/admin/leads'
    | '/admin/leads-workspace'
    | '/admin/marketing'
    | '/admin/memberships'
    | '/admin/midias'
    | '/admin/motivos'
    | '/admin/origens'
    | '/admin/perfis'
    | '/admin/pipeline'
    | '/admin/portais'
    | '/admin/site'
    | '/admin/tracking'
    | '/super/control-plane'
    | '/super/dlq'
    | '/super/domains'
    | '/super/observabilidade'
    | '/api/internal/billing-checkout'
    | '/api/internal/billing-portal'
    | '/api/internal/billing-reconcile'
    | '/api/internal/spr-03-managed-secret-provision'
    | '/api/public/portal-leads'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/super/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/campanhas/$id'
    | '/admin/formularios/$id'
    | '/admin/imoveis/$id'
    | '/admin/imoveis/novo'
    | '/admin/lancamentos/$id'
    | '/admin/lancamentos/novo'
    | '/admin/paginas/$id'
    | '/api/public/hooks/billing-stripe-webhook'
    | '/api/public/hooks/portal-dlq-retry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/blog/'
    | '/admin/campanhas/'
    | '/admin/formularios/'
    | '/admin/imoveis/'
    | '/admin/lancamentos/'
    | '/admin/paginas/'
    | '/api/public/feeds/$portal/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/contato'
    | '/imoveis'
    | '/lancamentos'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/unsubscribe'
    | '/invitations'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/imovel/$slug'
    | '/lancamentos/$slug'
    | '/p/$slug'
    | '/blog'
    | '/admin/auditoria'
    | '/admin/bairros'
    | '/admin/billing'
    | '/admin/cidades'
    | '/admin/cms-auditoria'
    | '/admin/cms-inventario'
    | '/admin/cms-transferencia'
    | '/admin/corretores'
    | '/admin/crm-operacoes'
    | '/admin/domains'
    | '/admin/equipes'
    | '/admin/leads'
    | '/admin/leads-workspace'
    | '/admin/marketing'
    | '/admin/memberships'
    | '/admin/midias'
    | '/admin/motivos'
    | '/admin/origens'
    | '/admin/perfis'
    | '/admin/pipeline'
    | '/admin/portais'
    | '/admin/site'
    | '/admin/tracking'
    | '/super/control-plane'
    | '/super/dlq'
    | '/super/domains'
    | '/super/observabilidade'
    | '/api/internal/billing-checkout'
    | '/api/internal/billing-portal'
    | '/api/internal/billing-reconcile'
    | '/api/internal/spr-03-managed-secret-provision'
    | '/api/public/portal-leads'
    | '/lovable/email/suppression'
    | '/admin'
    | '/super'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/campanhas/$id'
    | '/admin/formularios/$id'
    | '/admin/imoveis/$id'
    | '/admin/imoveis/novo'
    | '/admin/lancamentos/$id'
    | '/admin/lancamentos/novo'
    | '/admin/paginas/$id'
    | '/api/public/hooks/billing-stripe-webhook'
    | '/api/public/hooks/portal-dlq-retry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/blog'
    | '/admin/campanhas'
    | '/admin/formularios'
    | '/admin/imoveis'
    | '/admin/lancamentos'
    | '/admin/paginas'
    | '/api/public/feeds/$portal/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anuncie'
    | '/auth'
    | '/contato'
    | '/imoveis'
    | '/lancamentos'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/invitations'
    | '/_authenticated/super'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/imovel/$slug'
    | '/lancamentos/$slug'
    | '/p/$slug'
    | '/blog/'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/bairros'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/cidades'
    | '/_authenticated/admin/cms-auditoria'
    | '/_authenticated/admin/cms-inventario'
    | '/_authenticated/admin/cms-transferencia'
    | '/_authenticated/admin/corretores'
    | '/_authenticated/admin/crm-operacoes'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/equipes'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/leads-workspace'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/memberships'
    | '/_authenticated/admin/midias'
    | '/_authenticated/admin/motivos'
    | '/_authenticated/admin/origens'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/portais'
    | '/_authenticated/admin/site'
    | '/_authenticated/admin/tracking'
    | '/_authenticated/super/control-plane'
    | '/_authenticated/super/dlq'
    | '/_authenticated/super/domains'
    | '/_authenticated/super/observabilidade'
    | '/api/internal/billing-checkout'
    | '/api/internal/billing-portal'
    | '/api/internal/billing-reconcile'
    | '/api/internal/spr-03-managed-secret-provision'
    | '/api/public/portal-leads'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/super/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/blog/novo'
    | '/_authenticated/admin/campanhas/$id'
    | '/_authenticated/admin/formularios/$id'
    | '/_authenticated/admin/imoveis/$id'
    | '/_authenticated/admin/imoveis/novo'
    | '/_authenticated/admin/lancamentos/$id'
    | '/_authenticated/admin/lancamentos/novo'
    | '/_authenticated/admin/paginas/$id'
    | '/api/public/hooks/billing-stripe-webhook'
    | '/api/public/hooks/portal-dlq-retry'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/campanhas/'
    | '/_authenticated/admin/formularios/'
    | '/_authenticated/admin/imoveis/'
    | '/_authenticated/admin/lancamentos/'
    | '/_authenticated/admin/paginas/'
    | '/api/public/feeds/$portal/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnuncieRoute: typeof AnuncieRoute
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  ImoveisRoute: typeof ImoveisRoute
  LancamentosRoute: typeof LancamentosRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ImovelSlugRoute: typeof ImovelSlugRoute
  PSlugRoute: typeof PSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiInternalBillingCheckoutRoute: typeof ApiInternalBillingCheckoutRoute
  ApiInternalBillingPortalRoute: typeof ApiInternalBillingPortalRoute
  ApiInternalBillingReconcileRoute: typeof ApiInternalBillingReconcileRoute
  ApiInternalSpr03ManagedSecretProvisionRoute: typeof ApiInternalSpr03ManagedSecretProvisionRoute
  ApiPublicPortalLeadsRoute: typeof ApiPublicPortalLeadsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksBillingStripeWebhookRoute: typeof ApiPublicHooksBillingStripeWebhookRoute
  ApiPublicHooksPortalDlqRetryRoute: typeof ApiPublicHooksPortalDlqRetryRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicFeedsPortalTokenRoute: typeof ApiPublicFeedsPortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos/$slug': {
      id: '/lancamentos/$slug'
      path: '/$slug'
      fullPath: '/lancamentos/$slug'
      preLoaderRoute: typeof LancamentosSlugRouteImport
      parentRoute: typeof LancamentosRoute
    }
    '/imovel/$slug': {
      id: '/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof ImovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super/': {
      id: '/_authenticated/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof AuthenticatedSuperIndexRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal-leads': {
      id: '/api/public/portal-leads'
      path: '/api/public/portal-leads'
      fullPath: '/api/public/portal-leads'
      preLoaderRoute: typeof ApiPublicPortalLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/spr-03-managed-secret-provision': {
      id: '/api/internal/spr-03-managed-secret-provision'
      path: '/api/internal/spr-03-managed-secret-provision'
      fullPath: '/api/internal/spr-03-managed-secret-provision'
      preLoaderRoute: typeof ApiInternalSpr03ManagedSecretProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/billing-reconcile': {
      id: '/api/internal/billing-reconcile'
      path: '/api/internal/billing-reconcile'
      fullPath: '/api/internal/billing-reconcile'
      preLoaderRoute: typeof ApiInternalBillingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/billing-portal': {
      id: '/api/internal/billing-portal'
      path: '/api/internal/billing-portal'
      fullPath: '/api/internal/billing-portal'
      preLoaderRoute: typeof ApiInternalBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/billing-checkout': {
      id: '/api/internal/billing-checkout'
      path: '/api/internal/billing-checkout'
      fullPath: '/api/internal/billing-checkout'
      preLoaderRoute: typeof ApiInternalBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super/observabilidade': {
      id: '/_authenticated/super/observabilidade'
      path: '/observabilidade'
      fullPath: '/super/observabilidade'
      preLoaderRoute: typeof AuthenticatedSuperObservabilidadeRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/domains': {
      id: '/_authenticated/super/domains'
      path: '/domains'
      fullPath: '/super/domains'
      preLoaderRoute: typeof AuthenticatedSuperDomainsRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/dlq': {
      id: '/_authenticated/super/dlq'
      path: '/dlq'
      fullPath: '/super/dlq'
      preLoaderRoute: typeof AuthenticatedSuperDlqRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/super/control-plane': {
      id: '/_authenticated/super/control-plane'
      path: '/control-plane'
      fullPath: '/super/control-plane'
      preLoaderRoute: typeof AuthenticatedSuperControlPlaneRouteImport
      parentRoute: typeof AuthenticatedSuperRoute
    }
    '/_authenticated/admin/tracking': {
      id: '/_authenticated/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AuthenticatedAdminTrackingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portais': {
      id: '/_authenticated/admin/portais'
      path: '/portais'
      fullPath: '/admin/portais'
      preLoaderRoute: typeof AuthenticatedAdminPortaisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/origens': {
      id: '/_authenticated/admin/origens'
      path: '/origens'
      fullPath: '/admin/origens'
      preLoaderRoute: typeof AuthenticatedAdminOrigensRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/motivos': {
      id: '/_authenticated/admin/motivos'
      path: '/motivos'
      fullPath: '/admin/motivos'
      preLoaderRoute: typeof AuthenticatedAdminMotivosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/midias': {
      id: '/_authenticated/admin/midias'
      path: '/midias'
      fullPath: '/admin/midias'
      preLoaderRoute: typeof AuthenticatedAdminMidiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/memberships': {
      id: '/_authenticated/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads-workspace': {
      id: '/_authenticated/admin/leads-workspace'
      path: '/leads-workspace'
      fullPath: '/admin/leads-workspace'
      preLoaderRoute: typeof AuthenticatedAdminLeadsWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipes': {
      id: '/_authenticated/admin/equipes'
      path: '/equipes'
      fullPath: '/admin/equipes'
      preLoaderRoute: typeof AuthenticatedAdminEquipesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm-operacoes': {
      id: '/_authenticated/admin/crm-operacoes'
      path: '/crm-operacoes'
      fullPath: '/admin/crm-operacoes'
      preLoaderRoute: typeof AuthenticatedAdminCrmOperacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/corretores': {
      id: '/_authenticated/admin/corretores'
      path: '/corretores'
      fullPath: '/admin/corretores'
      preLoaderRoute: typeof AuthenticatedAdminCorretoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms-transferencia': {
      id: '/_authenticated/admin/cms-transferencia'
      path: '/cms-transferencia'
      fullPath: '/admin/cms-transferencia'
      preLoaderRoute: typeof AuthenticatedAdminCmsTransferenciaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms-inventario': {
      id: '/_authenticated/admin/cms-inventario'
      path: '/cms-inventario'
      fullPath: '/admin/cms-inventario'
      preLoaderRoute: typeof AuthenticatedAdminCmsInventarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms-auditoria': {
      id: '/_authenticated/admin/cms-auditoria'
      path: '/cms-auditoria'
      fullPath: '/admin/cms-auditoria'
      preLoaderRoute: typeof AuthenticatedAdminCmsAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cidades': {
      id: '/_authenticated/admin/cidades'
      path: '/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AuthenticatedAdminCidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bairros': {
      id: '/_authenticated/admin/bairros'
      path: '/bairros'
      fullPath: '/admin/bairros'
      preLoaderRoute: typeof AuthenticatedAdminBairrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paginas/': {
      id: '/_authenticated/admin/paginas/'
      path: '/paginas'
      fullPath: '/admin/paginas/'
      preLoaderRoute: typeof AuthenticatedAdminPaginasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lancamentos/': {
      id: '/_authenticated/admin/lancamentos/'
      path: '/lancamentos'
      fullPath: '/admin/lancamentos/'
      preLoaderRoute: typeof AuthenticatedAdminLancamentosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis/': {
      id: '/_authenticated/admin/imoveis/'
      path: '/imoveis'
      fullPath: '/admin/imoveis/'
      preLoaderRoute: typeof AuthenticatedAdminImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/formularios/': {
      id: '/_authenticated/admin/formularios/'
      path: '/formularios'
      fullPath: '/admin/formularios/'
      preLoaderRoute: typeof AuthenticatedAdminFormulariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campanhas/': {
      id: '/_authenticated/admin/campanhas/'
      path: '/campanhas'
      fullPath: '/admin/campanhas/'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/portal-dlq-retry': {
      id: '/api/public/hooks/portal-dlq-retry'
      path: '/api/public/hooks/portal-dlq-retry'
      fullPath: '/api/public/hooks/portal-dlq-retry'
      preLoaderRoute: typeof ApiPublicHooksPortalDlqRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/billing-stripe-webhook': {
      id: '/api/public/hooks/billing-stripe-webhook'
      path: '/api/public/hooks/billing-stripe-webhook'
      fullPath: '/api/public/hooks/billing-stripe-webhook'
      preLoaderRoute: typeof ApiPublicHooksBillingStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/paginas/$id': {
      id: '/_authenticated/admin/paginas/$id'
      path: '/paginas/$id'
      fullPath: '/admin/paginas/$id'
      preLoaderRoute: typeof AuthenticatedAdminPaginasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lancamentos/novo': {
      id: '/_authenticated/admin/lancamentos/novo'
      path: '/lancamentos/novo'
      fullPath: '/admin/lancamentos/novo'
      preLoaderRoute: typeof AuthenticatedAdminLancamentosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lancamentos/$id': {
      id: '/_authenticated/admin/lancamentos/$id'
      path: '/lancamentos/$id'
      fullPath: '/admin/lancamentos/$id'
      preLoaderRoute: typeof AuthenticatedAdminLancamentosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis/novo': {
      id: '/_authenticated/admin/imoveis/novo'
      path: '/imoveis/novo'
      fullPath: '/admin/imoveis/novo'
      preLoaderRoute: typeof AuthenticatedAdminImoveisNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis/$id': {
      id: '/_authenticated/admin/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/admin/imoveis/$id'
      preLoaderRoute: typeof AuthenticatedAdminImoveisIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/formularios/$id': {
      id: '/_authenticated/admin/formularios/$id'
      path: '/formularios/$id'
      fullPath: '/admin/formularios/$id'
      preLoaderRoute: typeof AuthenticatedAdminFormulariosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campanhas/$id': {
      id: '/_authenticated/admin/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/admin/campanhas/$id'
      preLoaderRoute: typeof AuthenticatedAdminCampanhasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/novo': {
      id: '/_authenticated/admin/blog/novo'
      path: '/novo'
      fullPath: '/admin/blog/novo'
      preLoaderRoute: typeof AuthenticatedAdminBlogNovoRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminBlogRoute
    }
    '/api/public/feeds/$portal/$token': {
      id: '/api/public/feeds/$portal/$token'
      path: '/api/public/feeds/$portal/$token'
      fullPath: '/api/public/feeds/$portal/$token'
      preLoaderRoute: typeof ApiPublicFeedsPortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminBlogRouteChildren {
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogNovoRoute: typeof AuthenticatedAdminBlogNovoRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedAdminBlogRouteChildren: AuthenticatedAdminBlogRouteChildren =
  {
    AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
    AuthenticatedAdminBlogNovoRoute: AuthenticatedAdminBlogNovoRoute,
    AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  }

const AuthenticatedAdminBlogRouteWithChildren =
  AuthenticatedAdminBlogRoute._addFileChildren(
    AuthenticatedAdminBlogRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBairrosRoute: typeof AuthenticatedAdminBairrosRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRouteWithChildren
  AuthenticatedAdminCidadesRoute: typeof AuthenticatedAdminCidadesRoute
  AuthenticatedAdminCmsAuditoriaRoute: typeof AuthenticatedAdminCmsAuditoriaRoute
  AuthenticatedAdminCmsInventarioRoute: typeof AuthenticatedAdminCmsInventarioRoute
  AuthenticatedAdminCmsTransferenciaRoute: typeof AuthenticatedAdminCmsTransferenciaRoute
  AuthenticatedAdminCorretoresRoute: typeof AuthenticatedAdminCorretoresRoute
  AuthenticatedAdminCrmOperacoesRoute: typeof AuthenticatedAdminCrmOperacoesRoute
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminEquipesRoute: typeof AuthenticatedAdminEquipesRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLeadsWorkspaceRoute: typeof AuthenticatedAdminLeadsWorkspaceRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
  AuthenticatedAdminMidiasRoute: typeof AuthenticatedAdminMidiasRoute
  AuthenticatedAdminMotivosRoute: typeof AuthenticatedAdminMotivosRoute
  AuthenticatedAdminOrigensRoute: typeof AuthenticatedAdminOrigensRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminPortaisRoute: typeof AuthenticatedAdminPortaisRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminTrackingRoute: typeof AuthenticatedAdminTrackingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCampanhasIdRoute: typeof AuthenticatedAdminCampanhasIdRoute
  AuthenticatedAdminFormulariosIdRoute: typeof AuthenticatedAdminFormulariosIdRoute
  AuthenticatedAdminImoveisIdRoute: typeof AuthenticatedAdminImoveisIdRoute
  AuthenticatedAdminImoveisNovoRoute: typeof AuthenticatedAdminImoveisNovoRoute
  AuthenticatedAdminLancamentosIdRoute: typeof AuthenticatedAdminLancamentosIdRoute
  AuthenticatedAdminLancamentosNovoRoute: typeof AuthenticatedAdminLancamentosNovoRoute
  AuthenticatedAdminPaginasIdRoute: typeof AuthenticatedAdminPaginasIdRoute
  AuthenticatedAdminCampanhasIndexRoute: typeof AuthenticatedAdminCampanhasIndexRoute
  AuthenticatedAdminFormulariosIndexRoute: typeof AuthenticatedAdminFormulariosIndexRoute
  AuthenticatedAdminImoveisIndexRoute: typeof AuthenticatedAdminImoveisIndexRoute
  AuthenticatedAdminLancamentosIndexRoute: typeof AuthenticatedAdminLancamentosIndexRoute
  AuthenticatedAdminPaginasIndexRoute: typeof AuthenticatedAdminPaginasIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminBairrosRoute: AuthenticatedAdminBairrosRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRouteWithChildren,
  AuthenticatedAdminCidadesRoute: AuthenticatedAdminCidadesRoute,
  AuthenticatedAdminCmsAuditoriaRoute: AuthenticatedAdminCmsAuditoriaRoute,
  AuthenticatedAdminCmsInventarioRoute: AuthenticatedAdminCmsInventarioRoute,
  AuthenticatedAdminCmsTransferenciaRoute:
    AuthenticatedAdminCmsTransferenciaRoute,
  AuthenticatedAdminCorretoresRoute: AuthenticatedAdminCorretoresRoute,
  AuthenticatedAdminCrmOperacoesRoute: AuthenticatedAdminCrmOperacoesRoute,
  AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
  AuthenticatedAdminEquipesRoute: AuthenticatedAdminEquipesRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLeadsWorkspaceRoute: AuthenticatedAdminLeadsWorkspaceRoute,
  AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
  AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
  AuthenticatedAdminMidiasRoute: AuthenticatedAdminMidiasRoute,
  AuthenticatedAdminMotivosRoute: AuthenticatedAdminMotivosRoute,
  AuthenticatedAdminOrigensRoute: AuthenticatedAdminOrigensRoute,
  AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedAdminPortaisRoute: AuthenticatedAdminPortaisRoute,
  AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
  AuthenticatedAdminTrackingRoute: AuthenticatedAdminTrackingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCampanhasIdRoute: AuthenticatedAdminCampanhasIdRoute,
  AuthenticatedAdminFormulariosIdRoute: AuthenticatedAdminFormulariosIdRoute,
  AuthenticatedAdminImoveisIdRoute: AuthenticatedAdminImoveisIdRoute,
  AuthenticatedAdminImoveisNovoRoute: AuthenticatedAdminImoveisNovoRoute,
  AuthenticatedAdminLancamentosIdRoute: AuthenticatedAdminLancamentosIdRoute,
  AuthenticatedAdminLancamentosNovoRoute:
    AuthenticatedAdminLancamentosNovoRoute,
  AuthenticatedAdminPaginasIdRoute: AuthenticatedAdminPaginasIdRoute,
  AuthenticatedAdminCampanhasIndexRoute: AuthenticatedAdminCampanhasIndexRoute,
  AuthenticatedAdminFormulariosIndexRoute:
    AuthenticatedAdminFormulariosIndexRoute,
  AuthenticatedAdminImoveisIndexRoute: AuthenticatedAdminImoveisIndexRoute,
  AuthenticatedAdminLancamentosIndexRoute:
    AuthenticatedAdminLancamentosIndexRoute,
  AuthenticatedAdminPaginasIndexRoute: AuthenticatedAdminPaginasIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSuperRouteChildren {
  AuthenticatedSuperControlPlaneRoute: typeof AuthenticatedSuperControlPlaneRoute
  AuthenticatedSuperDlqRoute: typeof AuthenticatedSuperDlqRoute
  AuthenticatedSuperDomainsRoute: typeof AuthenticatedSuperDomainsRoute
  AuthenticatedSuperObservabilidadeRoute: typeof AuthenticatedSuperObservabilidadeRoute
  AuthenticatedSuperIndexRoute: typeof AuthenticatedSuperIndexRoute
}

const AuthenticatedSuperRouteChildren: AuthenticatedSuperRouteChildren = {
  AuthenticatedSuperControlPlaneRoute: AuthenticatedSuperControlPlaneRoute,
  AuthenticatedSuperDlqRoute: AuthenticatedSuperDlqRoute,
  AuthenticatedSuperDomainsRoute: AuthenticatedSuperDomainsRoute,
  AuthenticatedSuperObservabilidadeRoute:
    AuthenticatedSuperObservabilidadeRoute,
  AuthenticatedSuperIndexRoute: AuthenticatedSuperIndexRoute,
}

const AuthenticatedSuperRouteWithChildren =
  AuthenticatedSuperRoute._addFileChildren(AuthenticatedSuperRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedSuperRoute: AuthenticatedSuperRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LancamentosRouteChildren {
  LancamentosSlugRoute: typeof LancamentosSlugRoute
}

const LancamentosRouteChildren: LancamentosRouteChildren = {
  LancamentosSlugRoute: LancamentosSlugRoute,
}

const LancamentosRouteWithChildren = LancamentosRoute._addFileChildren(
  LancamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnuncieRoute: AnuncieRoute,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  ImoveisRoute: ImoveisRoute,
  LancamentosRoute: LancamentosRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ImovelSlugRoute: ImovelSlugRoute,
  PSlugRoute: PSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiInternalBillingCheckoutRoute: ApiInternalBillingCheckoutRoute,
  ApiInternalBillingPortalRoute: ApiInternalBillingPortalRoute,
  ApiInternalBillingReconcileRoute: ApiInternalBillingReconcileRoute,
  ApiInternalSpr03ManagedSecretProvisionRoute:
    ApiInternalSpr03ManagedSecretProvisionRoute,
  ApiPublicPortalLeadsRoute: ApiPublicPortalLeadsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksBillingStripeWebhookRoute:
    ApiPublicHooksBillingStripeWebhookRoute,
  ApiPublicHooksPortalDlqRetryRoute: ApiPublicHooksPortalDlqRetryRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicFeedsPortalTokenRoute: ApiPublicFeedsPortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
