/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImovelSlugRouteImport } from './routes/imovel.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated.admin.site'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated.admin.leads'
import { Route as AuthenticatedAdminImoveisRouteImport } from './routes/_authenticated.admin.imoveis'
import { Route as AuthenticatedAdminCorretoresRouteImport } from './routes/_authenticated.admin.corretores'
import { Route as AuthenticatedAdminBairrosRouteImport } from './routes/_authenticated.admin.bairros'
import { Route as AuthenticatedAdminImoveisNovoRouteImport } from './routes/_authenticated.admin.imoveis.novo'
import { Route as AuthenticatedAdminImoveisIdRouteImport } from './routes/_authenticated.admin.imoveis.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelSlugRoute = ImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImoveisRoute =
  AuthenticatedAdminImoveisRouteImport.update({
    id: '/imoveis',
    path: '/imoveis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCorretoresRoute =
  AuthenticatedAdminCorretoresRouteImport.update({
    id: '/corretores',
    path: '/corretores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBairrosRoute =
  AuthenticatedAdminBairrosRouteImport.update({
    id: '/bairros',
    path: '/bairros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImoveisNovoRoute =
  AuthenticatedAdminImoveisNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminImoveisRoute,
  } as any)
const AuthenticatedAdminImoveisIdRoute =
  AuthenticatedAdminImoveisIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminImoveisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/lancamentos': typeof LancamentosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/imovel/$slug': typeof ImovelSlugRoute
  '/admin/bairros': typeof AuthenticatedAdminBairrosRoute
  '/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisRouteWithChildren
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/imoveis/$id': typeof AuthenticatedAdminImoveisIdRoute
  '/admin/imoveis/novo': typeof AuthenticatedAdminImoveisNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/lancamentos': typeof LancamentosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/admin/bairros': typeof AuthenticatedAdminBairrosRoute
  '/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisRouteWithChildren
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/imoveis/$id': typeof AuthenticatedAdminImoveisIdRoute
  '/admin/imoveis/novo': typeof AuthenticatedAdminImoveisNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/lancamentos': typeof LancamentosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/imovel/$slug': typeof ImovelSlugRoute
  '/_authenticated/admin/bairros': typeof AuthenticatedAdminBairrosRoute
  '/_authenticated/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/_authenticated/admin/imoveis': typeof AuthenticatedAdminImoveisRouteWithChildren
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/imoveis/$id': typeof AuthenticatedAdminImoveisIdRoute
  '/_authenticated/admin/imoveis/novo': typeof AuthenticatedAdminImoveisNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/imoveis'
    | '/lancamentos'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/imovel/$slug'
    | '/admin/bairros'
    | '/admin/corretores'
    | '/admin/imoveis'
    | '/admin/leads'
    | '/admin/site'
    | '/api/public/bootstrap-admin'
    | '/admin/'
    | '/admin/imoveis/$id'
    | '/admin/imoveis/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/imoveis'
    | '/lancamentos'
    | '/sitemap.xml'
    | '/sobre'
    | '/imovel/$slug'
    | '/admin/bairros'
    | '/admin/corretores'
    | '/admin/imoveis'
    | '/admin/leads'
    | '/admin/site'
    | '/api/public/bootstrap-admin'
    | '/admin'
    | '/admin/imoveis/$id'
    | '/admin/imoveis/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anuncie'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/imoveis'
    | '/lancamentos'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/imovel/$slug'
    | '/_authenticated/admin/bairros'
    | '/_authenticated/admin/corretores'
    | '/_authenticated/admin/imoveis'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/site'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/imoveis/$id'
    | '/_authenticated/admin/imoveis/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnuncieRoute: typeof AnuncieRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  ImoveisRoute: typeof ImoveisRoute
  LancamentosRoute: typeof LancamentosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ImovelSlugRoute: typeof ImovelSlugRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$slug': {
      id: '/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof ImovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis': {
      id: '/_authenticated/admin/imoveis'
      path: '/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AuthenticatedAdminImoveisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/corretores': {
      id: '/_authenticated/admin/corretores'
      path: '/corretores'
      fullPath: '/admin/corretores'
      preLoaderRoute: typeof AuthenticatedAdminCorretoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bairros': {
      id: '/_authenticated/admin/bairros'
      path: '/bairros'
      fullPath: '/admin/bairros'
      preLoaderRoute: typeof AuthenticatedAdminBairrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis/novo': {
      id: '/_authenticated/admin/imoveis/novo'
      path: '/novo'
      fullPath: '/admin/imoveis/novo'
      preLoaderRoute: typeof AuthenticatedAdminImoveisNovoRouteImport
      parentRoute: typeof AuthenticatedAdminImoveisRoute
    }
    '/_authenticated/admin/imoveis/$id': {
      id: '/_authenticated/admin/imoveis/$id'
      path: '/$id'
      fullPath: '/admin/imoveis/$id'
      preLoaderRoute: typeof AuthenticatedAdminImoveisIdRouteImport
      parentRoute: typeof AuthenticatedAdminImoveisRoute
    }
  }
}

interface AuthenticatedAdminImoveisRouteChildren {
  AuthenticatedAdminImoveisIdRoute: typeof AuthenticatedAdminImoveisIdRoute
  AuthenticatedAdminImoveisNovoRoute: typeof AuthenticatedAdminImoveisNovoRoute
}

const AuthenticatedAdminImoveisRouteChildren: AuthenticatedAdminImoveisRouteChildren =
  {
    AuthenticatedAdminImoveisIdRoute: AuthenticatedAdminImoveisIdRoute,
    AuthenticatedAdminImoveisNovoRoute: AuthenticatedAdminImoveisNovoRoute,
  }

const AuthenticatedAdminImoveisRouteWithChildren =
  AuthenticatedAdminImoveisRoute._addFileChildren(
    AuthenticatedAdminImoveisRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBairrosRoute: typeof AuthenticatedAdminBairrosRoute
  AuthenticatedAdminCorretoresRoute: typeof AuthenticatedAdminCorretoresRoute
  AuthenticatedAdminImoveisRoute: typeof AuthenticatedAdminImoveisRouteWithChildren
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBairrosRoute: AuthenticatedAdminBairrosRoute,
  AuthenticatedAdminCorretoresRoute: AuthenticatedAdminCorretoresRoute,
  AuthenticatedAdminImoveisRoute: AuthenticatedAdminImoveisRouteWithChildren,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnuncieRoute: AnuncieRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  ImoveisRoute: ImoveisRoute,
  LancamentosRoute: LancamentosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ImovelSlugRoute: ImovelSlugRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
